# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jfb-{{ .Values.global.developer }}-docker-pv
# spec:
#   capacity:
#     storage: 10Ki
#   accessModes:
#     - ReadOnlyMany
#   claimRef:
#     namespace: {{ .Values.global.developer }}
#     name: jfb-{{ .Values.global.developer }}-docker-pvc
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: {{ .Values.volume.launcher.docker }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfb-{{ .Values.global.developer }}-docker-pvc
  namespace: {{ .Values.global.developer }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ki
  storageClassName: jfb-azurefile-default
