{{- define "srcVolume" -}}
{{- range $app := .appList }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jfb-{{ $.developer }}-src-{{ $app }}-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: jfb-{{ $.developer }}-src-{{ $app }}-pvc
    namespace: {{ $.developer }}
  persistentVolumeReclaimPolicy: Retain
  {{ $.volumeType }}:
    {{- if eq $.volumeType "nfs" }}
    server: {{ $.nfsServer }}
    {{- end }}
    path: {{ $.baseDir }}/dev/{{ $app | replace "-" "_" }}_app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfb-{{ $.developer }}-src-{{ $app }}-pvc
  namespace: {{ $.developer }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
{{- end }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jfb-{{ $.developer }}-utils-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{  $.developer }}
    name: jfb-{{  $.developer }}-utils-pvc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ $.baseDir }}/dev/utils
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfb-{{ $.developer }}-utils-pvc
  namespace: {{ $.developer }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
{{- end }}

{{- if .Values.volume.src.enabled }}
{{- $appList := list "built-in-model" "dashboard" "dataset" "deployment" "image" "resource" "resource-kube" "training" "user" "workspace" -}}
{{- $srcValue := dict -}}
{{- $_ := set $srcValue "appList" $appList }}
{{- $_ := set $srcValue "developer" .Values.global.developer }}
{{- $_ := set $srcValue "volumeType" .Values.volume.src.type  }}
{{- $_ := set $srcValue "nfsServer" .Values.volume.src.server  }}
{{- $_ := set $srcValue "baseDir" ( include "src.baseDir" . )  }}
{{- include "srcVolume" $srcValue }}
{{- end }}
---
#