apiVersion: v1
kind: Service
metadata:
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}} 
  name: {{ .Values.pod_name }}---system-1
  namespace: "{{ include "namespace" . }}"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    project_item_id: {{ .Values.labels.project_item_id | quote  }}
    project_tool_type: {{ .Values.labels.project_tool_type }}
    index: "0"
  type: ClusterIP