{{/*
필요한 앱에서 rbac 세팅
clusteradmin: workspace 작업시 사용, + ... TODO COMMENT
*/}}

{{/*
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusteradmin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["PersistentVolumes", "PersistentVolumeClaims","PersistentVolumeClaims/status","nodes"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]


# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   creationTimestamp: null
#   annotations:
#     rbac.authorization.kubernetes.io/autoupdate: "true"
#   labels:
#     kubernetes.io/bootstrapping: rbac-defaults
#   name: jfb-{{ .Values.global.jfb.namespace}}-cluster-role
# rules:
# - apiGroups: [""]
#   resources: ["*"]
#   verbs: ["*"]
# - apiGroups: [""]
#   resources: ["nodes","PersistentVolumes", "PersistentVolumeClaims","PersistentVolumeClaims/status","namespaces"]
# #   verbs: ["*"]
#   verbs: ["create", "delete","get","list", "watch", "update"]

# - apiGroups: ["storage.k8s.io/v1 "]
#   resources: ["storageclasses"]
#   # verbs: ["list","create", "get"]
#   verbs: ["create", "delete","get","list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: clusteradmin
  namespace: {{ .Values.global.jfb.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role
  apiGroup: rbac.authorization.k8s.io
*/}}
