// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: logquery/logquery.proto

package go_poc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogQueryService_QueryWorkspaceDashboardLogs_FullMethodName    = "/logquery.LogQueryService/QueryWorkspaceDashboardLogs"
	LogQueryService_QueryAdminDashboardLogs_FullMethodName        = "/logquery.LogQueryService/QueryAdminDashboardLogs"
	LogQueryService_QueryAdminDetailLogs_FullMethodName           = "/logquery.LogQueryService/QueryAdminDetailLogs"
	LogQueryService_QueryTrainingFigureLogs_FullMethodName        = "/logquery.LogQueryService/QueryTrainingFigureLogs"
	LogQueryService_QueryTrainingAllLogs_FullMethodName           = "/logquery.LogQueryService/QueryTrainingAllLogs"
	LogQueryService_QueryDeploymentAllLogs_FullMethodName         = "/logquery.LogQueryService/QueryDeploymentAllLogs"
	LogQueryService_QueryImageAllLogs_FullMethodName              = "/logquery.LogQueryService/QueryImageAllLogs"
	LogQueryService_QueryFineTuningAllLogs_FullMethodName         = "/logquery.LogQueryService/QueryFineTuningAllLogs"
	LogQueryService_QueryFineTuningFigureLogs_FullMethodName      = "/logquery.LogQueryService/QueryFineTuningFigureLogs"
	LogQueryService_QueryRecentWorkerInfoLog_FullMethodName       = "/logquery.LogQueryService/QueryRecentWorkerInfoLog"
	LogQueryService_QueryWorkspaceResourceLogs_FullMethodName     = "/logquery.LogQueryService/QueryWorkspaceResourceLogs"
	LogQueryService_QueryClusterResourceLogs_FullMethodName       = "/logquery.LogQueryService/QueryClusterResourceLogs"
	LogQueryService_ElasticNativeQuery_FullMethodName             = "/logquery.LogQueryService/ElasticNativeQuery"
	LogQueryService_QueryBillingNetwork_FullMethodName            = "/logquery.LogQueryService/QueryBillingNetwork"
	LogQueryService_QueryBillingInstance_FullMethodName           = "/logquery.LogQueryService/QueryBillingInstance"
	LogQueryService_QueryWorkspaceAllocationTime_FullMethodName   = "/logquery.LogQueryService/QueryWorkspaceAllocationTime"
	LogQueryService_QueryWorkspaceRecentModifyTime_FullMethodName = "/logquery.LogQueryService/QueryWorkspaceRecentModifyTime"
	LogQueryService_QueryAllocationHistory_FullMethodName         = "/logquery.LogQueryService/QueryAllocationHistory"
	LogQueryService_QuerySummaryAllocationUptime_FullMethodName   = "/logquery.LogQueryService/QuerySummaryAllocationUptime"
)

// LogQueryServiceClient is the client API for LogQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogQueryServiceClient interface {
	QueryWorkspaceDashboardLogs(ctx context.Context, in *WorkspaceDashboardRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryAdminDashboardLogs(ctx context.Context, in *AdminDashboardRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryAdminDetailLogs(ctx context.Context, in *AdminDetailRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryTrainingFigureLogs(ctx context.Context, in *TrainingFigureRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryTrainingAllLogs(ctx context.Context, in *TrainingAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryDeploymentAllLogs(ctx context.Context, in *DeploymentAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryImageAllLogs(ctx context.Context, in *ImageAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryFineTuningAllLogs(ctx context.Context, in *FineTuningAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryFineTuningFigureLogs(ctx context.Context, in *FineTuningFigureRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error)
	QueryRecentWorkerInfoLog(ctx context.Context, in *RecentWorkerInfoRequest, opts ...grpc.CallOption) (*RecentWorkerInfoResponse, error)
	QueryWorkspaceResourceLogs(ctx context.Context, in *WorkspaceResourceRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	QueryClusterResourceLogs(ctx context.Context, in *ClusterResourceRequest, opts ...grpc.CallOption) (*structpb.Struct, error)
	ElasticNativeQuery(ctx context.Context, in *ElasticNativeQueryRequest, opts ...grpc.CallOption) (*ElasticNativeQueryResponse, error)
	QueryBillingNetwork(ctx context.Context, in *BillingNetworkRequest, opts ...grpc.CallOption) (*BillingNetworkResponse, error)
	QueryBillingInstance(ctx context.Context, in *BillingInstanceRequest, opts ...grpc.CallOption) (*BillingInstanceResponse, error)
	QueryWorkspaceAllocationTime(ctx context.Context, in *WorkspaceAllocationTimeRequest, opts ...grpc.CallOption) (*WorkspaceAllocationTimeResponse, error)
	QueryWorkspaceRecentModifyTime(ctx context.Context, in *WorkspaceRecentModifyTimeRequest, opts ...grpc.CallOption) (*WorkspaceRecentModifyTimeResponse, error)
	QueryAllocationHistory(ctx context.Context, in *AllocationHistoryRequest, opts ...grpc.CallOption) (*AllocationHistoryResponse, error)
	QuerySummaryAllocationUptime(ctx context.Context, in *SummaryAllocationUptimeRequest, opts ...grpc.CallOption) (*SummaryAllocationUptimeResponse, error)
}

type logQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogQueryServiceClient(cc grpc.ClientConnInterface) LogQueryServiceClient {
	return &logQueryServiceClient{cc}
}

func (c *logQueryServiceClient) QueryWorkspaceDashboardLogs(ctx context.Context, in *WorkspaceDashboardRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryWorkspaceDashboardLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryAdminDashboardLogs(ctx context.Context, in *AdminDashboardRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryAdminDashboardLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryAdminDetailLogs(ctx context.Context, in *AdminDetailRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryAdminDetailLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryTrainingFigureLogs(ctx context.Context, in *TrainingFigureRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryTrainingFigureLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryTrainingAllLogs(ctx context.Context, in *TrainingAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryTrainingAllLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryDeploymentAllLogs(ctx context.Context, in *DeploymentAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryDeploymentAllLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryImageAllLogs(ctx context.Context, in *ImageAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryImageAllLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryFineTuningAllLogs(ctx context.Context, in *FineTuningAllRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryFineTuningAllLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryFineTuningFigureLogs(ctx context.Context, in *FineTuningFigureRequest, opts ...grpc.CallOption) (*SummaryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryLogsResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryFineTuningFigureLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryRecentWorkerInfoLog(ctx context.Context, in *RecentWorkerInfoRequest, opts ...grpc.CallOption) (*RecentWorkerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecentWorkerInfoResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryRecentWorkerInfoLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryWorkspaceResourceLogs(ctx context.Context, in *WorkspaceResourceRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, LogQueryService_QueryWorkspaceResourceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryClusterResourceLogs(ctx context.Context, in *ClusterResourceRequest, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, LogQueryService_QueryClusterResourceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) ElasticNativeQuery(ctx context.Context, in *ElasticNativeQueryRequest, opts ...grpc.CallOption) (*ElasticNativeQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElasticNativeQueryResponse)
	err := c.cc.Invoke(ctx, LogQueryService_ElasticNativeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryBillingNetwork(ctx context.Context, in *BillingNetworkRequest, opts ...grpc.CallOption) (*BillingNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillingNetworkResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryBillingNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryBillingInstance(ctx context.Context, in *BillingInstanceRequest, opts ...grpc.CallOption) (*BillingInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillingInstanceResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryBillingInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryWorkspaceAllocationTime(ctx context.Context, in *WorkspaceAllocationTimeRequest, opts ...grpc.CallOption) (*WorkspaceAllocationTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceAllocationTimeResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryWorkspaceAllocationTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryWorkspaceRecentModifyTime(ctx context.Context, in *WorkspaceRecentModifyTimeRequest, opts ...grpc.CallOption) (*WorkspaceRecentModifyTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceRecentModifyTimeResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryWorkspaceRecentModifyTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QueryAllocationHistory(ctx context.Context, in *AllocationHistoryRequest, opts ...grpc.CallOption) (*AllocationHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocationHistoryResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QueryAllocationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logQueryServiceClient) QuerySummaryAllocationUptime(ctx context.Context, in *SummaryAllocationUptimeRequest, opts ...grpc.CallOption) (*SummaryAllocationUptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryAllocationUptimeResponse)
	err := c.cc.Invoke(ctx, LogQueryService_QuerySummaryAllocationUptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogQueryServiceServer is the server API for LogQueryService service.
// All implementations must embed UnimplementedLogQueryServiceServer
// for forward compatibility.
type LogQueryServiceServer interface {
	QueryWorkspaceDashboardLogs(context.Context, *WorkspaceDashboardRequest) (*SummaryLogsResponse, error)
	QueryAdminDashboardLogs(context.Context, *AdminDashboardRequest) (*SummaryLogsResponse, error)
	QueryAdminDetailLogs(context.Context, *AdminDetailRequest) (*SummaryLogsResponse, error)
	QueryTrainingFigureLogs(context.Context, *TrainingFigureRequest) (*SummaryLogsResponse, error)
	QueryTrainingAllLogs(context.Context, *TrainingAllRequest) (*SummaryLogsResponse, error)
	QueryDeploymentAllLogs(context.Context, *DeploymentAllRequest) (*SummaryLogsResponse, error)
	QueryImageAllLogs(context.Context, *ImageAllRequest) (*SummaryLogsResponse, error)
	QueryFineTuningAllLogs(context.Context, *FineTuningAllRequest) (*SummaryLogsResponse, error)
	QueryFineTuningFigureLogs(context.Context, *FineTuningFigureRequest) (*SummaryLogsResponse, error)
	QueryRecentWorkerInfoLog(context.Context, *RecentWorkerInfoRequest) (*RecentWorkerInfoResponse, error)
	QueryWorkspaceResourceLogs(context.Context, *WorkspaceResourceRequest) (*structpb.Struct, error)
	QueryClusterResourceLogs(context.Context, *ClusterResourceRequest) (*structpb.Struct, error)
	ElasticNativeQuery(context.Context, *ElasticNativeQueryRequest) (*ElasticNativeQueryResponse, error)
	QueryBillingNetwork(context.Context, *BillingNetworkRequest) (*BillingNetworkResponse, error)
	QueryBillingInstance(context.Context, *BillingInstanceRequest) (*BillingInstanceResponse, error)
	QueryWorkspaceAllocationTime(context.Context, *WorkspaceAllocationTimeRequest) (*WorkspaceAllocationTimeResponse, error)
	QueryWorkspaceRecentModifyTime(context.Context, *WorkspaceRecentModifyTimeRequest) (*WorkspaceRecentModifyTimeResponse, error)
	QueryAllocationHistory(context.Context, *AllocationHistoryRequest) (*AllocationHistoryResponse, error)
	QuerySummaryAllocationUptime(context.Context, *SummaryAllocationUptimeRequest) (*SummaryAllocationUptimeResponse, error)
	mustEmbedUnimplementedLogQueryServiceServer()
}

// UnimplementedLogQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogQueryServiceServer struct{}

func (UnimplementedLogQueryServiceServer) QueryWorkspaceDashboardLogs(context.Context, *WorkspaceDashboardRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWorkspaceDashboardLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryAdminDashboardLogs(context.Context, *AdminDashboardRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAdminDashboardLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryAdminDetailLogs(context.Context, *AdminDetailRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAdminDetailLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryTrainingFigureLogs(context.Context, *TrainingFigureRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTrainingFigureLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryTrainingAllLogs(context.Context, *TrainingAllRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTrainingAllLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryDeploymentAllLogs(context.Context, *DeploymentAllRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeploymentAllLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryImageAllLogs(context.Context, *ImageAllRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryImageAllLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryFineTuningAllLogs(context.Context, *FineTuningAllRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFineTuningAllLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryFineTuningFigureLogs(context.Context, *FineTuningFigureRequest) (*SummaryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFineTuningFigureLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryRecentWorkerInfoLog(context.Context, *RecentWorkerInfoRequest) (*RecentWorkerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRecentWorkerInfoLog not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryWorkspaceResourceLogs(context.Context, *WorkspaceResourceRequest) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWorkspaceResourceLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryClusterResourceLogs(context.Context, *ClusterResourceRequest) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryClusterResourceLogs not implemented")
}
func (UnimplementedLogQueryServiceServer) ElasticNativeQuery(context.Context, *ElasticNativeQueryRequest) (*ElasticNativeQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ElasticNativeQuery not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryBillingNetwork(context.Context, *BillingNetworkRequest) (*BillingNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBillingNetwork not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryBillingInstance(context.Context, *BillingInstanceRequest) (*BillingInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBillingInstance not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryWorkspaceAllocationTime(context.Context, *WorkspaceAllocationTimeRequest) (*WorkspaceAllocationTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWorkspaceAllocationTime not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryWorkspaceRecentModifyTime(context.Context, *WorkspaceRecentModifyTimeRequest) (*WorkspaceRecentModifyTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWorkspaceRecentModifyTime not implemented")
}
func (UnimplementedLogQueryServiceServer) QueryAllocationHistory(context.Context, *AllocationHistoryRequest) (*AllocationHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAllocationHistory not implemented")
}
func (UnimplementedLogQueryServiceServer) QuerySummaryAllocationUptime(context.Context, *SummaryAllocationUptimeRequest) (*SummaryAllocationUptimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySummaryAllocationUptime not implemented")
}
func (UnimplementedLogQueryServiceServer) mustEmbedUnimplementedLogQueryServiceServer() {}
func (UnimplementedLogQueryServiceServer) testEmbeddedByValue()                         {}

// UnsafeLogQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogQueryServiceServer will
// result in compilation errors.
type UnsafeLogQueryServiceServer interface {
	mustEmbedUnimplementedLogQueryServiceServer()
}

func RegisterLogQueryServiceServer(s grpc.ServiceRegistrar, srv LogQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogQueryService_ServiceDesc, srv)
}

func _LogQueryService_QueryWorkspaceDashboardLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryWorkspaceDashboardLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryWorkspaceDashboardLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryWorkspaceDashboardLogs(ctx, req.(*WorkspaceDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryAdminDashboardLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryAdminDashboardLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryAdminDashboardLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryAdminDashboardLogs(ctx, req.(*AdminDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryAdminDetailLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryAdminDetailLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryAdminDetailLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryAdminDetailLogs(ctx, req.(*AdminDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryTrainingFigureLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingFigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryTrainingFigureLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryTrainingFigureLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryTrainingFigureLogs(ctx, req.(*TrainingFigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryTrainingAllLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryTrainingAllLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryTrainingAllLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryTrainingAllLogs(ctx, req.(*TrainingAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryDeploymentAllLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryDeploymentAllLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryDeploymentAllLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryDeploymentAllLogs(ctx, req.(*DeploymentAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryImageAllLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryImageAllLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryImageAllLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryImageAllLogs(ctx, req.(*ImageAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryFineTuningAllLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FineTuningAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryFineTuningAllLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryFineTuningAllLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryFineTuningAllLogs(ctx, req.(*FineTuningAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryFineTuningFigureLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FineTuningFigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryFineTuningFigureLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryFineTuningFigureLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryFineTuningFigureLogs(ctx, req.(*FineTuningFigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryRecentWorkerInfoLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentWorkerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryRecentWorkerInfoLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryRecentWorkerInfoLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryRecentWorkerInfoLog(ctx, req.(*RecentWorkerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryWorkspaceResourceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryWorkspaceResourceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryWorkspaceResourceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryWorkspaceResourceLogs(ctx, req.(*WorkspaceResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryClusterResourceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryClusterResourceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryClusterResourceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryClusterResourceLogs(ctx, req.(*ClusterResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_ElasticNativeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElasticNativeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).ElasticNativeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_ElasticNativeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).ElasticNativeQuery(ctx, req.(*ElasticNativeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryBillingNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillingNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryBillingNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryBillingNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryBillingNetwork(ctx, req.(*BillingNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryBillingInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillingInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryBillingInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryBillingInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryBillingInstance(ctx, req.(*BillingInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryWorkspaceAllocationTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceAllocationTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryWorkspaceAllocationTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryWorkspaceAllocationTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryWorkspaceAllocationTime(ctx, req.(*WorkspaceAllocationTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryWorkspaceRecentModifyTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRecentModifyTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryWorkspaceRecentModifyTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryWorkspaceRecentModifyTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryWorkspaceRecentModifyTime(ctx, req.(*WorkspaceRecentModifyTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QueryAllocationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QueryAllocationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QueryAllocationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QueryAllocationHistory(ctx, req.(*AllocationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogQueryService_QuerySummaryAllocationUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryAllocationUptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServiceServer).QuerySummaryAllocationUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQueryService_QuerySummaryAllocationUptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServiceServer).QuerySummaryAllocationUptime(ctx, req.(*SummaryAllocationUptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogQueryService_ServiceDesc is the grpc.ServiceDesc for LogQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logquery.LogQueryService",
	HandlerType: (*LogQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryWorkspaceDashboardLogs",
			Handler:    _LogQueryService_QueryWorkspaceDashboardLogs_Handler,
		},
		{
			MethodName: "QueryAdminDashboardLogs",
			Handler:    _LogQueryService_QueryAdminDashboardLogs_Handler,
		},
		{
			MethodName: "QueryAdminDetailLogs",
			Handler:    _LogQueryService_QueryAdminDetailLogs_Handler,
		},
		{
			MethodName: "QueryTrainingFigureLogs",
			Handler:    _LogQueryService_QueryTrainingFigureLogs_Handler,
		},
		{
			MethodName: "QueryTrainingAllLogs",
			Handler:    _LogQueryService_QueryTrainingAllLogs_Handler,
		},
		{
			MethodName: "QueryDeploymentAllLogs",
			Handler:    _LogQueryService_QueryDeploymentAllLogs_Handler,
		},
		{
			MethodName: "QueryImageAllLogs",
			Handler:    _LogQueryService_QueryImageAllLogs_Handler,
		},
		{
			MethodName: "QueryFineTuningAllLogs",
			Handler:    _LogQueryService_QueryFineTuningAllLogs_Handler,
		},
		{
			MethodName: "QueryFineTuningFigureLogs",
			Handler:    _LogQueryService_QueryFineTuningFigureLogs_Handler,
		},
		{
			MethodName: "QueryRecentWorkerInfoLog",
			Handler:    _LogQueryService_QueryRecentWorkerInfoLog_Handler,
		},
		{
			MethodName: "QueryWorkspaceResourceLogs",
			Handler:    _LogQueryService_QueryWorkspaceResourceLogs_Handler,
		},
		{
			MethodName: "QueryClusterResourceLogs",
			Handler:    _LogQueryService_QueryClusterResourceLogs_Handler,
		},
		{
			MethodName: "ElasticNativeQuery",
			Handler:    _LogQueryService_ElasticNativeQuery_Handler,
		},
		{
			MethodName: "QueryBillingNetwork",
			Handler:    _LogQueryService_QueryBillingNetwork_Handler,
		},
		{
			MethodName: "QueryBillingInstance",
			Handler:    _LogQueryService_QueryBillingInstance_Handler,
		},
		{
			MethodName: "QueryWorkspaceAllocationTime",
			Handler:    _LogQueryService_QueryWorkspaceAllocationTime_Handler,
		},
		{
			MethodName: "QueryWorkspaceRecentModifyTime",
			Handler:    _LogQueryService_QueryWorkspaceRecentModifyTime_Handler,
		},
		{
			MethodName: "QueryAllocationHistory",
			Handler:    _LogQueryService_QueryAllocationHistory_Handler,
		},
		{
			MethodName: "QuerySummaryAllocationUptime",
			Handler:    _LogQueryService_QuerySummaryAllocationUptime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logquery/logquery.proto",
}
