// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// source: sensor_types.proto
// source: command.proto
// source: devices.proto
// source: configs.proto
// source: devices_doc.proto

package server

import "gitlab.suredatalab.kr/sdlmicro/middleware/auth"

func Register() error {
	if err := auth.Register(&auth.RegisterRequest{
		ServiceName: "devices",
		Resources: map[string]string{
			"create-device":         "장치 생성 권한",
			"create-device-config":  "장치 설정 생성 권한",
			"create-sensor-type":    "생성 권한",
			"device-admin":          "장치 관리자",
			"manage-device-configs": "장치 설정 관리 권한",
			"manage-devices":        "장치 관리 권한",
			"manage-sensor-types":   "관리 권한",
			"query-device-configs":  "장치 설정 검색 권한",
			"query-devices":         "장치 검색 권한",
			"query-sensor-types":    "검색 권한",
			"view-devices":          "장치 조회 권한",
		},
		AdminRole: "device-admin",
		Roles: map[string][]string{
			"/devices.DeviceConfigs/CreateConfig": {
				"create-device-config",
			},
			"/devices.DeviceConfigs/DeleteConfig": {
				"manage-device-configs",
			},
			"/devices.DeviceConfigs/ListDevice": {
				"create-device-config",
			},
			"/devices.DeviceConfigs/SearchConfig": {
				"query-device-configs",
				"manage-device-configs",
			},
			"/devices.Devices/AttachDevice": {
				"manage-devices",
			},
			"/devices.Devices/Command": {
				"manage-devices",
			},
			"/devices.Devices/CreateDevice": {
				"create-device",
			},
			"/devices.Devices/DeleteSensorLimit": {
				"manage-devices",
			},
			"/devices.Devices/DetachDevice": {
				"manage-devices",
			},
			"/devices.Devices/GetCommand": {
				"manage-devices",
			},
			"/devices.Devices/GetDevice": {
				"view-devices",
				"manage-devices",
			},
			"/devices.Devices/GetSensorLimit": {
				"view-devices",
			},
			"/devices.Devices/Histories": {
				"view-devices",
				"manage-devices",
			},
			"/devices.Devices/Search": {
				"query-devices",
				"manage-devices",
			},
			"/devices.Devices/SetSensorLimit": {
				"manage-devices",
			},
			"/devices.Devices/UpdateDevice": {
				"manage-devices",
			},
			"/devices.SensorTypes/CreateType": {
				"create-sensor-type",
			},
			"/devices.SensorTypes/DeleteType": {
				"manage-sensor-types",
			},
			"/devices.SensorTypes/SearchType": {
				"query-sensor-types",
				"manage-sensor-types",
			},
		},
	}); err != nil {
		return err
	}

	return nil
}

func Deregister() error {
	if err := auth.Deregister(); err != nil {
		return err
	}

	return nil
}
