// Code generated by protoc-gen-go-pg.
package server

import (
	"github.com/go-pg/pg/v10/orm"
	"gitlab.suredatalab.kr/sdlmicro/middleware/log"
	"gitlab.suredatalab.kr/sdlmicro/middleware/pgorm"

	"gitlab.suredatalab.kr/beymons/devices"
)

var ormModels = []interface{}{
	(*devices.SensorType)(nil),
	(*devices.SensorTypeAttribute)(nil),
	(*devices.Device)(nil),
	(*devices.DeviceRelation)(nil),
	(*devices.DeviceHistory)(nil),
	(*devices.DeviceUpdateHistory)(nil),
	(*devices.DeviceStatusHistory)(nil),
	(*devices.Sensor)(nil),
	(*devices.DeviceCommandHistory)(nil),
	(*devices.SensorLimit)(nil),
	(*devices.DeviceConfig)(nil),
	(*devices.DeviceConfigLink)(nil),
}

// 테이블 생성 함수
func createScheme() {
	if _, err := pgorm.ConnectDB(); err != nil {
		log.Fatal("DB connection failed", "error", err)
	}

	// DB Connection
	conn := pgorm.Conn()
	defer conn.Close()

	// Create tables
	for _, model := range ormModels {
		if err := conn.Model(model).
			CreateTable(&orm.CreateTableOptions{
				IfNotExists:   true,
				FKConstraints: true,
			}); err != nil {
			log.Fatal("Failed to create table", "error", err)
		}
	}

	queries := []string{
		"CREATE INDEX IF NOT EXISTS devices_display_name_idx ON devices USING BTREE (\"display_name\" ASC NULLS FIRST) ",
		"SELECT create_hypertable('device_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('device_histories', 'device_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('device_update_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT create_hypertable('device_status_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('device_status_histories', 'device_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('device_command_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('device_command_histories', 'device_id', number_partitions => 10, if_not_exists => true)",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'sensor_type_attributes' AND constraint_name = 'sensor_type_attributes_type_id_fk'\n    ) THEN\n        ALTER TABLE sensor_type_attributes ADD CONSTRAINT sensor_type_attributes_type_id_fk FOREIGN KEY (type_id) REFERENCES sensor_types (type_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'sensors' AND constraint_name = 'sensors_device_id_fk'\n    ) THEN\n        ALTER TABLE sensors ADD CONSTRAINT sensors_device_id_fk FOREIGN KEY (device_id) REFERENCES devices (device_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'sensors' AND constraint_name = 'sensors_sensor_type_fk'\n    ) THEN\n        ALTER TABLE sensors ADD CONSTRAINT sensors_sensor_type_fk FOREIGN KEY (sensor_type) REFERENCES sensor_types (type_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'sensor_limits' AND constraint_name = 'sensor_limits_device_id_fk'\n    ) THEN\n        ALTER TABLE sensor_limits ADD CONSTRAINT sensor_limits_device_id_fk FOREIGN KEY (device_id) REFERENCES devices (device_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'device_config_links' AND constraint_name = 'device_config_links_device_id_fkey'\n    ) THEN\n        ALTER TABLE device_config_links ADD CONSTRAINT device_config_links_device_id_fkey FOREIGN KEY (device_id) REFERENCES devices (device_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
	}

	for i, query := range queries {
		if _, err := conn.Exec(query); err != nil {
			log.Fatalf("Failed to exec[%d]: %s", i, err.Error())
		}
	}
}

// 생성된 테이블 삭제 함수
func deleteScheme() error {
	// DB 연결
	if _, err := pgorm.ConnectDB(); err != nil {
		return err
	}

	// DB Connection
	conn := pgorm.Conn()
	defer conn.Close()

	// 모델 제거
	for _, model := range ormModels {
		if err := conn.Model(model).DropTable(&orm.DropTableOptions{IfExists: true, Cascade: true}); err != nil {
			return err
		}
	}

	return nil
}
