- name: CONTAINERD CONFIG SETTING
  hosts: all
  gather_facts: no
  vars_files:
    - conf/env.yaml
  tasks:
    - name: check /etc/containerd/config.toml
      stat:
        path: /etc/containerd/config.toml
      register: file

    - name: back existed config
      command: mv /etc/containerd/config.toml /etc/containerd/config.toml_b
      when: file.stat.exists

    - name: Copy config
      copy:
        src: "{{ playbook_dir }}/conf/containerd.toml"
        dest: /etc/containerd/config.toml
        
    - name: containerd restart -> "systemctl restart containerd"
      command: systemctl restart containerd