- name: START REGISTRY POD
  hosts: registry
  gather_facts: no
  vars_files:
    - conf/env.yaml
  tasks:
    - name: registry start - deployment, service
      command: kubectl apply -f {{ playbook_dir }}/../registry/{{ item }}.yaml
      loop:
        - deployment.yaml
        - service.yaml