apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jfb-azurefile-default
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS   # Standard_LRS | Standard_GRS | Standard_ZRS ...
  # https://learn.microsoft.com/ko-kr/azure/aks/azure-csi-files-storage-provision#create-a-storage-class 참고
reclaimPolicy: Retain
volumeBindingMode: Immediate   # WaitForFirstConsumer | Immediate
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jfb-azuredisk-default
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer   # WaitForFirstConsumer | Immediate
allowVolumeExpansion: true