{{- range $index, $node := .Values.cluster }}
apiVersion: v1
kind: Pod
metadata:
  annotations:
    acryl.ai/appType: user
    {{- if $.Values.rdma.enabled }}
    k8s.v1.cni.cncf.io/networks: default/{{ $node.node_name }}
    {{- end }}
  labels:
    {{- range $key, $val := $.Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    role: "jfb-user-function"
    index: "{{ $index }}"
    device_type: {{ $node.device.type | default "" | quote }}
    device_model: {{ $node.device.model | default "" | quote }}
    device_count: {{ $node.device.count | default "" | quote }}
    device_ids: {{ $node.device.ids | default "" | quote }}
    node_name: {{ $node.node_name | default "" | quote }}
  name: {{ $.Values.pod_name }}-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  restartPolicy: Never
  hostname: {{ $.Values.spec.hostname }}
  {{- if $node.node_name }}
  nodeName: {{ $node.node_name }}
  {{- end }}
  {{- if $.Values.cpu_instance_name }}
  nodeSelector:
    jfb/cpu-instance.name: {{ $.Values.cpu_instance_name }}
  {{- end }}
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      cd /support && ./check_package_installed.sh
      {{- if ge $.Values.total_device_count 2 }}
      cp -ar /distributed ~; cd ~/distributed; ./init.sh;
      cd $JF_HOME
      {{- end }}
      {{- range $key, $val := $.Values.env }}
      echo "{{ $key }}={{ $val }}" >> /root/.deepspeed_env
      {{- end}}
      echo "POD_INDEX=$JF_POD_INDEX" >> /root/.deepspeed_env
      {{- if eq $index 0 }}
      (
      export_command=$(python3 /fine_tuning/uuid_to_index.py)
      # Check if the output contains 'export' and execute it
      echo $export_command
      if [[ $export_command == export* ]]; then
          eval $export_command
          echo "CUDA_VISIBLE_DEVICES updated: $CUDA_VISIBLE_DEVICES"
      else
          echo "Failed to update CUDA_VISIBLE_DEVICES."
      fi
      {{ $.Values.command }} --num_nodes=$JF_NUM_PODS --num_gpus=$JF_NUM_GPUS
      )
      {{- else }}
      while true; do sleep 30; done;
      {{- end }}

    env:
    {{- range $key, $val := $.Values.env }}
    - name: {{ $key }}
      value: {{ $val | quote }}
    {{- end}}
    {{- if and (eq $node.device.type "GPU") $node.device.uuids }}
    - name: "NVIDIA_VISIBLE_DEVICES"
      value: {{ $node.device.uuids }}
    {{- end }}
    - name: JF_NUM_GPUS
      value: {{ $node.device.count | default "" | quote }}
    - name: JF_NUM_PODS
      value: {{ len $.Values.cluster | quote }}
    - name: JF_POD_INDEX
      value: {{ $index | quote }}
    {{- if $.Values.rdma.enabled }}
    - name: "JF_RDMA_ENABLED"
      value: {{ $.Values.rdma.enabled | quote }}

    {{- if $.Values.rdma.mp.enabled }}
    - name: "JF_MP_ENABLED"
      value: "true"
    {{- if and $.Values.rdma.mp.seed_num $.Values.rdma.mp.seed_list }}
    {{- range $.Values.rdma.mp.seed_list }}
    {{- if eq .nodeName $node.node_name }}
    {{- if .seed }}
    - name: "JFB_MP_SEED_LIST"
      value: {{ .seed | quote }}
    - name: "JFB_MP_SEED_NUM"
      value: {{ $.Values.rdma.mp.seed_num | quote }} 
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if $.Values.rdma.p2p }}
    {{- range $.Values.rdma.p2p }}
    {{- if eq .nodeName $node.node_name }}
    - name: "JF_RDMA_IS_P2P"
      value: "true"
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }} # rdma    
    image: {{ $.Values.image }}
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - echo START
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            cd /fine_tuning; ./fine_tuning_stop.sh
    name:  "fine-tuning"
    resources:
      limits:
        cpu : {{ $.Values.resource.limits.cpu }}
        memory : {{ $.Values.resource.limits.memory }}
        {{- if $.Values.rdma.enabled }}
        rdma/jf_roce: 1
        {{- end }}
      requests:
        cpu : 0
        memory : {{ $.Values.resource.limits.memory }}
        {{- if $.Values.rdma.enabled }}
        rdma/jf_roce: 1
        {{- end }}
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        {{- if $.Values.rdma.enabled }}
        - NET_ADMIN
        {{- end }}
      privileged: false # TODO 기존과 같게 할건지 확인 필요
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - name: jf-data
      mountPath: /dataset/{{ $.Values.dataset.name }}
      subPath: "{{ $.Values.dataset.access }}/{{ $.Values.dataset.name }}"
      readOnly: true
    - name: jf-main
      mountPath: /tmp_model
      subPath: models/{{ $.Values.labels.model_name }}/tmp_model
    - name: jf-main
      mountPath: /tmp_config
      subPath: models/{{ $.Values.labels.model_name }}/tmp_config
    - name: jf-main
      mountPath: /logs
      subPath: models/{{ $.Values.labels.model_name }}/logs
    - name: jf-main
      mountPath: /model
      # subPath: models
      subPath: models/{{ $.Values.labels.model_name }}/latest_checkpoint
    - name: jf-main
      mountPath: /configurations
      subPath: models/{{ $.Values.labels.model_name }}/configurations
    - name: jf-bin
      mountPath: /fine_tuning
      subPath: fine_tuning
      readOnly: true
    - name: jf-bin
      mountPath: /support
      subPath: support
      readOnly: true
    {{- if ge $.Values.total_device_count 2 }}
      # 분산학습 프레임워크 적용 
    - name: jf-bin
      mountPath: /distributed
      subPath: distributed
      readOnly: true
    {{- end }}
    # - name: timezone
    #   mountPath: /etc/timezone
    #   subPath: timezone
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostIPC: true
  terminationGracePeriodSeconds: 0
  volumes:
  # - name: timezone
  #   configMap:
  #     name: timezone-config
  - name: jf-main
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-main-pvc
  - name: jf-data
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-data-pvc
  - name: jf-bin
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-bin-pvc
---
{{- end }}

