// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: configs.proto

package devices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceConfigs_SearchConfig_FullMethodName = "/devices.DeviceConfigs/SearchConfig"
	DeviceConfigs_CreateConfig_FullMethodName = "/devices.DeviceConfigs/CreateConfig"
	DeviceConfigs_ListDevice_FullMethodName   = "/devices.DeviceConfigs/ListDevice"
	DeviceConfigs_DeleteConfig_FullMethodName = "/devices.DeviceConfigs/DeleteConfig"
)

// DeviceConfigsClient is the client API for DeviceConfigs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceConfigsClient interface {
	// [TODO] 설정 조회
	SearchConfig(ctx context.Context, in *SearchConfigRequest, opts ...grpc.CallOption) (*SearchConfigResponse, error)
	// [TODO] 장치 설정 생성
	CreateConfig(ctx context.Context, in *DeviceConfig, opts ...grpc.CallOption) (*DeviceConfig, error)
	// [TODO] 설정이 적용된 장치 목록
	ListDevice(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// [TODO] 장치 설정 삭제
	//
	// 이 설정을 사용하는 장치가 있으면 삭제 불가
	DeleteConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deviceConfigsClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceConfigsClient(cc grpc.ClientConnInterface) DeviceConfigsClient {
	return &deviceConfigsClient{cc}
}

func (c *deviceConfigsClient) SearchConfig(ctx context.Context, in *SearchConfigRequest, opts ...grpc.CallOption) (*SearchConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchConfigResponse)
	err := c.cc.Invoke(ctx, DeviceConfigs_SearchConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigsClient) CreateConfig(ctx context.Context, in *DeviceConfig, opts ...grpc.CallOption) (*DeviceConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceConfig)
	err := c.cc.Invoke(ctx, DeviceConfigs_CreateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigsClient) ListDevice(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, DeviceConfigs_ListDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceConfigsClient) DeleteConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceConfigs_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceConfigsServer is the server API for DeviceConfigs service.
// All implementations must embed UnimplementedDeviceConfigsServer
// for forward compatibility.
type DeviceConfigsServer interface {
	// [TODO] 설정 조회
	SearchConfig(context.Context, *SearchConfigRequest) (*SearchConfigResponse, error)
	// [TODO] 장치 설정 생성
	CreateConfig(context.Context, *DeviceConfig) (*DeviceConfig, error)
	// [TODO] 설정이 적용된 장치 목록
	ListDevice(context.Context, *SearchRequest) (*SearchResponse, error)
	// [TODO] 장치 설정 삭제
	//
	// 이 설정을 사용하는 장치가 있으면 삭제 불가
	DeleteConfig(context.Context, *ConfigRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDeviceConfigsServer()
}

// UnimplementedDeviceConfigsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceConfigsServer struct{}

func (UnimplementedDeviceConfigsServer) SearchConfig(context.Context, *SearchConfigRequest) (*SearchConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchConfig not implemented")
}
func (UnimplementedDeviceConfigsServer) CreateConfig(context.Context, *DeviceConfig) (*DeviceConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedDeviceConfigsServer) ListDevice(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevice not implemented")
}
func (UnimplementedDeviceConfigsServer) DeleteConfig(context.Context, *ConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedDeviceConfigsServer) mustEmbedUnimplementedDeviceConfigsServer() {}
func (UnimplementedDeviceConfigsServer) testEmbeddedByValue()                       {}

// UnsafeDeviceConfigsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceConfigsServer will
// result in compilation errors.
type UnsafeDeviceConfigsServer interface {
	mustEmbedUnimplementedDeviceConfigsServer()
}

func RegisterDeviceConfigsServer(s grpc.ServiceRegistrar, srv DeviceConfigsServer) {
	// If the following call panics, it indicates UnimplementedDeviceConfigsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceConfigs_ServiceDesc, srv)
}

func _DeviceConfigs_SearchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigsServer).SearchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigs_SearchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigsServer).SearchConfig(ctx, req.(*SearchConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigs_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigsServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigs_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigsServer).CreateConfig(ctx, req.(*DeviceConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigs_ListDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigsServer).ListDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigs_ListDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigsServer).ListDevice(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceConfigs_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfigsServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceConfigs_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfigsServer).DeleteConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceConfigs_ServiceDesc is the grpc.ServiceDesc for DeviceConfigs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceConfigs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devices.DeviceConfigs",
	HandlerType: (*DeviceConfigsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchConfig",
			Handler:    _DeviceConfigs_SearchConfig_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _DeviceConfigs_CreateConfig_Handler,
		},
		{
			MethodName: "ListDevice",
			Handler:    _DeviceConfigs_ListDevice_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _DeviceConfigs_DeleteConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configs.proto",
}
