// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: devices.proto

package devices

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "gitlab.suredatalab.kr/beymons/common"
	_ "gitlab.suredatalab.kr/sdlmicro/middleware/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 사용 가능한 속성
type Attribute int32

const (
	// 장치 이름
	Attribute_display_name Attribute = 0
	// 장치 설명
	Attribute_description Attribute = 1
	// 센서 정보
	Attribute_sensors Attribute = 2
	// 설치 위치
	Attribute_location Attribute = 3
	// 생성 일시
	Attribute_created_at Attribute = 4
	// 생성한 사용자 정보
	Attribute_created_by Attribute = 5
	// 마지막으로 수정된 일시
	Attribute_updated_at Attribute = 6
	// 마지막으로 수정한 사용자 정보
	Attribute_updated_by Attribute = 7
	// 고객 정보
	Attribute_site Attribute = 8
)

// Enum value maps for Attribute.
var (
	Attribute_name = map[int32]string{
		0: "display_name",
		1: "description",
		2: "sensors",
		3: "location",
		4: "created_at",
		5: "created_by",
		6: "updated_at",
		7: "updated_by",
		8: "site",
	}
	Attribute_value = map[string]int32{
		"display_name": 0,
		"description":  1,
		"sensors":      2,
		"location":     3,
		"created_at":   4,
		"created_by":   5,
		"updated_at":   6,
		"updated_by":   7,
		"site":         8,
	}
)

func (x Attribute) Enum() *Attribute {
	p := new(Attribute)
	*p = x
	return p
}

func (x Attribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Attribute) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[0].Descriptor()
}

func (Attribute) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[0]
}

func (x Attribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Attribute.Descriptor instead.
func (Attribute) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{0}
}

// TODO: repeater 관련 Flag 설정 참조해서 수정
type DeviceRole int32

const (
	DeviceRole_GATEWAY     DeviceRole = 0
	DeviceRole_NODE        DeviceRole = 1
	DeviceRole_REPEATER    DeviceRole = 2
	DeviceRole_NODEGATEWAY DeviceRole = 3
)

// Enum value maps for DeviceRole.
var (
	DeviceRole_name = map[int32]string{
		0: "GATEWAY",
		1: "NODE",
		2: "REPEATER",
		3: "NODEGATEWAY",
	}
	DeviceRole_value = map[string]int32{
		"GATEWAY":     0,
		"NODE":        1,
		"REPEATER":    2,
		"NODEGATEWAY": 3,
	}
)

func (x DeviceRole) Enum() *DeviceRole {
	p := new(DeviceRole)
	*p = x
	return p
}

func (x DeviceRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceRole) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[1].Descriptor()
}

func (DeviceRole) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[1]
}

func (x DeviceRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceRole.Descriptor instead.
func (DeviceRole) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{1}
}

type DeviceStatus int32

const (
	// 정상 상태
	DeviceStatus_NORMAL DeviceStatus = 0
	// 장치 혹은 센서의 고장 상태
	DeviceStatus_TROUBLE DeviceStatus = 1
	// 폐기
	DeviceStatus_DISCARD DeviceStatus = 2
	// 데이터 미수신 상태
	DeviceStatus_NOT_RECEIVED DeviceStatus = 3
	// 주의
	DeviceStatus_CAUTION DeviceStatus = 4
	// 경고
	DeviceStatus_WARNING DeviceStatus = 5
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "NORMAL",
		1: "TROUBLE",
		2: "DISCARD",
		3: "NOT_RECEIVED",
		4: "CAUTION",
		5: "WARNING",
	}
	DeviceStatus_value = map[string]int32{
		"NORMAL":       0,
		"TROUBLE":      1,
		"DISCARD":      2,
		"NOT_RECEIVED": 3,
		"CAUTION":      4,
		"WARNING":      5,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[2].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[2]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{2}
}

// 정렬
type SearchRequest_Order int32

const (
	// 장치 ID 오름차순
	SearchRequest_device_id_asc SearchRequest_Order = 0
	// 장치 ID 내림차순
	SearchRequest_device_id_desc SearchRequest_Order = 1
	// 동작방식 오름차순
	SearchRequest_device_role_asc SearchRequest_Order = 2
	// 동작방식 내림차순
	SearchRequest_device_role_desc SearchRequest_Order = 3
	// 현장 ID 오름차순
	SearchRequest_site_id_asc SearchRequest_Order = 4
	// 현장 ID 내림차순
	SearchRequest_site_id_desc SearchRequest_Order = 5
	// 현장명 오름차순
	SearchRequest_site_name_asc SearchRequest_Order = 6
	// 현장명 내림차순
	SearchRequest_site_name_desc SearchRequest_Order = 7
)

// Enum value maps for SearchRequest_Order.
var (
	SearchRequest_Order_name = map[int32]string{
		0: "device_id_asc",
		1: "device_id_desc",
		2: "device_role_asc",
		3: "device_role_desc",
		4: "site_id_asc",
		5: "site_id_desc",
		6: "site_name_asc",
		7: "site_name_desc",
	}
	SearchRequest_Order_value = map[string]int32{
		"device_id_asc":    0,
		"device_id_desc":   1,
		"device_role_asc":  2,
		"device_role_desc": 3,
		"site_id_asc":      4,
		"site_id_desc":     5,
		"site_name_asc":    6,
		"site_name_desc":   7,
	}
)

func (x SearchRequest_Order) Enum() *SearchRequest_Order {
	p := new(SearchRequest_Order)
	*p = x
	return p
}

func (x SearchRequest_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequest_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[3].Descriptor()
}

func (SearchRequest_Order) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[3]
}

func (x SearchRequest_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchRequest_Order.Descriptor instead.
func (SearchRequest_Order) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{2, 0}
}

// 관리 이력 코드
type DeviceHistory_Kind int32

const (
	// 생성
	DeviceHistory_CREATE DeviceHistory_Kind = 0
	// 정보 변경
	DeviceHistory_UPDATE DeviceHistory_Kind = 1
	// 삭제
	DeviceHistory_DELETE DeviceHistory_Kind = 2
	// 장치 상태
	DeviceHistory_STATUS DeviceHistory_Kind = 3
	// 명령 전송
	DeviceHistory_COMMAND DeviceHistory_Kind = 4
	// 장치 및 센서 연결
	DeviceHistory_ATTACH DeviceHistory_Kind = 5
	// 장치 및 센서 해제
	DeviceHistory_DETACH DeviceHistory_Kind = 6
	// 장치 설치
	DeviceHistory_INSTALL DeviceHistory_Kind = 7
	// 장치 해제
	DeviceHistory_UNINSTALL DeviceHistory_Kind = 8
)

// Enum value maps for DeviceHistory_Kind.
var (
	DeviceHistory_Kind_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "STATUS",
		4: "COMMAND",
		5: "ATTACH",
		6: "DETACH",
		7: "INSTALL",
		8: "UNINSTALL",
	}
	DeviceHistory_Kind_value = map[string]int32{
		"CREATE":    0,
		"UPDATE":    1,
		"DELETE":    2,
		"STATUS":    3,
		"COMMAND":   4,
		"ATTACH":    5,
		"DETACH":    6,
		"INSTALL":   7,
		"UNINSTALL": 8,
	}
)

func (x DeviceHistory_Kind) Enum() *DeviceHistory_Kind {
	p := new(DeviceHistory_Kind)
	*p = x
	return p
}

func (x DeviceHistory_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceHistory_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[4].Descriptor()
}

func (DeviceHistory_Kind) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[4]
}

func (x DeviceHistory_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceHistory_Kind.Descriptor instead.
func (DeviceHistory_Kind) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{14, 0}
}

type DeviceCommandHistory_Direction int32

const (
	DeviceCommandHistory_upstream   DeviceCommandHistory_Direction = 0
	DeviceCommandHistory_downstream DeviceCommandHistory_Direction = 1
)

// Enum value maps for DeviceCommandHistory_Direction.
var (
	DeviceCommandHistory_Direction_name = map[int32]string{
		0: "upstream",
		1: "downstream",
	}
	DeviceCommandHistory_Direction_value = map[string]int32{
		"upstream":   0,
		"downstream": 1,
	}
)

func (x DeviceCommandHistory_Direction) Enum() *DeviceCommandHistory_Direction {
	p := new(DeviceCommandHistory_Direction)
	*p = x
	return p
}

func (x DeviceCommandHistory_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCommandHistory_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[5].Descriptor()
}

func (DeviceCommandHistory_Direction) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[5]
}

func (x DeviceCommandHistory_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCommandHistory_Direction.Descriptor instead.
func (DeviceCommandHistory_Direction) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{18, 0}
}

type DeviceCommandHistory_Status int32

const (
	// 처리 중
	DeviceCommandHistory_PROCESSING DeviceCommandHistory_Status = 0
	// 성공
	DeviceCommandHistory_SUCCESS DeviceCommandHistory_Status = 1
	// 실패
	DeviceCommandHistory_FALLURE DeviceCommandHistory_Status = 2
	// 타임아웃
	DeviceCommandHistory_TIMEOUT DeviceCommandHistory_Status = 3
	// 정의되지 않은 명령
	DeviceCommandHistory_UNKNOWN DeviceCommandHistory_Status = 4
)

// Enum value maps for DeviceCommandHistory_Status.
var (
	DeviceCommandHistory_Status_name = map[int32]string{
		0: "PROCESSING",
		1: "SUCCESS",
		2: "FALLURE",
		3: "TIMEOUT",
		4: "UNKNOWN",
	}
	DeviceCommandHistory_Status_value = map[string]int32{
		"PROCESSING": 0,
		"SUCCESS":    1,
		"FALLURE":    2,
		"TIMEOUT":    3,
		"UNKNOWN":    4,
	}
)

func (x DeviceCommandHistory_Status) Enum() *DeviceCommandHistory_Status {
	p := new(DeviceCommandHistory_Status)
	*p = x
	return p
}

func (x DeviceCommandHistory_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCommandHistory_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_devices_proto_enumTypes[6].Descriptor()
}

func (DeviceCommandHistory_Status) Type() protoreflect.EnumType {
	return &file_devices_proto_enumTypes[6]
}

func (x DeviceCommandHistory_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCommandHistory_Status.Descriptor instead.
func (DeviceCommandHistory_Status) EnumDescriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{18, 1}
}

type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Device *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// 마지막으로 적용된 설정 값
	Params *structpb.Struct `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// 관련 링크 (HATEOAS)
	Link map[string]string `protobuf:"bytes,3,rep,name=link,proto3" json:"link,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 관련 장치
	//
	// - DEPRECATED: 하위 장치
	// - TODO: 이 장치롤 통해 데이터를 전송한 장치
	Related       []*Device `protobuf:"bytes,4,rep,name=related,proto3" json:"related,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
	mi := &file_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResponse.ProtoReflect.Descriptor instead.
func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceResponse) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DeviceResponse) GetLink() map[string]string {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *DeviceResponse) GetRelated() []*Device {
	if x != nil {
		return x.Related
	}
	return nil
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Order []SearchRequest_Order  `protobuf:"varint,1,rep,packed,name=order,proto3,enum=devices.SearchRequest_Order" json:"order,omitempty"`
	// 조회 필드 선택 (default: ALL)
	Field []Attribute `protobuf:"varint,2,rep,packed,name=field,proto3,enum=devices.Attribute" json:"field,omitempty"`
	// 응답으로 보내줄 레코드 수.
	// 지정하지 않거나 0인 경우 전체 레코드를 조회하지만,
	// 응답이 15초 이상 소요되는 경우 타임아웃 오류가 발생된다.
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// 페이지에서 표시되는 첫 레코드의 인덱스 (Default: 0)
	Offset uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// 전체 검색
	//
	// 대상:
	// - 장치 ID (전방일치)
	// - 장치명
	// - 장치 설명
	// - 현장 ID (전방일치)
	// - 현장명
	// - 설비명
	Search string `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	// TODO: Config ID로 필터링
	ConfigId string `protobuf:"bytes,6,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	// 장치 ID로 필터링
	DeviceId string `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// 현장 ID로 필터링
	SiteId string `protobuf:"bytes,8,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// 설비 ID로 필터링
	FacilityId string `protobuf:"bytes,9,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	// 센서 타입으로 필터링
	SensorType []string `protobuf:"bytes,10,rep,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	// 장치 종류로 필터링
	Role []DeviceRole `protobuf:"varint,11,rep,packed,name=role,proto3,enum=devices.DeviceRole" json:"role,omitempty"`
	// 장치 상태로 필터링
	Status        []DeviceStatus `protobuf:"varint,12,rep,packed,name=status,proto3,enum=devices.DeviceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetOrder() []SearchRequest_Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SearchRequest) GetField() []Attribute {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *SearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *SearchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SearchRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SearchRequest) GetFacilityId() string {
	if x != nil {
		return x.FacilityId
	}
	return ""
}

func (x *SearchRequest) GetSensorType() []string {
	if x != nil {
		return x.SensorType
	}
	return nil
}

func (x *SearchRequest) GetRole() []DeviceRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *SearchRequest) GetStatus() []DeviceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type SearchResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entities []*Device              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// 전체 데이터 수
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 관련 링크 (HATEOAS)
	Link          map[string]string `protobuf:"bytes,3,rep,name=link,proto3" json:"link,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetEntities() []*Device {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchResponse) GetLink() map[string]string {
	if x != nil {
		return x.Link
	}
	return nil
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histories     []*DeviceHistory       `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryResponse) GetHistories() []*DeviceHistory {
	if x != nil {
		return x.Histories
	}
	return nil
}

type ChildDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Children      []string               `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildDeviceRequest) Reset() {
	*x = ChildDeviceRequest{}
	mi := &file_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildDeviceRequest) ProtoMessage() {}

func (x *ChildDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildDeviceRequest.ProtoReflect.Descriptor instead.
func (*ChildDeviceRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{5}
}

func (x *ChildDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ChildDeviceRequest) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

type DeleteSensorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Sensor ID
	SensorId      string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSensorRequest) Reset() {
	*x = DeleteSensorRequest{}
	mi := &file_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSensorRequest) ProtoMessage() {}

func (x *DeleteSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSensorRequest.ProtoReflect.Descriptor instead.
func (*DeleteSensorRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSensorRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeleteSensorRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type GetLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Modbus address(구: Channel ID)
	Channel       uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitRequest) Reset() {
	*x = GetLimitRequest{}
	mi := &file_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitRequest) ProtoMessage() {}

func (x *GetLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitRequest.ProtoReflect.Descriptor instead.
func (*GetLimitRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{7}
}

func (x *GetLimitRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetLimitRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type GetLimitResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Limits        map[string]*SensorLimit `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitResponse) Reset() {
	*x = GetLimitResponse{}
	mi := &file_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitResponse) ProtoMessage() {}

func (x *GetLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitResponse.ProtoReflect.Descriptor instead.
func (*GetLimitResponse) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{8}
}

func (x *GetLimitResponse) GetLimits() map[string]*SensorLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

type SetLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Modbus address(구: Channel ID)
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Attribute
	Attribute string `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// 정상 범위 하한값
	NormalMin float64 `protobuf:"fixed64,4,opt,name=normal_min,json=normalMin,proto3" json:"normal_min,omitempty"`
	// 정상 범위 상한값
	NormalMax float64 `protobuf:"fixed64,5,opt,name=normal_max,json=normalMax,proto3" json:"normal_max,omitempty"`
	// 주의 범위 하한값
	CautionMin float64 `protobuf:"fixed64,6,opt,name=caution_min,json=cautionMin,proto3" json:"caution_min,omitempty"`
	// 주의 범위 상한값
	CautionMax    float64 `protobuf:"fixed64,7,opt,name=caution_max,json=cautionMax,proto3" json:"caution_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLimitRequest) Reset() {
	*x = SetLimitRequest{}
	mi := &file_devices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimitRequest) ProtoMessage() {}

func (x *SetLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimitRequest.ProtoReflect.Descriptor instead.
func (*SetLimitRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{9}
}

func (x *SetLimitRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetLimitRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SetLimitRequest) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *SetLimitRequest) GetNormalMin() float64 {
	if x != nil {
		return x.NormalMin
	}
	return 0
}

func (x *SetLimitRequest) GetNormalMax() float64 {
	if x != nil {
		return x.NormalMax
	}
	return 0
}

func (x *SetLimitRequest) GetCautionMin() float64 {
	if x != nil {
		return x.CautionMin
	}
	return 0
}

func (x *SetLimitRequest) GetCautionMax() float64 {
	if x != nil {
		return x.CautionMax
	}
	return 0
}

type DeleteLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Modbus address(구: Channel ID)
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Attribute
	Attribute     string `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLimitRequest) Reset() {
	*x = DeleteLimitRequest{}
	mi := &file_devices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLimitRequest) ProtoMessage() {}

func (x *DeleteLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLimitRequest.ProtoReflect.Descriptor instead.
func (*DeleteLimitRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLimitRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeleteLimitRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DeleteLimitRequest) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type GetCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId      string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Sequence      uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequest) Reset() {
	*x = GetCommandRequest{}
	mi := &file_devices_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequest) ProtoMessage() {}

func (x *GetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequest) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{11}
}

func (x *GetCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetCommandRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Device
//
// BEYMONS 장치에 대한 메타데이터 관리
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// device 이름
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" pg:",type:varchar(100)"`
	// device 설명
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" pg:",type:varchar(1000)"`
	// device 동작 모드 [변경 불가]
	DeviceRole DeviceRole `protobuf:"varint,4,opt,name=device_role,json=deviceRole,proto3,enum=devices.DeviceRole" json:"device_role,omitempty" pg:",type:varchar(16),use_zero,notnull"`
	// device 상태
	Status DeviceStatus `protobuf:"varint,5,opt,name=status,proto3,enum=devices.DeviceStatus" json:"status,omitempty" pg:",type:varchar(16),notnull,use_zero"`
	// 연결된 센서 목록 [변경 불가]
	Sensors []*Sensor `protobuf:"bytes,6,rep,name=sensors,proto3" json:"sensors,omitempty" pg:",rel:has-many"`
	// 등록 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:"-"`
	// 등록한 사용자 정보
	CreatedBy *structpb.Struct `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty" pg:"-"`
	// 마지막 변경 일시
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" pg:"-"`
	// 마지막으로 변경한 사용자 정보
	UpdatedBy *structpb.Struct `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty" pg:"-"`
	// 장치가 설치된 위치
	Location *common.Location `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty" pg:"-"`
	Site     *Device_Site     `protobuf:"bytes,12,opt,name=site,proto3" json:"site,omitempty" pg:"-"`
	// 리소스에 대한 변경 권한 여부
	Writable      bool `protobuf:"varint,14,opt,name=writable,proto3" json:"writable,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_devices_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{12}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Device) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Device) GetDeviceRole() DeviceRole {
	if x != nil {
		return x.DeviceRole
	}
	return DeviceRole_GATEWAY
}

func (x *Device) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_NORMAL
}

func (x *Device) GetSensors() []*Sensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetCreatedBy() *structpb.Struct {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Device) GetUpdatedBy() *structpb.Struct {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *Device) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Device) GetSite() *Device_Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Device) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

// DeviceRelation
//
// DEPRECATED: 장치 간의 연결 정보를 관리한다.
type DeviceRelation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent
	ParentId string  `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty" pg:",type:varchar(14),pk,notnull,join_fk:device_id,on_delete:CASCADE"`
	Parent   *Device `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty" pg:",rel:has-one,fk:parent_id"`
	// Child
	ChildId string  `protobuf:"bytes,2,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty" pg:",type:varchar(14),pk,notnull,join_fk:device_id,on_delete:CASCADE"`
	Child   *Device `protobuf:"bytes,6,opt,name=child,proto3" json:"child,omitempty" pg:",rel:has-one,fk:child_id"`
	// 장치 연결 일시
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRelation) Reset() {
	*x = DeviceRelation{}
	mi := &file_devices_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRelation) ProtoMessage() {}

func (x *DeviceRelation) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRelation.ProtoReflect.Descriptor instead.
func (*DeviceRelation) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceRelation) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DeviceRelation) GetParent() *Device {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *DeviceRelation) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *DeviceRelation) GetChild() *Device {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *DeviceRelation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// DeviceHistory
//
// 장치에 대한 이력 관리
type DeviceHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 이력 발생 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// Device ID
	DeviceId string             `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),notnull"`
	Action   DeviceHistory_Kind `protobuf:"varint,3,opt,name=action,proto3,enum=devices.DeviceHistory_Kind" json:"action,omitempty" pg:",type:varchar(10),notnull,use_zero"`
	// 이력을 발생시킨 사용자 ID
	CreatedUserId string `protobuf:"bytes,4,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty" pg:",type:varchar(36),notnull"`
	// 이력 발생 당시의 사용자 이름
	CreatedName string `protobuf:"bytes,5,opt,name=created_name,json=createdName,proto3" json:"created_name,omitempty" pg:",type:varchar(200),notnull,default:'Anonymous'"`
	// 이력을 발생시킨 사용자 정보
	CreatedBy *structpb.Struct `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty" pg:"-"`
	// 상세 이력
	//
	// 관리 이력 코드에 따라 값의 형태가 달라지며
	// ATTACH, DETACH, INSTALL, UNINSTALL 코드는 UPDATE와 동일한 구조를 사용한다.
	//
	// Example:
	// - STATUS: {"channel": 0, "status": "상태"}
	// - UPDATE: {"속성명": {"origin": "기존 값", "change": "변경된 값"}}
	// - ATTACH | DETACH: {"sensors": ["Sensor ID"]}
	// - ATTACH | DETACH: {"parent": ["Device ID"]}
	// - ATTACH | DETACH: {"children": ["Device ID"]}
	// - INSTALL | UNINSTALL: {"sites": ["Site ID"]}
	// - INSTALL | UNINSTALL: {"facilities": ["Facility ID"]}
	// - COMMAND: {}
	Details       *structpb.Struct `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHistory) Reset() {
	*x = DeviceHistory{}
	mi := &file_devices_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHistory) ProtoMessage() {}

func (x *DeviceHistory) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHistory.ProtoReflect.Descriptor instead.
func (*DeviceHistory) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHistory) GetAction() DeviceHistory_Kind {
	if x != nil {
		return x.Action
	}
	return DeviceHistory_CREATE
}

func (x *DeviceHistory) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *DeviceHistory) GetCreatedName() string {
	if x != nil {
		return x.CreatedName
	}
	return ""
}

func (x *DeviceHistory) GetCreatedBy() *structpb.Struct {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *DeviceHistory) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// DeviceUpdateHistory
//
// Device 모델의 변경 이력 관리
type DeviceUpdateHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 이력 발생 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// Device ID
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),notnull"`
	// 변경된 속성명
	Attribute string `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty" pg:",type:varchar(50),notnull"`
	// 기존 값
	Origin string `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty" pg:",type:varchar(4000)"`
	// 변경된 값
	Change        string `protobuf:"bytes,5,opt,name=change,proto3" json:"change,omitempty" pg:",type:varchar(4000)"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceUpdateHistory) Reset() {
	*x = DeviceUpdateHistory{}
	mi := &file_devices_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUpdateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUpdateHistory) ProtoMessage() {}

func (x *DeviceUpdateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUpdateHistory.ProtoReflect.Descriptor instead.
func (*DeviceUpdateHistory) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceUpdateHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceUpdateHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceUpdateHistory) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *DeviceUpdateHistory) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *DeviceUpdateHistory) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

// DeviceStatusHistory
//
// 장치 상태 변경 이력
type DeviceStatusHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 이력 발생 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// Device ID
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),notnull"`
	// 연결된 모드버스(구: 채널). 0(NULL)이 아닌 경우 센서의 상태
	Channel uint32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// 장치 상태
	Status DeviceStatus `protobuf:"varint,4,opt,name=status,proto3,enum=devices.DeviceStatus" json:"status,omitempty" pg:",type:varchar(16),notnull,use_zero"`
	// 설명
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" pg:",type:varchar(1000)"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusHistory) Reset() {
	*x = DeviceStatusHistory{}
	mi := &file_devices_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusHistory) ProtoMessage() {}

func (x *DeviceStatusHistory) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusHistory.ProtoReflect.Descriptor instead.
func (*DeviceStatusHistory) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceStatusHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceStatusHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatusHistory) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DeviceStatusHistory) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_NORMAL
}

func (x *DeviceStatusHistory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Sensor
//
// 장치에 연결된 센서 정보 관리
type Sensor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sensor ID
	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty" pg:",type:uuid,pk,default:gen_random_uuid()"`
	// Device ID
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),notnull,unique:device_channel_id"`
	// Modbus address (구: Channel ID)
	ChannelId uint32 `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty" pg:",type:smallint,notnull,use_zero,unique:device_channel_id"`
	// 센서 타입
	SensorType string `protobuf:"bytes,4,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty" pg:",type:varchar(16),notnull"`
	// 센서 이름
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" pg:",type:varchar(100)"`
	// 센서 설명
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty" pg:",type:varchar(1000)"`
	// 최근 수집한 데이터. 장치 조회 API에서만 포함
	Latest *structpb.Struct `protobuf:"bytes,7,opt,name=latest,proto3" json:"latest,omitempty" pg:"-"`
	// 채널(구: 프로프) 개수
	Probes uint32 `protobuf:"varint,8,opt,name=probes,proto3" json:"probes,omitempty" pg:",type:smallint"`
	// 센서 상태
	Status        DeviceStatus     `protobuf:"varint,9,opt,name=status,proto3,enum=devices.DeviceStatus" json:"status,omitempty" pg:",type:varchar(16),notnull,use_zero"`
	Facility      *Sensor_Facility `protobuf:"bytes,10,opt,name=facility,proto3" json:"facility,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sensor) Reset() {
	*x = Sensor{}
	mi := &file_devices_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sensor) ProtoMessage() {}

func (x *Sensor) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sensor.ProtoReflect.Descriptor instead.
func (*Sensor) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{17}
}

func (x *Sensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Sensor) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Sensor) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Sensor) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *Sensor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Sensor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Sensor) GetLatest() *structpb.Struct {
	if x != nil {
		return x.Latest
	}
	return nil
}

func (x *Sensor) GetProbes() uint32 {
	if x != nil {
		return x.Probes
	}
	return 0
}

func (x *Sensor) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_NORMAL
}

func (x *Sensor) GetFacility() *Sensor_Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

// DeviceCommandHistory
//
// 서버와 장치간 요청된 명령에 대한 이력을 관리한다.
type DeviceCommandHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 명령이 수신된 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// Gateway ID
	DeviceId  string                         `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),notnull"`
	Direction DeviceCommandHistory_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=devices.DeviceCommandHistory_Direction" json:"direction,omitempty" pg:",type:varchar(10),use_zero,notnull"`
	Command   string                         `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty" pg:",type:varchar(30),notnull"`
	// Sequence
	Sequence uint64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty" pg:",notnull,use_zero"`
	// Operand
	Payload string                      `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty" pg:",type:jsonb,json_use_number,notnull"`
	Status  DeviceCommandHistory_Status `protobuf:"varint,7,opt,name=status,proto3,enum=devices.DeviceCommandHistory_Status" json:"status,omitempty" pg:",type:varchar(10),use_zero,notnull"`
	// 응답 시간
	RespondedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty" pg:",type:timestamptz"`
	// 응답 내용
	Response      string `protobuf:"bytes,9,opt,name=response,proto3" json:"response,omitempty" pg:",type:jsonb,json_use_number"`
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommandHistory) Reset() {
	*x = DeviceCommandHistory{}
	mi := &file_devices_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommandHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommandHistory) ProtoMessage() {}

func (x *DeviceCommandHistory) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommandHistory.ProtoReflect.Descriptor instead.
func (*DeviceCommandHistory) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceCommandHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceCommandHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCommandHistory) GetDirection() DeviceCommandHistory_Direction {
	if x != nil {
		return x.Direction
	}
	return DeviceCommandHistory_upstream
}

func (x *DeviceCommandHistory) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DeviceCommandHistory) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeviceCommandHistory) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *DeviceCommandHistory) GetStatus() DeviceCommandHistory_Status {
	if x != nil {
		return x.Status
	}
	return DeviceCommandHistory_PROCESSING
}

func (x *DeviceCommandHistory) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

func (x *DeviceCommandHistory) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *DeviceCommandHistory) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SensorLimit
//
// 센서로부터 수집된 데이터에 대한 임계치를 관리한다.
type SensorLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// Modbus address(구: Channel ID)
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty" pg:",pk,notnull"`
	// 데이터 속성명
	Attribute string `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty" pg:",type:varchar(50),pk,notnull"`
	// 정상 범위 하한값
	NormalMin float64 `protobuf:"fixed64,4,opt,name=normal_min,json=normalMin,proto3" json:"normal_min,omitempty" pg:",use_zero,notnull"`
	// 정상 범위 상한값
	NormalMax float64 `protobuf:"fixed64,5,opt,name=normal_max,json=normalMax,proto3" json:"normal_max,omitempty" pg:",use_zero,notnull"`
	// 주의 범위 하한값
	CautionMin float64 `protobuf:"fixed64,6,opt,name=caution_min,json=cautionMin,proto3" json:"caution_min,omitempty" pg:",use_zero,notnull"`
	// 주의 범위 상한값
	CautionMax float64 `protobuf:"fixed64,7,opt,name=caution_max,json=cautionMax,proto3" json:"caution_max,omitempty" pg:",use_zero,notnull"`
	// 설정 시간
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorLimit) Reset() {
	*x = SensorLimit{}
	mi := &file_devices_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorLimit) ProtoMessage() {}

func (x *SensorLimit) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorLimit.ProtoReflect.Descriptor instead.
func (*SensorLimit) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{19}
}

func (x *SensorLimit) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorLimit) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SensorLimit) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *SensorLimit) GetNormalMin() float64 {
	if x != nil {
		return x.NormalMin
	}
	return 0
}

func (x *SensorLimit) GetNormalMax() float64 {
	if x != nil {
		return x.NormalMax
	}
	return 0
}

func (x *SensorLimit) GetCautionMin() float64 {
	if x != nil {
		return x.CautionMin
	}
	return 0
}

func (x *SensorLimit) GetCautionMax() float64 {
	if x != nil {
		return x.CautionMax
	}
	return 0
}

func (x *SensorLimit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 장치가 연결된 사이트 정보
type Device_Site struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 고객 ID
	SiteId string `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// 고객 이름
	SiteName      string `protobuf:"bytes,2,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device_Site) Reset() {
	*x = Device_Site{}
	mi := &file_devices_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device_Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_Site) ProtoMessage() {}

func (x *Device_Site) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_Site.ProtoReflect.Descriptor instead.
func (*Device_Site) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{12, 0}
}

func (x *Device_Site) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Device_Site) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

// 장치가 설비 정보
type Sensor_Facility struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 설비 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 설비 이름
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sensor_Facility) Reset() {
	*x = Sensor_Facility{}
	mi := &file_devices_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sensor_Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sensor_Facility) ProtoMessage() {}

func (x *Sensor_Facility) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sensor_Facility.ProtoReflect.Descriptor instead.
func (*Sensor_Facility) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{17, 0}
}

func (x *Sensor_Facility) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sensor_Facility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_devices_proto protoreflect.FileDescriptor

const file_devices_proto_rawDesc = "" +
	"\n" +
	"\rdevices.proto\x12\adevices\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a%sdlmicro/middleware/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1abeymons/common/types.proto\x1a\rcommand.proto\"1\n" +
	"\rDeviceRequest\x12 \n" +
	"\tdevice_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bdeviceId\"\x85\x02\n" +
	"\x0eDeviceResponse\x12'\n" +
	"\x06device\x18\x01 \x01(\v2\x0f.devices.DeviceR\x06device\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x125\n" +
	"\x04link\x18\x03 \x03(\v2!.devices.DeviceResponse.LinkEntryR\x04link\x12)\n" +
	"\arelated\x18\x04 \x03(\v2\x0f.devices.DeviceR\arelated\x1a7\n" +
	"\tLinkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x05\n" +
	"\rSearchRequest\x127\n" +
	"\x05order\x18\x01 \x03(\x0e2\x1c.devices.SearchRequest.OrderB\x03\xe0A\x01R\x05order\x12-\n" +
	"\x05field\x18\x02 \x03(\x0e2\x12.devices.AttributeB\x03\xe0A\x01R\x05field\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x04B\x03\xe0A\x01R\x05limit\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x04B\x03\xe0A\x01R\x06offset\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tB\x03\xe0A\x01R\x06search\x12 \n" +
	"\tconfig_id\x18\x06 \x01(\tB\x03\xe0A\x01R\bconfigId\x12 \n" +
	"\tdevice_id\x18\a \x01(\tB\x03\xe0A\x01R\bdeviceId\x12\x1c\n" +
	"\asite_id\x18\b \x01(\tB\x03\xe0A\x01R\x06siteId\x12$\n" +
	"\vfacility_id\x18\t \x01(\tB\x03\xe0A\x01R\n" +
	"facilityId\x12$\n" +
	"\vsensor_type\x18\n" +
	" \x03(\tB\x03\xe0A\x01R\n" +
	"sensorType\x12,\n" +
	"\x04role\x18\v \x03(\x0e2\x13.devices.DeviceRoleB\x03\xe0A\x01R\x04role\x122\n" +
	"\x06status\x18\f \x03(\x0e2\x15.devices.DeviceStatusB\x03\xe0A\x01R\x06status\"\xa3\x01\n" +
	"\x05Order\x12\x11\n" +
	"\rdevice_id_asc\x10\x00\x12\x12\n" +
	"\x0edevice_id_desc\x10\x01\x12\x13\n" +
	"\x0fdevice_role_asc\x10\x02\x12\x14\n" +
	"\x10device_role_desc\x10\x03\x12\x0f\n" +
	"\vsite_id_asc\x10\x04\x12\x10\n" +
	"\fsite_id_desc\x10\x05\x12\x11\n" +
	"\rsite_name_asc\x10\x06\x12\x12\n" +
	"\x0esite_name_desc\x10\a\"\xc3\x01\n" +
	"\x0eSearchResponse\x12+\n" +
	"\bentities\x18\x01 \x03(\v2\x0f.devices.DeviceR\bentities\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x125\n" +
	"\x04link\x18\x03 \x03(\v2!.devices.SearchResponse.LinkEntryR\x04link\x1a7\n" +
	"\tLinkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x0fHistoryResponse\x124\n" +
	"\thistories\x18\x01 \x03(\v2\x16.devices.DeviceHistoryR\thistories\"M\n" +
	"\x12ChildDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bchildren\x18\x02 \x03(\tR\bchildren\"O\n" +
	"\x13DeleteSensorRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\"H\n" +
	"\x0fGetLimitRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\"\xa2\x01\n" +
	"\x10GetLimitResponse\x12=\n" +
	"\x06limits\x18\x01 \x03(\v2%.devices.GetLimitResponse.LimitsEntryR\x06limits\x1aO\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.devices.SensorLimitR\x05value:\x028\x01\"\x9c\x05\n" +
	"\x0fSetLimitRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x1c\n" +
	"\tattribute\x18\x03 \x01(\tR\tattribute\x12\x1d\n" +
	"\n" +
	"normal_min\x18\x04 \x01(\x01R\tnormalMin\x12\x1d\n" +
	"\n" +
	"normal_max\x18\x05 \x01(\x01R\tnormalMax\x12\x1f\n" +
	"\vcaution_min\x18\x06 \x01(\x01R\n" +
	"cautionMin\x12\x1f\n" +
	"\vcaution_max\x18\a \x01(\x01R\n" +
	"cautionMax:\xb3\x03\xbaH\xaf\x03\x1ah\n" +
	"\x17normal_bound_constraint\x12*normal_max must be greater than normal_min\x1a!this.normal_max > this.normal_min\x1am\n" +
	"\x18caution_bound_constraint\x12,caution_max must be greater than caution_min\x1a#this.caution_max > this.caution_min\x1ai\n" +
	"\x16lower_bound_constraint\x12+normal_min must be greater than caution_min\x1a\"this.normal_min > this.caution_min\x1ai\n" +
	"\x16upper_bound_constraint\x12+caution_max must be greater than normal_max\x1a\"this.caution_max > this.normal_max\"i\n" +
	"\x12DeleteLimitRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x1c\n" +
	"\tattribute\x18\x03 \x01(\tR\tattribute\"L\n" +
	"\x11GetCommandRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"\x95\f\n" +
	"\x06Device\x12\x9b\x01\n" +
	"\tdevice_id\x18\x01 \x01(\tB~\x92A0J\v\"T00000001\"x\x0e\x80\x01\x02\x8a\x01\x1b^[a-zA-Z0-9_-]+[a-zA-Z0-9]$\xe0A\x02\xbaH#r!\x10\x02\x18\x0e2\x1b^[a-zA-Z0-9_-]+[a-zA-Z0-9]$\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(14),pk,notnullR\bdeviceId\x12h\n" +
	"\fdisplay_name\x18\x02 \x01(\tBE\x92A\x16J\x12\"테스트 노드\"xd\xe0A\x01\xbaH\x0er\f\x18d2\b^[^\n" +
	"\t]*$\xe2\xde\x1f\x14\n" +
	"\x12,type:varchar(100)R\vdisplayName\x12L\n" +
	"\vdescription\x18\x03 \x01(\tB*\x92A\x03x\xe8\a\xe0A\x01\xbaH\x05r\x03\x18\xe8\a\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(1000)R\vdescription\x12o\n" +
	"\vdevice_role\x18\x04 \x01(\x0e2\x13.devices.DeviceRoleB9\x92A\bJ\x06\"NODE\"\xe0A\x05\xe0A\x02\xe2\xde\x1f$\n" +
	"\",type:varchar(16),use_zero,notnullR\n" +
	"deviceRole\x12Z\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.devices.DeviceStatusB+\xe0A\x03\xe2\xde\x1f$\n" +
	"\",type:varchar(16),notnull,use_zeroR\x06status\x12A\n" +
	"\asensors\x18\x06 \x03(\v2\x0f.devices.SensorB\x16\xe0A\x01\xe2\xde\x1f\x0f\n" +
	"\r,rel:has-manyR\asensors\x12E\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\tcreatedAt\x12\xfb\x01\n" +
	"\n" +
	"created_by\x18\b \x01(\v2\x17.google.protobuf.StructB\xc2\x01\x92A\xb4\x01@\x01J\xaf\x01{\"email\": \"example@suredatalab.com\", \"first_name\": \"길동\", \"last_name\": \"홍\", \"username\": \"example\", \"name\": \"홍길동\", \"user_id\": \"UUID_000010\"}\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\tcreatedBy\x12E\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\tupdatedAt\x12\xfb\x01\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructB\xc2\x01\x92A\xb4\x01@\x01J\xaf\x01{\"email\": \"example@suredatalab.com\", \"first_name\": \"길동\", \"last_name\": \"홍\", \"username\": \"example\", \"name\": \"홍길동\", \"user_id\": \"UUID_000010\"}\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\tupdatedBy\x12>\n" +
	"\blocation\x18\v \x01(\v2\x11.beymons.LocationB\x0f\x92A\x02@\x01\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\blocation\x129\n" +
	"\x04site\x18\f \x01(\v2\x14.devices.Device.SiteB\x0f\x92A\x02@\x01\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\x04site\x12&\n" +
	"\bwritable\x18\x0e \x01(\bB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\bwritable\x1aF\n" +
	"\x04Site\x12\x1c\n" +
	"\asite_id\x18\x01 \x01(\tB\x03\xe0A\x03R\x06siteId\x12 \n" +
	"\tsite_name\x18\x02 \x01(\tB\x03\xe0A\x03R\bsiteName:0\xda\xde\x1f,\x1a*\n" +
	"\x18devices_display_name_idx\x12\x0e\n" +
	"\fdisplay_name\"\xd9\x03\n" +
	"\x0eDeviceRelation\x12c\n" +
	"\tparent_id\x18\x01 \x01(\tBF\xe2\xde\x1fB\n" +
	"@,type:varchar(14),pk,notnull,join_fk:device_id,on_delete:CASCADER\bparentId\x12H\n" +
	"\x06parent\x18\x05 \x01(\v2\x0f.devices.DeviceB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,rel:has-one,fk:parent_idR\x06parent\x12a\n" +
	"\bchild_id\x18\x02 \x01(\tBF\xe2\xde\x1fB\n" +
	"@,type:varchar(14),pk,notnull,join_fk:device_id,on_delete:CASCADER\achildId\x12E\n" +
	"\x05child\x18\x06 \x01(\v2\x0f.devices.DeviceB\x1e\xe2\xde\x1f\x1a\n" +
	"\x18,rel:has-one,fk:child_idR\x05child\x12h\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB-\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt:\x04\xda\xde\x1f\x00\"\xb3\a\n" +
	"\rDeviceHistory\x12n\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB3\xe0A\x05\xe0A\x03\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12?\n" +
	"\tdevice_id\x18\x02 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(14),notnullR\bdeviceId\x12`\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1b.devices.DeviceHistory.KindB+\xe0A\x05\xe2\xde\x1f$\n" +
	"\",type:varchar(10),notnull,use_zeroR\x06action\x12J\n" +
	"\x0fcreated_user_id\x18\x04 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(36),notnullR\rcreatedUserId\x12]\n" +
	"\fcreated_name\x18\x05 \x01(\tB:\xe0A\x04\xe0A\x05\xe2\xde\x1f0\n" +
	".,type:varchar(200),notnull,default:'Anonymous'R\vcreatedName\x12\xfb\x01\n" +
	"\n" +
	"created_by\x18\x06 \x01(\v2\x17.google.protobuf.StructB\xc2\x01\x92A\xb4\x01@\x01J\xaf\x01{\"email\": \"example@suredatalab.com\", \"first_name\": \"길동\", \"last_name\": \"홍\", \"username\": \"example\", \"name\": \"홍길동\", \"user_id\": \"UUID_000010\"}\xe0A\x05\xe2\xde\x1f\x03\n" +
	"\x01-R\tcreatedBy\x12B\n" +
	"\adetails\x18\a \x01(\v2\x17.google.protobuf.StructB\x0f\x92A\x02@\x01\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\adetails\"w\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\n" +
	"\n" +
	"\x06STATUS\x10\x03\x12\v\n" +
	"\aCOMMAND\x10\x04\x12\n" +
	"\n" +
	"\x06ATTACH\x10\x05\x12\n" +
	"\n" +
	"\x06DETACH\x10\x06\x12\v\n" +
	"\aINSTALL\x10\a\x12\r\n" +
	"\tUNINSTALL\x10\b:)\xda\xde\x1f%\x12#\n" +
	"\n" +
	"created_at\x12\x061 week\x1a\r\x1a\tdevice_id \n" +
	"\"\x84\x03\n" +
	"\x13DeviceUpdateHistory\x12k\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x05\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12?\n" +
	"\tdevice_id\x18\x02 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(14),notnullR\bdeviceId\x12=\n" +
	"\tattribute\x18\x03 \x01(\tB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(50),notnullR\tattribute\x121\n" +
	"\x06origin\x18\x04 \x01(\tB\x19\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(4000)R\x06origin\x121\n" +
	"\x06change\x18\x05 \x01(\tB\x19\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(4000)R\x06change:\x1a\xda\xde\x1f\x16\x12\x14\n" +
	"\n" +
	"created_at\x12\x061 week\"\x9e\x03\n" +
	"\x13DeviceStatusHistory\x12k\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x05\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12?\n" +
	"\tdevice_id\x18\x02 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(14),notnullR\bdeviceId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12W\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.devices.DeviceStatusB(\xe2\xde\x1f$\n" +
	"\",type:varchar(16),notnull,use_zeroR\x06status\x12;\n" +
	"\vdescription\x18\x05 \x01(\tB\x19\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(1000)R\vdescription:)\xda\xde\x1f%\x12#\n" +
	"\n" +
	"created_at\x12\x061 week\x1a\r\x1a\tdevice_id \n" +
	"\"\xe9\t\n" +
	"\x06Sensor\x12{\n" +
	"\tsensor_id\x18\x01 \x01(\tB^\x92A(J&\"UUID_000010\"\xe0A\x03\xe0A\x05\xe2\xde\x1f)\n" +
	"',type:uuid,pk,default:gen_random_uuid()R\bsensorId\x12~\n" +
	"\tdevice_id\x18\x02 \x01(\tBa\x92A\rJ\v\"T00000001\"\xe0A\x03\xe2\xde\x1fJ\n" +
	"2,type:varchar(14),notnull,unique:device_channel_id\x1a\x14sensors_device_id_fkR\bdeviceId\x12\x82\x01\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\rBc\x92A\x15J\x011Y\x00\x00\x00\x00\x00\xe0o@i\x00\x00\x00\x00\x00\x00\xf0?\xe0A\x02\xbaH\a*\x05\x18\xff\x01 \x00\xe2\xde\x1f:\n" +
	"8,type:smallint,notnull,use_zero,unique:device_channel_idR\tchannelId\x12t\n" +
	"\vsensor_type\x18\x04 \x01(\tBS\x92A\x0fJ\r\"temperature\"\xe0A\x02\xbaH\x04r\x02\x10\x02\xe2\xde\x1f3\n" +
	"\x19,type:varchar(16),notnull\x1a\x16sensors_sensor_type_fkR\n" +
	"sensorType\x12S\n" +
	"\fdisplay_name\x18\x05 \x01(\tB0\x92A\vJ\t\"온도1\"\xe0A\x01\xbaH\x04r\x02\x18d\xe2\xde\x1f\x14\n" +
	"\x12,type:varchar(100)R\vdisplayName\x12g\n" +
	"\vdescription\x18\x06 \x01(\tBE\x92A\x1eJ\x1c\"냉장고 뒤쪽에 부착\"\xe0A\x01\xbaH\x05r\x03\x18\xe8\a\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(1000)R\vdescription\x12\x95\x01\n" +
	"\x06latest\x18\a \x01(\v2\x17.google.protobuf.StructBd\x92AWJU{\"1\": {\"temp\": 25.4, \"ts\": 1717047881120 }, \"2\": {\"temp\": 25.6, \"ts\": 1717047881120}}\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\x06latest\x12E\n" +
	"\x06probes\x18\b \x01(\rB-\x92A\fJ\x011Y\x00\x00\x00\x00\x00\x80O@\xe0A\x01\xbaH\x04*\x02\x18?\xe2\xde\x1f\x10\n" +
	"\x0e,type:smallintR\x06probes\x12g\n" +
	"\x06status\x18\t \x01(\x0e2\x15.devices.DeviceStatusB8\x92A\n" +
	"J\b\"NORMAL\"\xe0A\x03\xe2\xde\x1f$\n" +
	"\",type:varchar(16),notnull,use_zeroR\x06status\x12E\n" +
	"\bfacility\x18\n" +
	" \x01(\v2\x18.devices.Sensor.FacilityB\x0f\x92A\x02@\x01\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\bfacility\x1a8\n" +
	"\bFacility\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x03R\x04name:`\xda\xde\x1f\\\n" +
	"+\n" +
	"\x14sensors_device_id_fk\x12\x06Device\x1a\tdevice_id \x01\n" +
	"-\n" +
	"\x16sensors_sensor_type_fk\x12\n" +
	"SensorType\x1a\atype_id\"\xa0\a\n" +
	"\x14DeviceCommandHistory\x12k\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x05\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12<\n" +
	"\tdevice_id\x18\x02 \x01(\tB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(14),notnullR\bdeviceId\x12o\n" +
	"\tdirection\x18\x03 \x01(\x0e2'.devices.DeviceCommandHistory.DirectionB(\xe2\xde\x1f$\n" +
	"\",type:varchar(10),use_zero,notnullR\tdirection\x129\n" +
	"\acommand\x18\x04 \x01(\tB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(30),notnullR\acommand\x123\n" +
	"\bsequence\x18\x05 \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\bsequence\x12C\n" +
	"\apayload\x18\x06 \x01(\tB)\xe2\xde\x1f%\n" +
	"#,type:jsonb,json_use_number,notnullR\apayload\x12f\n" +
	"\x06status\x18\a \x01(\x0e2$.devices.DeviceCommandHistory.StatusB(\xe2\xde\x1f$\n" +
	"\",type:varchar(10),use_zero,notnullR\x06status\x12V\n" +
	"\fresponded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x17\xe2\xde\x1f\x13\n" +
	"\x11,type:timestamptzR\vrespondedAt\x12=\n" +
	"\bresponse\x18\t \x01(\tB!\xe2\xde\x1f\x1d\n" +
	"\x1b,type:jsonb,json_use_numberR\bresponse\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\")\n" +
	"\tDirection\x12\f\n" +
	"\bupstream\x10\x00\x12\x0e\n" +
	"\n" +
	"downstream\x10\x01\"L\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFALLURE\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04:)\xda\xde\x1f%\x12#\n" +
	"\n" +
	"created_at\x12\x061 week\x1a\r\x1a\tdevice_id \n" +
	"\"\xc9\x05\n" +
	"\vSensorLimit\x12\x89\x01\n" +
	"\tdevice_id\x18\x01 \x01(\tBl\x92A(J&\"UUID_000010\"\xe0A\x03\xe2\xde\x1f:\n" +
	"\x1c,type:varchar(14),pk,notnull\x1a\x1asensor_limits_device_id_fkR\bdeviceId\x125\n" +
	"\achannel\x18\x02 \x01(\rB\x1b\xbaH\a*\x05\x18\xff\x01 \x00\xe2\xde\x1f\r\n" +
	"\v,pk,notnullR\achannel\x12m\n" +
	"\tattribute\x18\x03 \x01(\tBO\x92A\bJ\x06\"temp\"\xbaH\x1fr\x1d\x1822\x19^[a-z][a-z0-9_]*[a-z0-9]$\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(50),pk,notnullR\tattribute\x126\n" +
	"\n" +
	"normal_min\x18\x04 \x01(\x01B\x17\xe2\xde\x1f\x13\n" +
	"\x11,use_zero,notnullR\tnormalMin\x126\n" +
	"\n" +
	"normal_max\x18\x05 \x01(\x01B\x17\xe2\xde\x1f\x13\n" +
	"\x11,use_zero,notnullR\tnormalMax\x128\n" +
	"\vcaution_min\x18\x06 \x01(\x01B\x17\xe2\xde\x1f\x13\n" +
	"\x11,use_zero,notnullR\n" +
	"cautionMin\x128\n" +
	"\vcaution_max\x18\a \x01(\x01B\x17\xe2\xde\x1f\x13\n" +
	"\x11,use_zero,notnullR\n" +
	"cautionMax\x12k\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x03\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt:7\xda\xde\x1f3\n" +
	"1\n" +
	"\x1asensor_limits_device_id_fk\x12\x06Device\x1a\tdevice_id \x01*\x93\x01\n" +
	"\tAttribute\x12\x10\n" +
	"\fdisplay_name\x10\x00\x12\x0f\n" +
	"\vdescription\x10\x01\x12\v\n" +
	"\asensors\x10\x02\x12\f\n" +
	"\blocation\x10\x03\x12\x0e\n" +
	"\n" +
	"created_at\x10\x04\x12\x0e\n" +
	"\n" +
	"created_by\x10\x05\x12\x0e\n" +
	"\n" +
	"updated_at\x10\x06\x12\x0e\n" +
	"\n" +
	"updated_by\x10\a\x12\b\n" +
	"\x04site\x10\b*B\n" +
	"\n" +
	"DeviceRole\x12\v\n" +
	"\aGATEWAY\x10\x00\x12\b\n" +
	"\x04NODE\x10\x01\x12\f\n" +
	"\bREPEATER\x10\x02\x12\x0f\n" +
	"\vNODEGATEWAY\x10\x03*`\n" +
	"\fDeviceStatus\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\v\n" +
	"\aTROUBLE\x10\x01\x12\v\n" +
	"\aDISCARD\x10\x02\x12\x10\n" +
	"\fNOT_RECEIVED\x10\x03\x12\v\n" +
	"\aCAUTION\x10\x04\x12\v\n" +
	"\aWARNING\x10\x052\xa7\x13\n" +
	"\aDevices\x12\x9a\x01\n" +
	"\fCreateDevice\x12\x0f.devices.Device\x1a\x0f.devices.Device\"h\x92A=J;\n" +
	"\x03409\x124\n" +
	"*Returned when the device is already exists\x12\x062\x04null\xd2\xde\x1f\x11\n" +
	"\rcreate-device \x03\x82\xd3\xe4\x93\x02\r:\x01*\"\b/devices\x12p\n" +
	"\x06Search\x12\x16.devices.SearchRequest\x1a\x17.devices.SearchResponse\"5\xd2\xde\x1f!\n" +
	"\rquery-devices\n" +
	"\x0emanage-devices \x04\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/devices\x12~\n" +
	"\tGetDevice\x12\x16.devices.DeviceRequest\x1a\x17.devices.DeviceResponse\"@\xd2\xde\x1f \n" +
	"\fview-devices\n" +
	"\x0emanage-devices \x05\x82\xd3\xe4\x93\x02\x16\x12\x14/devices/{device_id}\x12\x87\x01\n" +
	"\tHistories\x12\x16.devices.DeviceRequest\x1a\x18.devices.HistoryResponse\"H\xd2\xde\x1f\x1e\n" +
	"\fview-devices\n" +
	"\x0emanage-devices\x82\xd3\xe4\x93\x02 \x12\x1e/devices/{device_id}/histories\x12g\n" +
	"\fUpdateDevice\x12\x0f.devices.Device\x1a\x0f.devices.Device\"5\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \x06\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/devices/{device_id}\x12\xbe\x02\n" +
	"\aCommand\x12\x17.devices.CommandRequest\x1a\x17.google.protobuf.Struct\"\x80\x02\x92A\b\n" +
	"\x06제어\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \t\x82\xd3\xe4\x93\x02\xd8\x01:\apayloadZ#:\x01*2\x1e/devices/{device_id}/{command}Z(:\tconfigure\"\x1b/devices/{device_id}/configZ):\bagsmotor\"\x1d/devices/{device_id}/agsmotorZ3:\ragsmotor_mode\"\"/devices/{device_id}/agsmotor_mode\"\x1e/devices/{device_id}/{command}\x12\x9a\x01\n" +
	"\n" +
	"GetCommand\x12\x1a.devices.GetCommandRequest\x1a\x1d.devices.DeviceCommandHistory\"Q\x92A\b\n" +
	"\x06제어\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \n" +
	"\x82\xd3\xe4\x93\x02*\x12(/devices/{device_id}/sequence/{sequence}\x12\x84\x01\n" +
	"\fAttachDevice\x12\x1b.devices.ChildDeviceRequest\x1a\x17.devices.DeviceResponse\">\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \b\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/devices/{device_id}/children\x12\x8c\x01\n" +
	"\fDetachDevice\x12\x1b.devices.ChildDeviceRequest\x1a\x17.devices.DeviceResponse\"F\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices P\x82\xd3\xe4\x93\x02**(/devices/{device_id}/children/{children}\x12b\n" +
	"\fDeleteDevice\x12\x16.devices.DeviceRequest\x1a\x16.google.protobuf.Empty\"\"\xd2\xde\x1f\x02 b\x82\xd3\xe4\x93\x02\x16*\x14/devices/{device_id}\x12\x95\x01\n" +
	"\fAppendSensor\x12\x0f.devices.Sensor\x1a\x16.google.protobuf.Empty\"\\\xd2\xde\x1f\x02 \a\x82\xd3\xe4\x93\x02P:\x01*Z-:\x01*\x1a(/devices/{device_id}/sensors/{sensor_id}\"\x1c/devices/{device_id}/sensors\x12|\n" +
	"\fDeleteSensor\x12\x1c.devices.DeleteSensorRequest\x1a\x16.google.protobuf.Empty\"6\xd2\xde\x1f\x02 Z\x82\xd3\xe4\x93\x02**(/devices/{device_id}/sensors/{sensor_id}\x12\x90\x01\n" +
	"\x0eGetSensorLimit\x12\x18.devices.GetLimitRequest\x1a\x19.devices.GetLimitResponse\"I\xd2\xde\x1f\x10\n" +
	"\fview-devices \f\x82\xd3\xe4\x93\x02/\x12-/devices/{device_id}/sensors/{channel}/limits\x12\x95\x01\n" +
	"\x0eSetSensorLimit\x12\x18.devices.SetLimitRequest\x1a\x14.devices.SensorLimit\"S\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \v\x82\xd3\xe4\x93\x027:\x01*\x1a2/devices/{device_id}/sensors/{channel}/{attribute}\x12\x9a\x01\n" +
	"\x11DeleteSensorLimit\x12\x1b.devices.DeleteLimitRequest\x1a\x16.google.protobuf.Empty\"P\xd2\xde\x1f\x12\n" +
	"\x0emanage-devices \r\x82\xd3\xe4\x93\x024*2/devices/{device_id}/sensors/{channel}/{attribute}\x1a\xe3\x01\x92A\x0f\x12\r장치 관리\xca\xde\x1f\xcc\x01\n" +
	"%\n" +
	"\rcreate-device\x12\x14장치 생성 권한\n" +
	" \n" +
	"\fdevice-admin\x12\x10장치 관리자\n" +
	"&\n" +
	"\x0emanage-devices\x12\x14장치 관리 권한\n" +
	"%\n" +
	"\rquery-devices\x12\x14장치 검색 권한\n" +
	"$\n" +
	"\fview-devices\x12\x14장치 조회 권한\x12\fdevice-adminB'Z%gitlab.suredatalab.kr/beymons/devicesb\x06proto3"

var (
	file_devices_proto_rawDescOnce sync.Once
	file_devices_proto_rawDescData []byte
)

func file_devices_proto_rawDescGZIP() []byte {
	file_devices_proto_rawDescOnce.Do(func() {
		file_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)))
	})
	return file_devices_proto_rawDescData
}

var file_devices_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_devices_proto_goTypes = []any{
	(Attribute)(0),                      // 0: devices.Attribute
	(DeviceRole)(0),                     // 1: devices.DeviceRole
	(DeviceStatus)(0),                   // 2: devices.DeviceStatus
	(SearchRequest_Order)(0),            // 3: devices.SearchRequest.Order
	(DeviceHistory_Kind)(0),             // 4: devices.DeviceHistory.Kind
	(DeviceCommandHistory_Direction)(0), // 5: devices.DeviceCommandHistory.Direction
	(DeviceCommandHistory_Status)(0),    // 6: devices.DeviceCommandHistory.Status
	(*DeviceRequest)(nil),               // 7: devices.DeviceRequest
	(*DeviceResponse)(nil),              // 8: devices.DeviceResponse
	(*SearchRequest)(nil),               // 9: devices.SearchRequest
	(*SearchResponse)(nil),              // 10: devices.SearchResponse
	(*HistoryResponse)(nil),             // 11: devices.HistoryResponse
	(*ChildDeviceRequest)(nil),          // 12: devices.ChildDeviceRequest
	(*DeleteSensorRequest)(nil),         // 13: devices.DeleteSensorRequest
	(*GetLimitRequest)(nil),             // 14: devices.GetLimitRequest
	(*GetLimitResponse)(nil),            // 15: devices.GetLimitResponse
	(*SetLimitRequest)(nil),             // 16: devices.SetLimitRequest
	(*DeleteLimitRequest)(nil),          // 17: devices.DeleteLimitRequest
	(*GetCommandRequest)(nil),           // 18: devices.GetCommandRequest
	(*Device)(nil),                      // 19: devices.Device
	(*DeviceRelation)(nil),              // 20: devices.DeviceRelation
	(*DeviceHistory)(nil),               // 21: devices.DeviceHistory
	(*DeviceUpdateHistory)(nil),         // 22: devices.DeviceUpdateHistory
	(*DeviceStatusHistory)(nil),         // 23: devices.DeviceStatusHistory
	(*Sensor)(nil),                      // 24: devices.Sensor
	(*DeviceCommandHistory)(nil),        // 25: devices.DeviceCommandHistory
	(*SensorLimit)(nil),                 // 26: devices.SensorLimit
	nil,                                 // 27: devices.DeviceResponse.LinkEntry
	nil,                                 // 28: devices.SearchResponse.LinkEntry
	nil,                                 // 29: devices.GetLimitResponse.LimitsEntry
	(*Device_Site)(nil),                 // 30: devices.Device.Site
	(*Sensor_Facility)(nil),             // 31: devices.Sensor.Facility
	(*structpb.Struct)(nil),             // 32: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 33: google.protobuf.Timestamp
	(*common.Location)(nil),             // 34: beymons.Location
	(*CommandRequest)(nil),              // 35: devices.CommandRequest
	(*emptypb.Empty)(nil),               // 36: google.protobuf.Empty
}
var file_devices_proto_depIdxs = []int32{
	19, // 0: devices.DeviceResponse.device:type_name -> devices.Device
	32, // 1: devices.DeviceResponse.params:type_name -> google.protobuf.Struct
	27, // 2: devices.DeviceResponse.link:type_name -> devices.DeviceResponse.LinkEntry
	19, // 3: devices.DeviceResponse.related:type_name -> devices.Device
	3,  // 4: devices.SearchRequest.order:type_name -> devices.SearchRequest.Order
	0,  // 5: devices.SearchRequest.field:type_name -> devices.Attribute
	1,  // 6: devices.SearchRequest.role:type_name -> devices.DeviceRole
	2,  // 7: devices.SearchRequest.status:type_name -> devices.DeviceStatus
	19, // 8: devices.SearchResponse.entities:type_name -> devices.Device
	28, // 9: devices.SearchResponse.link:type_name -> devices.SearchResponse.LinkEntry
	21, // 10: devices.HistoryResponse.histories:type_name -> devices.DeviceHistory
	29, // 11: devices.GetLimitResponse.limits:type_name -> devices.GetLimitResponse.LimitsEntry
	1,  // 12: devices.Device.device_role:type_name -> devices.DeviceRole
	2,  // 13: devices.Device.status:type_name -> devices.DeviceStatus
	24, // 14: devices.Device.sensors:type_name -> devices.Sensor
	33, // 15: devices.Device.created_at:type_name -> google.protobuf.Timestamp
	32, // 16: devices.Device.created_by:type_name -> google.protobuf.Struct
	33, // 17: devices.Device.updated_at:type_name -> google.protobuf.Timestamp
	32, // 18: devices.Device.updated_by:type_name -> google.protobuf.Struct
	34, // 19: devices.Device.location:type_name -> beymons.Location
	30, // 20: devices.Device.site:type_name -> devices.Device.Site
	19, // 21: devices.DeviceRelation.parent:type_name -> devices.Device
	19, // 22: devices.DeviceRelation.child:type_name -> devices.Device
	33, // 23: devices.DeviceRelation.created_at:type_name -> google.protobuf.Timestamp
	33, // 24: devices.DeviceHistory.created_at:type_name -> google.protobuf.Timestamp
	4,  // 25: devices.DeviceHistory.action:type_name -> devices.DeviceHistory.Kind
	32, // 26: devices.DeviceHistory.created_by:type_name -> google.protobuf.Struct
	32, // 27: devices.DeviceHistory.details:type_name -> google.protobuf.Struct
	33, // 28: devices.DeviceUpdateHistory.created_at:type_name -> google.protobuf.Timestamp
	33, // 29: devices.DeviceStatusHistory.created_at:type_name -> google.protobuf.Timestamp
	2,  // 30: devices.DeviceStatusHistory.status:type_name -> devices.DeviceStatus
	32, // 31: devices.Sensor.latest:type_name -> google.protobuf.Struct
	2,  // 32: devices.Sensor.status:type_name -> devices.DeviceStatus
	31, // 33: devices.Sensor.facility:type_name -> devices.Sensor.Facility
	33, // 34: devices.DeviceCommandHistory.created_at:type_name -> google.protobuf.Timestamp
	5,  // 35: devices.DeviceCommandHistory.direction:type_name -> devices.DeviceCommandHistory.Direction
	6,  // 36: devices.DeviceCommandHistory.status:type_name -> devices.DeviceCommandHistory.Status
	33, // 37: devices.DeviceCommandHistory.responded_at:type_name -> google.protobuf.Timestamp
	33, // 38: devices.SensorLimit.created_at:type_name -> google.protobuf.Timestamp
	26, // 39: devices.GetLimitResponse.LimitsEntry.value:type_name -> devices.SensorLimit
	19, // 40: devices.Devices.CreateDevice:input_type -> devices.Device
	9,  // 41: devices.Devices.Search:input_type -> devices.SearchRequest
	7,  // 42: devices.Devices.GetDevice:input_type -> devices.DeviceRequest
	7,  // 43: devices.Devices.Histories:input_type -> devices.DeviceRequest
	19, // 44: devices.Devices.UpdateDevice:input_type -> devices.Device
	35, // 45: devices.Devices.Command:input_type -> devices.CommandRequest
	18, // 46: devices.Devices.GetCommand:input_type -> devices.GetCommandRequest
	12, // 47: devices.Devices.AttachDevice:input_type -> devices.ChildDeviceRequest
	12, // 48: devices.Devices.DetachDevice:input_type -> devices.ChildDeviceRequest
	7,  // 49: devices.Devices.DeleteDevice:input_type -> devices.DeviceRequest
	24, // 50: devices.Devices.AppendSensor:input_type -> devices.Sensor
	13, // 51: devices.Devices.DeleteSensor:input_type -> devices.DeleteSensorRequest
	14, // 52: devices.Devices.GetSensorLimit:input_type -> devices.GetLimitRequest
	16, // 53: devices.Devices.SetSensorLimit:input_type -> devices.SetLimitRequest
	17, // 54: devices.Devices.DeleteSensorLimit:input_type -> devices.DeleteLimitRequest
	19, // 55: devices.Devices.CreateDevice:output_type -> devices.Device
	10, // 56: devices.Devices.Search:output_type -> devices.SearchResponse
	8,  // 57: devices.Devices.GetDevice:output_type -> devices.DeviceResponse
	11, // 58: devices.Devices.Histories:output_type -> devices.HistoryResponse
	19, // 59: devices.Devices.UpdateDevice:output_type -> devices.Device
	32, // 60: devices.Devices.Command:output_type -> google.protobuf.Struct
	25, // 61: devices.Devices.GetCommand:output_type -> devices.DeviceCommandHistory
	8,  // 62: devices.Devices.AttachDevice:output_type -> devices.DeviceResponse
	8,  // 63: devices.Devices.DetachDevice:output_type -> devices.DeviceResponse
	36, // 64: devices.Devices.DeleteDevice:output_type -> google.protobuf.Empty
	36, // 65: devices.Devices.AppendSensor:output_type -> google.protobuf.Empty
	36, // 66: devices.Devices.DeleteSensor:output_type -> google.protobuf.Empty
	15, // 67: devices.Devices.GetSensorLimit:output_type -> devices.GetLimitResponse
	26, // 68: devices.Devices.SetSensorLimit:output_type -> devices.SensorLimit
	36, // 69: devices.Devices.DeleteSensorLimit:output_type -> google.protobuf.Empty
	55, // [55:70] is the sub-list for method output_type
	40, // [40:55] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_devices_proto_init() }
func file_devices_proto_init() {
	if File_devices_proto != nil {
		return
	}
	file_command_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devices_proto_goTypes,
		DependencyIndexes: file_devices_proto_depIdxs,
		EnumInfos:         file_devices_proto_enumTypes,
		MessageInfos:      file_devices_proto_msgTypes,
	}.Build()
	File_devices_proto = out.File
	file_devices_proto_goTypes = nil
	file_devices_proto_depIdxs = nil
}
