// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sensor_types.proto

package devices

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "gitlab.suredatalab.kr/sdlmicro/middleware/options"
	metadata "gitlab.suredatalab.kr/services/metadata"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 사용 가능한 속성
type SearchTypeRequest_Attribute int32

const (
	// ID (Default)
	SearchTypeRequest_sensor_type_id SearchTypeRequest_Attribute = 0
	// 센서 타입 이름
	SearchTypeRequest_type_name SearchTypeRequest_Attribute = 1
	// 속성
	SearchTypeRequest_attributes SearchTypeRequest_Attribute = 2
	// 설명
	SearchTypeRequest_description SearchTypeRequest_Attribute = 3
	// 생성 일시
	SearchTypeRequest_created_at SearchTypeRequest_Attribute = 4
	// 생성한 사용자 정보
	SearchTypeRequest_created_by SearchTypeRequest_Attribute = 5
)

// Enum value maps for SearchTypeRequest_Attribute.
var (
	SearchTypeRequest_Attribute_name = map[int32]string{
		0: "sensor_type_id",
		1: "type_name",
		2: "attributes",
		3: "description",
		4: "created_at",
		5: "created_by",
	}
	SearchTypeRequest_Attribute_value = map[string]int32{
		"sensor_type_id": 0,
		"type_name":      1,
		"attributes":     2,
		"description":    3,
		"created_at":     4,
		"created_by":     5,
	}
)

func (x SearchTypeRequest_Attribute) Enum() *SearchTypeRequest_Attribute {
	p := new(SearchTypeRequest_Attribute)
	*p = x
	return p
}

func (x SearchTypeRequest_Attribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTypeRequest_Attribute) Descriptor() protoreflect.EnumDescriptor {
	return file_sensor_types_proto_enumTypes[0].Descriptor()
}

func (SearchTypeRequest_Attribute) Type() protoreflect.EnumType {
	return &file_sensor_types_proto_enumTypes[0]
}

func (x SearchTypeRequest_Attribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTypeRequest_Attribute.Descriptor instead.
func (SearchTypeRequest_Attribute) EnumDescriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{1, 0}
}

type SensorTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorTypeRequest) Reset() {
	*x = SensorTypeRequest{}
	mi := &file_sensor_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorTypeRequest) ProtoMessage() {}

func (x *SensorTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorTypeRequest.ProtoReflect.Descriptor instead.
func (*SensorTypeRequest) Descriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{0}
}

func (x *SensorTypeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type SearchTypeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 오름차순으로 정렬
	Asc []SearchTypeRequest_Attribute `protobuf:"varint,1,rep,packed,name=asc,proto3,enum=devices.SearchTypeRequest_Attribute" json:"asc,omitempty"`
	// 내림차순으로 정렬
	Desc []SearchTypeRequest_Attribute `protobuf:"varint,2,rep,packed,name=desc,proto3,enum=devices.SearchTypeRequest_Attribute" json:"desc,omitempty"`
	// 조회 필드 선택 (default: ALL)
	Field []SearchTypeRequest_Attribute `protobuf:"varint,3,rep,packed,name=field,proto3,enum=devices.SearchTypeRequest_Attribute" json:"field,omitempty"`
	// 응답으로 보내줄 레코드 수.
	// 지정하지 않거나 0인 경우 전체 레코드를 조회하지만,
	// 응답이 15초 이상 소요되는 경우 타임아웃 오류가 발생된다.
	Limit uint64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// 페이지에서 표시되는 첫 레코드의 인덱스 (Default: 0)
	Offset uint64 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	// 전체 검색 (type_id, type_name, description)
	Search string `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	// 센서 타입 ID로 검색
	TypeId        string `protobuf:"bytes,7,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTypeRequest) Reset() {
	*x = SearchTypeRequest{}
	mi := &file_sensor_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTypeRequest) ProtoMessage() {}

func (x *SearchTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTypeRequest.ProtoReflect.Descriptor instead.
func (*SearchTypeRequest) Descriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTypeRequest) GetAsc() []SearchTypeRequest_Attribute {
	if x != nil {
		return x.Asc
	}
	return nil
}

func (x *SearchTypeRequest) GetDesc() []SearchTypeRequest_Attribute {
	if x != nil {
		return x.Desc
	}
	return nil
}

func (x *SearchTypeRequest) GetField() []SearchTypeRequest_Attribute {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *SearchTypeRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchTypeRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchTypeRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchTypeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type SearchTypeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entities []*SensorType          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// 데이터의 총건수
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 관련 링크 (HATEOAS)
	Link          map[string]string `protobuf:"bytes,3,rep,name=link,proto3" json:"link,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTypeResponse) Reset() {
	*x = SearchTypeResponse{}
	mi := &file_sensor_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTypeResponse) ProtoMessage() {}

func (x *SearchTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTypeResponse.ProtoReflect.Descriptor instead.
func (*SearchTypeResponse) Descriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{2}
}

func (x *SearchTypeResponse) GetEntities() []*SensorType {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchTypeResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchTypeResponse) GetLink() map[string]string {
	if x != nil {
		return x.Link
	}
	return nil
}

// SensorType
//
// 센서 타입 관리
type SensorType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SensorType ID
	TypeId string `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty" pg:",type:varchar(16),pk,notnull"`
	// 타입 이름
	TypeName string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty" pg:",type:varchar(50)"`
	// 센서 내에 다수의 채널을 가질 수 있는지 여부
	MultiProbe bool `protobuf:"varint,3,opt,name=multi_probe,json=multiProbe,proto3" json:"multi_probe,omitempty" pg:",notnull,default:FALSE"`
	// 타입 설명
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" pg:",type:varchar(1000)"`
	// 생성 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// 생성한 사용자 ID
	CreatedUserId string `protobuf:"bytes,6,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty" pg:",type:varchar(36),notnull"`
	// 타입을 생성한 사용자 정보
	CreatedBy *structpb.Struct `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty" pg:"-"`
	// 속성
	Attributes []*SensorTypeAttribute `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" pg:"-"`
	// 리소스에 대한 변경 권한 여부
	Writable      bool `protobuf:"varint,9,opt,name=writable,proto3" json:"writable,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorType) Reset() {
	*x = SensorType{}
	mi := &file_sensor_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorType) ProtoMessage() {}

func (x *SensorType) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorType.ProtoReflect.Descriptor instead.
func (*SensorType) Descriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{3}
}

func (x *SensorType) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *SensorType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *SensorType) GetMultiProbe() bool {
	if x != nil {
		return x.MultiProbe
	}
	return false
}

func (x *SensorType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SensorType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SensorType) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *SensorType) GetCreatedBy() *structpb.Struct {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *SensorType) GetAttributes() []*SensorTypeAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SensorType) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

// SensorTypeAttribute
//
// 센서 타입에서 사용하는 속성을 관리
type SensorTypeAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type_id
	TypeId string `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty" pg:",type:varchar(16),unique:relation,notnull"`
	// 데이터 속성명
	Attribute string `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty" pg:",type:varchar(50),unique:relation,notnull"`
	// 단위
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty" pg:",type:varchar(50)"`
	// 수신된 데이터의 타입
	Type metadata.MetadataSchemaAttribute_Type `protobuf:"varint,4,opt,name=type,proto3,enum=metadata.MetadataSchemaAttribute_Type" json:"type,omitempty" pg:"-"`
	// 타입이 text인 경우 최대 길이
	Length uint32 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty" pg:"-"`
	// 원본 데이터를 관리하는 테이블에서의 타입
	TypeName string `protobuf:"bytes,6,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty" pg:",type:varchar(20),notnull"`
	// 설명
	Description   string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty" pg:",type:varchar(1000)"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorTypeAttribute) Reset() {
	*x = SensorTypeAttribute{}
	mi := &file_sensor_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorTypeAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorTypeAttribute) ProtoMessage() {}

func (x *SensorTypeAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorTypeAttribute.ProtoReflect.Descriptor instead.
func (*SensorTypeAttribute) Descriptor() ([]byte, []int) {
	return file_sensor_types_proto_rawDescGZIP(), []int{4}
}

func (x *SensorTypeAttribute) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *SensorTypeAttribute) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *SensorTypeAttribute) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SensorTypeAttribute) GetType() metadata.MetadataSchemaAttribute_Type {
	if x != nil {
		return x.Type
	}
	return metadata.MetadataSchemaAttribute_Type(0)
}

func (x *SensorTypeAttribute) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SensorTypeAttribute) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *SensorTypeAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_sensor_types_proto protoreflect.FileDescriptor

const file_sensor_types_proto_rawDesc = "" +
	"\n" +
	"\x12sensor_types.proto\x12\adevices\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a%sdlmicro/middleware/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a services/metadata/metadata.proto\"1\n" +
	"\x11SensorTypeRequest\x12\x1c\n" +
	"\atype_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06typeId\"\xb4\x03\n" +
	"\x11SearchTypeRequest\x12;\n" +
	"\x03asc\x18\x01 \x03(\x0e2$.devices.SearchTypeRequest.AttributeB\x03\xe0A\x01R\x03asc\x12=\n" +
	"\x04desc\x18\x02 \x03(\x0e2$.devices.SearchTypeRequest.AttributeB\x03\xe0A\x01R\x04desc\x12?\n" +
	"\x05field\x18\x03 \x03(\x0e2$.devices.SearchTypeRequest.AttributeB\x03\xe0A\x01R\x05field\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x04B\x03\xe0A\x01R\x05limit\x12\x1b\n" +
	"\x06offset\x18\x05 \x01(\x04B\x03\xe0A\x01R\x06offset\x12\x1b\n" +
	"\x06search\x18\x06 \x01(\tB\x03\xe0A\x01R\x06search\x12\x1c\n" +
	"\atype_id\x18\a \x01(\tB\x03\xe0A\x01R\x06typeId\"o\n" +
	"\tAttribute\x12\x12\n" +
	"\x0esensor_type_id\x10\x00\x12\r\n" +
	"\ttype_name\x10\x01\x12\x0e\n" +
	"\n" +
	"attributes\x10\x02\x12\x0f\n" +
	"\vdescription\x10\x03\x12\x0e\n" +
	"\n" +
	"created_at\x10\x04\x12\x0e\n" +
	"\n" +
	"created_by\x10\x05\"\xcf\x01\n" +
	"\x12SearchTypeResponse\x12/\n" +
	"\bentities\x18\x01 \x03(\v2\x13.devices.SensorTypeR\bentities\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x129\n" +
	"\x04link\x18\x03 \x03(\v2%.devices.SearchTypeResponse.LinkEntryR\x04link\x1a7\n" +
	"\tLinkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\a\n" +
	"\n" +
	"SensorType\x12\x98\x01\n" +
	"\atype_id\x18\x01 \x01(\tB\x7f\x92A0J\r\"temperature\"x\x10\x80\x01\x02\x8a\x01\x19^[a-z][a-z0-9_]*[a-z0-9]$\xe0A\x02\xe0A\x05\xbaH!r\x1f\x10\x02\x18\x102\x19^[a-z][a-z0-9_]*[a-z0-9]$\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(16),pk,notnullR\x06typeId\x12^\n" +
	"\ttype_name\x18\x02 \x01(\tBA\x92A\x13J\x0f\"온도 센서\"x2\xe0A\x01\xbaH\x0er\f\x1822\b^[^\n" +
	"\t]*$\xe2\xde\x1f\x13\n" +
	"\x11,type:varchar(50)R\btypeName\x12=\n" +
	"\vmulti_probe\x18\x03 \x01(\bB\x1c\xe2\xde\x1f\x18\n" +
	"\x16,notnull,default:FALSER\n" +
	"multiProbe\x12m\n" +
	"\vdescription\x18\x04 \x01(\tBK\x92A$J\x1f\"온도만 수집하는 센서\"x\xe8\a\xe0A\x01\xbaH\x05r\x03\x18\xe8\a\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(1000)R\vdescription\x12n\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB3\xe0A\x05\xe0A\x03\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12M\n" +
	"\x0fcreated_user_id\x18\x06 \x01(\tB%\xe0A\x05\xe0A\x03\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(36),notnullR\rcreatedUserId\x12\xfb\x01\n" +
	"\n" +
	"created_by\x18\a \x01(\v2\x17.google.protobuf.StructB\xc2\x01\x92A\xb4\x01@\x01J\xaf\x01{\"email\": \"example@suredatalab.com\", \"first_name\": \"길동\", \"last_name\": \"홍\", \"username\": \"example\", \"name\": \"홍길동\", \"user_id\": \"UUID_000010\"}\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\tcreatedBy\x12P\n" +
	"\n" +
	"attributes\x18\b \x03(\v2\x1c.devices.SensorTypeAttributeB\x12\xe0A\x02\xbaH\x05\x92\x01\x02\b\x01\xe2\xde\x1f\x03\n" +
	"\x01-R\n" +
	"attributes\x12&\n" +
	"\bwritable\x18\t \x01(\bB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\bwritable:\x04\xda\xde\x1f\x00\"\xd5\x05\n" +
	"\x13SensorTypeAttribute\x12\x80\x01\n" +
	"\atype_id\x18\x01 \x01(\tBg\x92A\x0fJ\r\"temperature\"\xe0A\x03\xe2\xde\x1fN\n" +
	"),type:varchar(16),unique:relation,notnull\x1a!sensor_type_attributes_type_id_fkR\x06typeId\x12\x90\x01\n" +
	"\tattribute\x18\x02 \x01(\tBr\x92A!J\x06\"temp\"x2\x80\x01\x01\x8a\x01\x11^[a-z][a-z0-9_]*$\xe0A\x05\xbaH\x19r\x17\x10\x01\x1822\x11^[a-z][a-z0-9_]*$\xe2\xde\x1f+\n" +
	"),type:varchar(50),unique:relation,notnullR\tattribute\x12K\n" +
	"\x04unit\x18\x03 \x01(\tB7\x92A\tJ\x05\"℃\"x2\xe0A\x01\xbaH\x0er\f\x1822\b^[^\n" +
	"\t]*$\xe2\xde\x1f\x13\n" +
	"\x11,type:varchar(50)R\x04unit\x12Q\n" +
	"\x04type\x18\x04 \x01(\x0e2&.metadata.MetadataSchemaAttribute.TypeB\x15\x92A\bJ\x06\"real\"\xe0A\x04\xe2\xde\x1f\x03\n" +
	"\x01-R\x04type\x12\"\n" +
	"\x06length\x18\x05 \x01(\rB\n" +
	"\xe0A\x04\xe2\xde\x1f\x03\n" +
	"\x01-R\x06length\x12J\n" +
	"\ttype_name\x18\x06 \x01(\tB-\x92A\bJ\x06\"real\"\xe0A\x03\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(20),notnullR\btypeName\x12V\n" +
	"\vdescription\x18\a \x01(\tB4\x92A\rJ\b\"온도\"x\xe8\a\xe0A\x01\xbaH\x05r\x03\x18\xe8\a\xe2\xde\x1f\x15\n" +
	"\x13,type:varchar(1000)R\vdescription:@\xda\xde\x1f<\n" +
	":\n" +
	"!sensor_type_attributes_type_id_fk\x12\n" +
	"SensorType\x1a\atype_id \x012\x84\x05\n" +
	"\vSensorTypes\x12\xa6\x01\n" +
	"\n" +
	"SearchType\x12\x1a.devices.SearchTypeRequest\x1a\x1b.devices.SearchTypeResponse\"_\xd2\xde\x1f+\n" +
	"\x12query-sensor-types\n" +
	"\x13manage-sensor-types \x02\x82\xd3\xe4\x93\x02*Z\x19\x12\x17/sensor-types/{type_id}\x12\r/sensor-types\x12\xaf\x01\n" +
	"\n" +
	"CreateType\x12\x13.devices.SensorType\x1a\x13.devices.SensorType\"w\x92ABJ@\n" +
	"\x03409\x129\n" +
	"/Returned when the sensor type is already exists\x12\x062\x04null\xd2\xde\x1f\x16\n" +
	"\x12create-sensor-type \x01\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/sensor-types\x12|\n" +
	"\n" +
	"DeleteType\x12\x1a.devices.SensorTypeRequest\x1a\x16.google.protobuf.Empty\":\xd2\xde\x1f\x17\n" +
	"\x13manage-sensor-types c\x82\xd3\xe4\x93\x02\x19*\x17/sensor-types/{type_id}\x1a\x9b\x01\x92A\x16\x12\x14센서 타입 관리\xca\xde\x1f~\n" +
	"#\n" +
	"\x12create-sensor-type\x12\r생성 권한\n" +
	"$\n" +
	"\x13manage-sensor-types\x12\r관리 권한\n" +
	"#\n" +
	"\x12query-sensor-types\x12\r검색 권한\x12\fdevice-adminB'Z%gitlab.suredatalab.kr/beymons/devicesb\x06proto3"

var (
	file_sensor_types_proto_rawDescOnce sync.Once
	file_sensor_types_proto_rawDescData []byte
)

func file_sensor_types_proto_rawDescGZIP() []byte {
	file_sensor_types_proto_rawDescOnce.Do(func() {
		file_sensor_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_types_proto_rawDesc), len(file_sensor_types_proto_rawDesc)))
	})
	return file_sensor_types_proto_rawDescData
}

var file_sensor_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sensor_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sensor_types_proto_goTypes = []any{
	(SearchTypeRequest_Attribute)(0),           // 0: devices.SearchTypeRequest.Attribute
	(*SensorTypeRequest)(nil),                  // 1: devices.SensorTypeRequest
	(*SearchTypeRequest)(nil),                  // 2: devices.SearchTypeRequest
	(*SearchTypeResponse)(nil),                 // 3: devices.SearchTypeResponse
	(*SensorType)(nil),                         // 4: devices.SensorType
	(*SensorTypeAttribute)(nil),                // 5: devices.SensorTypeAttribute
	nil,                                        // 6: devices.SearchTypeResponse.LinkEntry
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                    // 8: google.protobuf.Struct
	(metadata.MetadataSchemaAttribute_Type)(0), // 9: metadata.MetadataSchemaAttribute.Type
	(*emptypb.Empty)(nil),                      // 10: google.protobuf.Empty
}
var file_sensor_types_proto_depIdxs = []int32{
	0,  // 0: devices.SearchTypeRequest.asc:type_name -> devices.SearchTypeRequest.Attribute
	0,  // 1: devices.SearchTypeRequest.desc:type_name -> devices.SearchTypeRequest.Attribute
	0,  // 2: devices.SearchTypeRequest.field:type_name -> devices.SearchTypeRequest.Attribute
	4,  // 3: devices.SearchTypeResponse.entities:type_name -> devices.SensorType
	6,  // 4: devices.SearchTypeResponse.link:type_name -> devices.SearchTypeResponse.LinkEntry
	7,  // 5: devices.SensorType.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: devices.SensorType.created_by:type_name -> google.protobuf.Struct
	5,  // 7: devices.SensorType.attributes:type_name -> devices.SensorTypeAttribute
	9,  // 8: devices.SensorTypeAttribute.type:type_name -> metadata.MetadataSchemaAttribute.Type
	2,  // 9: devices.SensorTypes.SearchType:input_type -> devices.SearchTypeRequest
	4,  // 10: devices.SensorTypes.CreateType:input_type -> devices.SensorType
	1,  // 11: devices.SensorTypes.DeleteType:input_type -> devices.SensorTypeRequest
	3,  // 12: devices.SensorTypes.SearchType:output_type -> devices.SearchTypeResponse
	4,  // 13: devices.SensorTypes.CreateType:output_type -> devices.SensorType
	10, // 14: devices.SensorTypes.DeleteType:output_type -> google.protobuf.Empty
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sensor_types_proto_init() }
func file_sensor_types_proto_init() {
	if File_sensor_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_types_proto_rawDesc), len(file_sensor_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_types_proto_goTypes,
		DependencyIndexes: file_sensor_types_proto_depIdxs,
		EnumInfos:         file_sensor_types_proto_enumTypes,
		MessageInfos:      file_sensor_types_proto_msgTypes,
	}.Build()
	File_sensor_types_proto = out.File
	file_sensor_types_proto_goTypes = nil
	file_sensor_types_proto_depIdxs = nil
}
