apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.name }}"
  labels:
    instance_id: "{{ .Values.instance_id }}"
    pod_type: "collect"
    collect_id: "{{ .Values.collect_id }}"
    dataset_id: "{{ .Values.dataset_id }}"
    work_func_type: "remote-server"
    workspace_id: "{{ .Values.workspace_id }}"
    helm_name: {{ .Values.name }}
spec:
  containers:
  - name: remote-server
    image: {{ .Values.registry }}{{ .Values.image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
    env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
    # envFrom:
    # - configMapRef:
    #     name: jfb-settings
    command: ["sh", "-c", "python3 /app/src/collect/remote_server.py"] #while true; do sleep 30; done; python3 /app/src/collect/remote_server.py
    resources:
      limits:
        cpu: {{ .Values.resource.cpu }}
        memory: {{ .Values.resource.memory }} # 256 MiB
    volumeMounts:
    - name: data-pvc
      mountPath: "/jf-data"
      subPath: "{{ .Values.dataset_path }}"
  volumes:
  - name: data-pvc
    persistentVolumeClaim:
      claimName: {{ .Values.dataset_pvc_name }}
