# CI/CD 시 ArgoCD 템플릿

.argo_refresh:
  image: ${CONTAINER_REGISTRY_ADDRESS}/argocd-cli:0.1.0
  script:
    - echo "ArgoCD에 로그인 시도..."
    - echo "Addr ${ARGOCD_ADDRESS}, Name ${ARGOCD_ID}"
    - argocd login "${ARGOCD_ADDRESS}" 
      --username "${ARGOCD_ID}" 
      --password "${ARGOCD_PASSWORD}" 
      --insecure
    - echo "ArgoCD로 배포..."
    - argocd app set 
        "${ARGOCD_APP_NAME}" 
        --helm-set "${HELM_CHART_IMAGE_KEY}=${CONTAINER_REGISTRY_ADDRESS}/${IMAGE_NAME}:${DEPLOY_TARGET}" # 이미지 버전 등록
    - argocd app get 
        "${ARGOCD_APP_NAME}" 
        --hard-refresh # 강제 갱신
    - argocd app sync "${ARGOCD_APP_NAME}" # 동기화

.argo_refresh_no_image_changed:
  image: ${CONTAINER_REGISTRY_ADDRESS}/argocd-cli:0.1.0
  script:
    - echo "ArgoCD에 로그인 시도..."
    - echo "Addr ${ARGOCD_ADDRESS}, Name ${ARGOCD_ID}"
    - argocd login "${ARGOCD_ADDRESS}" 
      --username "${ARGOCD_ID}" 
      --password "${ARGOCD_PASSWORD}" 
      --insecure
    - echo "ArgoCD로 배포..."
    - argocd app get 
        "${ARGOCD_APP_NAME}" 
        --hard-refresh # 강제 갱신
    - argocd app sync "${ARGOCD_APP_NAME}" # 동기화

