# 배포 혹은 테스트 수행 등 조건 확인용 범용 템플릿

.general_when_push:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.general_when_merge_request:
 rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.general_check_needed:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")

.general_deploy_needed:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.general_skip_deploy_not_needed: # 해당 템플릿만 extend할 경우 실행되지 않을 수 있으므로 유의
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never

# .general_when_apps_changed:
#   rules:
#     - changes:
#       - $APPS_DIR_REL/**/*

# .general_when_devops_changed:
#   rules:
#     - changes:
#       - $DEVOPS_DIR_REL/**/*

# .general_when_anything_changed:
#   rules:
#     - changes:
#       - $APPS_DIR_REL/**/*
#       - $DEVOPS_DIR_REL/**/*