# CI/CD 시 헬름 템플릿

.helm_push:
  image: ventx/helm3-ci:2.3.0
  script:
    - echo "헬름 레포에 로그인 시도... ${HELM_REPO_LOGIN_ADDRESS} ${HELM_REPO_USERNAME} pw***"
    - helm registry login "${HELM_REPO_LOGIN_ADDRESS}" 
      --username "${HELM_REPO_USERNAME}" 
      --password "${HELM_REPO_PASSWORD}" # 레지스트리 로그인
    - echo "헬름 차트 관련 경로 설정... ${HELM_CHART_DIR}" 
    - cd "${HELM_CHART_DIR}"
    - echo "의존성 빌드..."
    - helm dependency build
    - echo "헬름 빌드 시도..."
    - helm package . 
      --version "${HELM_CHART_VERSION}" # 헬름 차트 빌드
    - echo "헬름 푸시 시도..."
    - helm push 
        "${HELM_CHART_NAME}-${HELM_CHART_VERSION}.tgz" 
        "$HELM_REPO_ACTUAL_ADDRESS" # 헬름 차트 푸시

# 재귀적으로 의존성 빌드가 필요한 경우.
# chart dir 상위 경로에 helm_dependency.sh가 있다고 가정
# 해당 스크립트는 해당 차트의 helm dependency build도 수행해야 함
.helm_push_recursive:
  image: ventx/helm3-ci:2.3.0
  script:
    - echo "헬름 레포에 로그인 시도... ${HELM_REPO_LOGIN_ADDRESS} ${HELM_REPO_USERNAME} pw***"
    - helm registry login "${HELM_REPO_LOGIN_ADDRESS}" 
      --username "${HELM_REPO_USERNAME}" 
      --password "${HELM_REPO_PASSWORD}" # 레지스트리 로그인
    - echo "헬름 차트 관련 경로 설정... ${HELM_CHART_DIR}" 
    - cd "${HELM_CHART_DIR}"
    - cd ..
    - echo "의존성 빌드 스크립트 실행..."
    - ./helm_dependency.sh
    - cd "${HELM_CHART_DIR}"
    - echo "헬름 빌드 시도..."
    - helm package . 
      --version "${HELM_CHART_VERSION}" # 헬름 차트 빌드
    - echo "헬름 푸시 시도..."
    - helm push 
        "${HELM_CHART_NAME}-${HELM_CHART_VERSION}.tgz" 
        "$HELM_REPO_ACTUAL_ADDRESS" # 헬름 차트 푸시