apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: {{ .Values.global.jfb.name.front }}-api
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  ingressClassName: {{ .Values.global.jfb.settings.external.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Values.global.jfb.name.front }}-svc
            port:
              number: 8001
        path: /
        pathType: Prefix
