import os

JF_HOST_PATH = os.getenv('JF_HOST_PATH',"") # TODO
JF_DATA_HOST_PATH = os.getenv('JF_DATA_HOST_PATH',"") # TODO
JF_BIN_HOST_PATH = os.getenv('JF_BIN_HOST_PATH',"") # TODO
## API app path
JF_MAIN_STORAGE_PATH = "/jf-data/{STORAGE_NAME}/main/{WORKSPACE_NAME}"
JF_MAIN_PROJECT_PATH = JF_MAIN_STORAGE_PATH + "/projects/{PROJECT_NAME}" 
JF_MAIN_PROJECT_SRC_PATH = JF_MAIN_PROJECT_PATH + "/src"
JF_MAIN_PROJECT_BUILT_IN_CHECKPOINT_PATH = JF_MAIN_PROJECT_PATH + "/built_in_checkpoint"
JF_MAIN_PROJECT_HPS_LOG_PATH = JF_MAIN_PROJECT_PATH + "/hps_logs"
JF_MAIN_PROJECT_HPS_LOG_FILE_PATH = JF_MAIN_PROJECT_HPS_LOG_PATH + "/{HPS_ID}.json"
JF_MAIN_MODEL_PATH = JF_MAIN_STORAGE_PATH + "/models/{MODEL_NAME}"
JF_MAIN_RAG_PATH = JF_MAIN_STORAGE_PATH + "/rags/{RAG_ID}"
JF_MAIN_PREPROCESSING_PATH = JF_MAIN_STORAGE_PATH + "/preprocessings/{PREPROCESSING_NAME}"
JF_DATA_STORAGE_PATH = "/jf-data/{STORAGE_NAME}/data/{WORKSPACE_NAME}"
JF_DATA_DATASET_PATH = JF_DATA_STORAGE_PATH+"/{ACCESS}/{DATASET_NAME}"
JF_DATA_DATASET_DATA_PATH = JF_DATA_DATASET_PATH + "/{DATA_PATH}"

## PROJECT POD path
JF_PROJECT_HOME_NAME = "project"
JF_PROJECT_BASE_HOME_POD_PATH = f"/root/{JF_PROJECT_HOME_NAME}"
JF_MAIN_TOOL_CLUSTER_HOSTFILE_PATH = JF_MAIN_PROJECT_SRC_PATH + "/.config/nodes-{POD_NAME}"
JF_BUILT_IN_MODEL_PATH = "/model"
JF_BUILT_IN_DATASET_PATH = "/dataset"
JF_BUILT_IN_CHECKPOINT_PATH = "/built_in_checkpoint"
# JG_BUILT_IN_CHECKPOINT_HPS_PATH = "/built_in_checkpoint/HPS/{HPS_ID}"
# JG_BUILT_IN_CHECKPOINT_FILE_HPS_PATH = JG_BUILT_IN_CHECKPOINT_HPS_PATH +"/{STEP}/checkpoint.pth"
JF_BUILT_IN_CHECKPOINT_FILE_PATH = JF_BUILT_IN_CHECKPOINT_PATH + "/{JOB_ID}/checkpoint.pth"
JF_BUILT_IN_TRAIN_SCRIPT_PATH = JF_BUILT_IN_MODEL_PATH + "/train.py"

# PREPROCESSING POD path
JF_PREPROCESSING_HOME_NAME = "preprocessing"
JF_PREPROCESSING_BASE_HOME_POD_PATH = f"/root/{JF_PREPROCESSING_HOME_NAME}"
JF_PREPROCESSING_TOOL_CLUSTER_HOSTFILE_PATH = JF_MAIN_PREPROCESSING_PATH + "/.config/nodes-{POD_NAME}"
JF_PREPROCESSING_BUILT_IN_CODE_BASE_PATH = "/built_in"
JF_PREPROCESSING_BUILT_IN_CODE_PATH = JF_PREPROCESSING_BUILT_IN_CODE_BASE_PATH + "/{RUN_CODE}"
JF_PREPROCESSING_DATA_PATH = "/dataset/{DATA_PATH}"

## MODEL APP PATH
JF_MODEL_COMMIT_PATH = JF_MAIN_MODEL_PATH + "/commit_models"
JF_MODEL_COMMIT_LOG_PATH = JF_MAIN_MODEL_PATH + "/commit_logs"
JF_MODEL_LATEST_CHECKPOINT_PATH = JF_MAIN_MODEL_PATH + "/latest_checkpoint"
JF_MODEL_TMP_PATH = JF_MAIN_MODEL_PATH + "/tmp_model"
JF_MODEL_TOKENIZER_PATH = JF_MAIN_MODEL_PATH + "/tokenizer"
JF_MODEL_LOG_PATH = JF_MAIN_MODEL_PATH + "/logs"
JF_MODEL_CONFIGURATION_PATH = JF_MAIN_MODEL_PATH + "/configurations"
JF_MODEL_CONFIGURATION_FILE_PATH = JF_MODEL_CONFIGURATION_PATH + "/{FILE_NAME}"

# MODEL POD PATH
JF_POD_MODELS_PATH = "/models"
JF_POD_MODEL_PATH = JF_POD_MODELS_PATH + "/{MODEL_NAME}"
JF_POD_MODEL_COMMIT_MODELS_PATH = JF_POD_MODEL_PATH + "/commit_models"
JF_POD_MODEL_COMMIT_MODEL_PATH = JF_POD_MODEL_COMMIT_MODELS_PATH + "/{COMMIT_NAME}"
JF_POD_MODEL_SOURCE_MODEL_PATH = JF_POD_MODEL_COMMIT_MODELS_PATH + "/source_model"
JF_POD_MODEL_TOKENIZER_PATH = JF_POD_MODEL_PATH + "/tokenizer"
JF_POD_MODEL_TMP_MODEL_PATH = JF_POD_MODEL_PATH + "/tmp_model"
JF_POD_MODEL_LATEST_CHECKPOINT_PATH = JF_POD_MODEL_PATH + "/latest_checkpoint"
JF_POD_MODEL_LATEST_LOG_PATH = JF_POD_MODEL_PATH + "/logs"
JF_POD_MODEL_COMMIT_LOG_PATH = JF_POD_MODEL_PATH + "/commit_logs/{COMMIT_NAME}"
JF_POD_MODEL_FINE_TUNING_SCRIPT_PATH = "/fine_tuning"
JF_POD_MODEL_CONFIG_FILE_PATH = JF_POD_MODELS_PATH + "/configurations/{FILE_NAME}"
JF_POD_MODEL_FINE_TUNING_DATASET_PATH = "/dataset/{DATASET_NAME}/{FILE_PATH}"


# TODO HPS 관련사항은 추후 수정될 예정
# HPS 저장 경로 관련
JF_PROJECT_HPS_SAVE_LOAD_FILE_DIR_NAME = "hps_save_load_files"
JF_PROJECT_HPS_SAVE_FILE_DIR_POD_STATIC_PATH = f"/{JF_PROJECT_HPS_SAVE_LOAD_FILE_DIR_NAME}"
# HPS log 경로 관련
JF_PROJECT_HPS_LOG_DIR_NAME = "hps_logs"
JF_PROJECT_HPS_LOG_DIR_POD_PATH = f"/{JF_PROJECT_HPS_LOG_DIR_NAME}"
JF_PROJECT_HPS_LOG_ORIGINAL_RECORD_FILE_POD_PATH = JF_PROJECT_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}.json" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}.json"
JF_PROJECT_HPS_LOG_N_ITER_FILE_DIR_POD_PATH = JF_PROJECT_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}"


########## DEPLOYMENT ONLY ###############
JF_DEPLOYMENT_PATH = "/jf-data/{main_storage_name}/main/{workspace_name}/deployments/{deployment_name}"
JF_DEPLOYMENT_WORKER_LOG_DIR_PATH = JF_DEPLOYMENT_PATH + "/log/{deployment_worker_id}"

POD_API_LOG_BASE_PATH_IN_POD="/log"
POD_API_LOG_BASE_PATH_IN_JF_API="{DEPLOYMENT_HOME_IN_JF_API}/log/{DEPLOYMENT_WORKER_ID}"
POD_API_LOG_BASE_PATH_IN_HOST_PATH="{DEPLOYMENT_HOME_IN_HOST}/log/{DEPLOYMENT_WORKER_ID}"

POD_API_LOG_FILE_NAME="monitor.txt"
POD_API_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_API_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_API_LOG_FILE_NAME=POD_API_LOG_FILE_NAME)
POD_API_LOG_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_API_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_API_LOG_FILE_NAME=POD_API_LOG_FILE_NAME)

POD_API_LOG_IMPORT_CHECK_FILE_NAME="import.txt"
POD_API_LOG_IMPORT_CHECK_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_API_LOG_IMPORT_CHECK_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_API_LOG_IMPORT_CHECK_FILE_NAME=POD_API_LOG_IMPORT_CHECK_FILE_NAME)
POD_API_LOG_IMPORT_CHECK_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_API_LOG_IMPORT_CHECK_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_API_LOG_IMPORT_CHECK_FILE_NAME=POD_API_LOG_IMPORT_CHECK_FILE_NAME)

POD_NGINX_ACCESS_LOG_FILE_NAME="nginx_access.log"
POD_NGINX_ACEESS_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ACCESS_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ACCESS_LOG_FILE_NAME=POD_NGINX_ACCESS_LOG_FILE_NAME)
POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_ACCESS_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_ACCESS_LOG_FILE_NAME=POD_NGINX_ACCESS_LOG_FILE_NAME)
def GET_POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API(main_storage_name, workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(main_storage_name=main_storage_name, workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_ACEESS_LOG_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)


POD_NGINX_ERROR_LOG_FILE_NAME="nginx_error.log"
# POD_NGINX_ERROR_LOG_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ERROR_LOG_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ERROR_LOG_FILE_NAME=POD_NGINX_ERROR_LOG_FILE_NAME)

POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME="nginx_access_per_hour.log"
POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME=POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME)
POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME=POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_NAME)
def GET_POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API(main_storage_name, workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(main_storage_name=main_storage_name, workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_ACCESS_LOG_PER_HOUR_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)

POD_API_LOG_COUNT_FILE_NAME="count.json"

POD_NGINX_LOG_COUNT_FILE_NAME="nginx_count.json"
POD_NGINX_LOG_COUNT_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_NGINX_LOG_COUNT_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_NGINX_LOG_COUNT_FILE_NAME=POD_NGINX_LOG_COUNT_FILE_NAME)
POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_NGINX_LOG_COUNT_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_NGINX_LOG_COUNT_FILE_NAME=POD_NGINX_LOG_COUNT_FILE_NAME)
def GET_POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API(main_storage_name, workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(main_storage_name=main_storage_name, workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_NGINX_LOG_COUNT_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)


POD_RUN_TIME_FILE_NAME="pod_run_time.json"
POD_RUN_TIME_FILE_PATH_IN_POD="{POD_API_LOG_BASE_PATH_IN_POD}/{POD_RUN_TIME_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_POD=POD_API_LOG_BASE_PATH_IN_POD, POD_RUN_TIME_FILE_NAME=POD_RUN_TIME_FILE_NAME)
POD_RUN_TIME_FILE_PATH_IN_JF_API="{POD_API_LOG_BASE_PATH_IN_JF_API}/{POD_RUN_TIME_FILE_NAME}".format(POD_API_LOG_BASE_PATH_IN_JF_API=POD_API_LOG_BASE_PATH_IN_JF_API, POD_RUN_TIME_FILE_NAME=POD_RUN_TIME_FILE_NAME)
def GET_POD_RUN_TIME_FILE_PATH_IN_JF_API(main_storage_name, workspace_name, deployment_name, deployment_worker_id):
    DEPLOYMENT_HOME_IN_JF_API = JF_DEPLOYMENT_PATH.format(main_storage_name=main_storage_name, workspace_name=workspace_name, deployment_name=deployment_name)
    return POD_RUN_TIME_FILE_PATH_IN_JF_API.format(DEPLOYMENT_HOME_IN_JF_API=DEPLOYMENT_HOME_IN_JF_API, DEPLOYMENT_WORKER_ID=deployment_worker_id)

POD_DASHBOARD_HISTORY_FILE_NAME="dashboard_history.json"
POD_DASHBOARD_HISTORY_BACK_FILE_NAME="dashboard_history_bak.json"
POD_DASHBOARD_LIVE_HISTORY_FILE_NAME="dashboard_live_history.json"
POD_DASHBOARD_LIVE_HISTORY_BACK_FILE_NAME="dashboard_live_history_bak.json"


