import os

## API app path
JF_MAIN_STORAGE_PATH = "/jf-data/{STORAGE_NAME}/main/{WORKSPACE_NAME}"
JF_MAIN_PROJECT_PATH = JF_MAIN_STORAGE_PATH + "/projects/{PROJECT_NAME}"
JF_MAIN_TOOL_CLUSTER_HOSTFILE_PATH = JF_MAIN_PROJECT_PATH + "/.config/nodes-{POD_NAME}"
JF_DATA_STORAGE_PATH = "/jf-data/{STORAGE_NAME}/data/{WORKSPACE_NAME}"
JF_DATA_DATASET_PATH = JF_DATA_STORAGE_PATH+"/{ACCESS}/{DATASET_NAME}"



## POD path
JF_PROJECT_HOME_NAME = "project"
JF_PROJECT_BASE_HOME_POD_PATH = f"/root/{JF_PROJECT_HOME_NAME}"


# TRAINING 로그 관련
JF_PROJECT_TRAINING_LOG_DIR_NAME = "training_logs"
JF_PROJECT_TRAINING_LOG_DIR_POD_PATH = f"/{JF_PROJECT_TRAINING_LOG_DIR_NAME}"
JF_PROJECT_TRAINING_LOG_DIR_MAIN_PATH = JF_MAIN_PROJECT_PATH + JF_PROJECT_TRAINING_LOG_DIR_POD_PATH



# HPS 저장 경로 관련
JF_PROJECT_HPS_SAVE_LOAD_FILE_DIR_NAME = "hps_save_load_files"
JF_PROJECT_HPS_SAVE_FILE_DIR_POD_STATIC_PATH = f"/{JF_PROJECT_HPS_SAVE_LOAD_FILE_DIR_NAME}"
# HPS log 경로 관련
JF_PROJECT_HPS_LOG_DIR_NAME = "hps_logs"
JF_PROJECT_HPS_LOG_DIR_POD_PATH = f"/{JF_PROJECT_HPS_LOG_DIR_NAME}"
JF_PROJECT_HPS_LOG_ORIGINAL_RECORD_FILE_POD_PATH = JF_PROJECT_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}.json" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}.json"
JF_PROJECT_HPS_LOG_N_ITER_FILE_DIR_POD_PATH = JF_PROJECT_HPS_LOG_DIR_POD_PATH + "/" + "{hps_id}" # JF_TRAINING_POD_PATH + "/" + JF_TRAINING_HPS_LOG_DIR_NAME + "/" + "{hps_id}"
