apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-dataset

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role-dataset
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["PersistentVolumes", "PersistentVolumeClaims","PersistentVolumeClaims/status","nodes"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role-binding-dataset
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-dataset
  namespace: {{ .Values.global.jfb.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.jfb.namespace }}-clusteradmin-cluster-role-dataset
  apiGroup: rbac.authorization.k8s.io