// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sensor_types.proto

package devices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorTypes_SearchType_FullMethodName = "/devices.SensorTypes/SearchType"
	SensorTypes_CreateType_FullMethodName = "/devices.SensorTypes/CreateType"
	SensorTypes_DeleteType_FullMethodName = "/devices.SensorTypes/DeleteType"
)

// SensorTypesClient is the client API for SensorTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorTypesClient interface {
	// 센서 타입 검색
	SearchType(ctx context.Context, in *SearchTypeRequest, opts ...grpc.CallOption) (*SearchTypeResponse, error)
	// 센서 타입 생성
	CreateType(ctx context.Context, in *SensorType, opts ...grpc.CallOption) (*SensorType, error)
	// 삭제
	DeleteType(ctx context.Context, in *SensorTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sensorTypesClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorTypesClient(cc grpc.ClientConnInterface) SensorTypesClient {
	return &sensorTypesClient{cc}
}

func (c *sensorTypesClient) SearchType(ctx context.Context, in *SearchTypeRequest, opts ...grpc.CallOption) (*SearchTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTypeResponse)
	err := c.cc.Invoke(ctx, SensorTypes_SearchType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorTypesClient) CreateType(ctx context.Context, in *SensorType, opts ...grpc.CallOption) (*SensorType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorType)
	err := c.cc.Invoke(ctx, SensorTypes_CreateType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorTypesClient) DeleteType(ctx context.Context, in *SensorTypeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SensorTypes_DeleteType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorTypesServer is the server API for SensorTypes service.
// All implementations must embed UnimplementedSensorTypesServer
// for forward compatibility.
type SensorTypesServer interface {
	// 센서 타입 검색
	SearchType(context.Context, *SearchTypeRequest) (*SearchTypeResponse, error)
	// 센서 타입 생성
	CreateType(context.Context, *SensorType) (*SensorType, error)
	// 삭제
	DeleteType(context.Context, *SensorTypeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSensorTypesServer()
}

// UnimplementedSensorTypesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorTypesServer struct{}

func (UnimplementedSensorTypesServer) SearchType(context.Context, *SearchTypeRequest) (*SearchTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchType not implemented")
}
func (UnimplementedSensorTypesServer) CreateType(context.Context, *SensorType) (*SensorType, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateType not implemented")
}
func (UnimplementedSensorTypesServer) DeleteType(context.Context, *SensorTypeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteType not implemented")
}
func (UnimplementedSensorTypesServer) mustEmbedUnimplementedSensorTypesServer() {}
func (UnimplementedSensorTypesServer) testEmbeddedByValue()                     {}

// UnsafeSensorTypesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorTypesServer will
// result in compilation errors.
type UnsafeSensorTypesServer interface {
	mustEmbedUnimplementedSensorTypesServer()
}

func RegisterSensorTypesServer(s grpc.ServiceRegistrar, srv SensorTypesServer) {
	// If the following call panics, it indicates UnimplementedSensorTypesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorTypes_ServiceDesc, srv)
}

func _SensorTypes_SearchType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorTypesServer).SearchType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorTypes_SearchType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorTypesServer).SearchType(ctx, req.(*SearchTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorTypes_CreateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorTypesServer).CreateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorTypes_CreateType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorTypesServer).CreateType(ctx, req.(*SensorType))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorTypes_DeleteType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorTypesServer).DeleteType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorTypes_DeleteType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorTypesServer).DeleteType(ctx, req.(*SensorTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorTypes_ServiceDesc is the grpc.ServiceDesc for SensorTypes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorTypes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devices.SensorTypes",
	HandlerType: (*SensorTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchType",
			Handler:    _SensorTypes_SearchType_Handler,
		},
		{
			MethodName: "CreateType",
			Handler:    _SensorTypes_CreateType_Handler,
		},
		{
			MethodName: "DeleteType",
			Handler:    _SensorTypes_DeleteType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sensor_types.proto",
}
