# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\" \n\x10\x44iskUsageRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1f\n\x0e\x44iskUsageReply\x12\r\n\x05usage\x18\x01 \x01(\t2F\n\x0eStorageService\x12\x34\n\x0cGetDiskUsage\x12\x11.DiskUsageRequest\x1a\x0f.DiskUsageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISKUSAGEREQUEST']._serialized_start=17
  _globals['_DISKUSAGEREQUEST']._serialized_end=49
  _globals['_DISKUSAGEREPLY']._serialized_start=51
  _globals['_DISKUSAGEREPLY']._serialized_end=82
  _globals['_STORAGESERVICE']._serialized_start=84
  _globals['_STORAGESERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
