apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  .filebrowser.json: |-
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "/srv",
      "noauth": "noauth"
    }
