apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}-pod
  labels:
    tool_type: "filebrowser"
    dataset_id: "{{ .Values.dataset_id }}"
    ingress_path: "{{ .Values.ingress_path }}"
spec:
  containers:
  - name: filebrowser
    image: {{ .Values.registry }}jfb-system/filebrowser:0.1.0
    ports:
    - containerPort: 80
    env:
      - name: FB_NOAUTH
        value: "noauth"
      - name: FB_BASEURL
        value: /{{ .Values.ingress_path }}
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "500m" # 0.5 CPU core
        memory: "512Mi" # 512 MiB
    volumeMounts:
    # - name: config-volume
    #   mountPath: "/tmp"
    #   subPath: ".filebrowser.json"
    - name: data-pvc
      mountPath: "/srv"
      subPath: "{{ .Values.dataset_path }}"
  volumes:
  - name: config-volume
    configMap:
      name: {{ .Values.name }}-config
  - name: data-pvc
    persistentVolumeClaim:
      claimName: {{ .Values.dataset_pvc_name }}
