apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-storage-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-exporter
  template:
    metadata:
      labels:
        app: storage-exporter
    spec:
      containers:
      - name: storage-exporter
        image: {{ .Values.registry }}jfb-system/storage-exporter:0.1.4
        command: ["sh", "-c", "python3 /app/storage-metric.py"]
        # args: [] # while true; do sleep 30; done; python3 /app/storage-metric.py
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: jfb-settings
        volumeMounts:
        - name: jf-src
          mountPath: /app
          subPath: src/storage
        - name: jf-utils
          mountPath: /utils
        - name: nfs-data
          mountPath: /jf-data
      volumes:
      - name: jf-src
        persistentVolumeClaim:
          claimName: jf-src-resource-pvc
      - name: jf-utils
        persistentVolumeClaim:
          claimName: jf-src-utils-pvc
      - name: nfs-data
        nfs:
          server: {{ .Values.server }}
          path: {{ .Values.mountpoint }}

