// Code generated by protoc-gen-go-pg.
package server

import (
	"github.com/go-pg/pg/v10/orm"
	"gitlab.suredatalab.kr/sdlmicro/middleware/log"
	"gitlab.suredatalab.kr/sdlmicro/middleware/pgorm"

	"gitlab.suredatalab.kr/beymons/facilities"
)

var ormModels = []interface{}{
	(*facilities.Facility)(nil),
	(*facilities.FacilityAttribute)(nil),
	(*facilities.FacilityDevice)(nil),
	(*facilities.FacilityHistory)(nil),
	(*facilities.FacilityUpdateHistory)(nil),
	(*facilities.FacilityStatusHistory)(nil),
	(*facilities.FacilityControl)(nil),
	(*facilities.FacilityCommandHistory)(nil),
	(*facilities.Product)(nil),
	(*facilities.ProductAttribute)(nil),
	(*facilities.ProductHistory)(nil),
	(*facilities.ProductUpdateHistory)(nil),
	(*facilities.ProductControl)(nil),
}

// 테이블 생성 함수
func createScheme() {
	if _, err := pgorm.ConnectDB(); err != nil {
		log.Fatal("DB connection failed", "error", err)
	}

	// DB Connection
	conn := pgorm.Conn()
	defer conn.Close()

	// Create tables
	for _, model := range ormModels {
		if err := conn.Model(model).
			CreateTable(&orm.CreateTableOptions{
				IfNotExists:   true,
				FKConstraints: true,
			}); err != nil {
			log.Fatal("Failed to create table", "error", err)
		}
	}

	queries := []string{
		"CREATE INDEX IF NOT EXISTS facilities_facility_name_site_id_idx ON facilities USING BTREE (\"facility_name\" ASC NULLS FIRST, \"site_id\" ASC NULLS FIRST) ",
		"CREATE UNIQUE INDEX IF NOT EXISTS facility_attributes_facility_id_attribute_key ON facility_attributes USING BTREE (\"facility_id\" ASC NULLS FIRST, \"attribute\" ASC NULLS FIRST) ",
		"SELECT create_hypertable('facility_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('facility_histories', 'site_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('facility_update_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('facility_update_histories', 'site_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('facility_status_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('facility_status_histories', 'site_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('facility_command_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"CREATE UNIQUE INDEX IF NOT EXISTS product_attributes_manufacture_id_model_number_attribute_key ON product_attributes USING BTREE (\"manufacture_id\" ASC NULLS FIRST, \"model_number\" ASC NULLS FIRST, \"attribute\" ASC NULLS FIRST) ",
		"SELECT create_hypertable('product_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('product_histories', 'manufacture_id', number_partitions => 10, if_not_exists => true)",
		"SELECT create_hypertable('product_update_histories', 'created_at', chunk_time_interval => INTERVAL '1 week', if_not_exists => true)",
		"SELECT add_dimension('product_update_histories', 'manufacture_id', number_partitions => 10, if_not_exists => true)",
		"CREATE UNIQUE INDEX IF NOT EXISTS product_controls_manufacture_id_model_number_control_name_modbus_key ON product_controls USING BTREE (\"manufacture_id\" ASC NULLS FIRST, \"model_number\" ASC NULLS FIRST, \"control_name\" ASC NULLS FIRST, \"modbus\" ASC NULLS FIRST) ",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facilities' AND constraint_name = 'facilities_site_id_group_id_fkey'\n    ) THEN\n        ALTER TABLE facilities ADD CONSTRAINT facilities_site_id_group_id_fkey FOREIGN KEY (site_id, group_id) REFERENCES groups (site_id, group_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facilities' AND constraint_name = 'facilities_manufacture_id_model_number_fk'\n    ) THEN\n        ALTER TABLE facilities ADD CONSTRAINT facilities_manufacture_id_model_number_fk FOREIGN KEY (manufacture_id, model_number) REFERENCES products (manufacture_id, model_number) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_attributes' AND constraint_name = 'facility_attributes_facility_id_fk'\n    ) THEN\n        ALTER TABLE facility_attributes ADD CONSTRAINT facility_attributes_facility_id_fk FOREIGN KEY (facility_id) REFERENCES facilities (facility_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_devices' AND constraint_name = 'facility_devices_facility_id_fkey'\n    ) THEN\n        ALTER TABLE facility_devices ADD CONSTRAINT facility_devices_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES facilities (facility_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_devices' AND constraint_name = 'facility_devices_site_id_device_id_fkey'\n    ) THEN\n        ALTER TABLE facility_devices ADD CONSTRAINT facility_devices_site_id_device_id_fkey FOREIGN KEY (site_id, device_id) REFERENCES site_devices (site_id, device_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_controls' AND constraint_name = 'facility_controls_facility_id_fkey'\n    ) THEN\n        ALTER TABLE facility_controls ADD CONSTRAINT facility_controls_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES facilities (facility_id) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_controls' AND constraint_name = 'facility_controls_device_id_fkey'\n    ) THEN\n        ALTER TABLE facility_controls ADD CONSTRAINT facility_controls_device_id_fkey FOREIGN KEY (device_id) REFERENCES devices (device_id) ON DELETE SET NULL;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_controls' AND constraint_name = 'facility_controls_p_control_id_fkey'\n    ) THEN\n        ALTER TABLE facility_controls ADD CONSTRAINT facility_controls_p_control_id_fkey FOREIGN KEY (p_control_id) REFERENCES product_controls (control_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'facility_controls' AND constraint_name = 'facility_controls_sensor_type_fkey'\n    ) THEN\n        ALTER TABLE facility_controls ADD CONSTRAINT facility_controls_sensor_type_fkey FOREIGN KEY (sensor_type) REFERENCES sensor_types (type_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'products' AND constraint_name = 'products_manufacture_id_fk'\n    ) THEN\n        ALTER TABLE products ADD CONSTRAINT products_manufacture_id_fk FOREIGN KEY (manufacture_id) REFERENCES sites (site_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'product_attributes' AND constraint_name = 'product_attributes_manufacture_id_model_number_fk'\n    ) THEN\n        ALTER TABLE product_attributes ADD CONSTRAINT product_attributes_manufacture_id_model_number_fk FOREIGN KEY (manufacture_id, model_number) REFERENCES products (manufacture_id, model_number) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'product_controls' AND constraint_name = 'product_controls_manufacture_id_model_number_fkey'\n    ) THEN\n        ALTER TABLE product_controls ADD CONSTRAINT product_controls_manufacture_id_model_number_fkey FOREIGN KEY (manufacture_id, model_number) REFERENCES products (manufacture_id, model_number) ON DELETE CASCADE;\n    END IF;\nEND;\n$$;",
		"DO $$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.table_constraints\n        JOIN information_schema.key_column_usage USING (table_name, constraint_name, table_schema)\n        WHERE constraint_type = 'FOREIGN KEY'\n        AND table_schema = current_schema()\n        AND table_name = 'product_controls' AND constraint_name = 'product_controls_sensor_type_fkey'\n    ) THEN\n        ALTER TABLE product_controls ADD CONSTRAINT product_controls_sensor_type_fkey FOREIGN KEY (sensor_type) REFERENCES sensor_types (type_id) ON DELETE RESTRICT;\n    END IF;\nEND;\n$$;",
	}

	for i, query := range queries {
		if _, err := conn.Exec(query); err != nil {
			log.Fatalf("Failed to exec[%d]: %s", i, err.Error())
		}
	}
}

// 생성된 테이블 삭제 함수
func deleteScheme() error {
	// DB 연결
	if _, err := pgorm.ConnectDB(); err != nil {
		return err
	}

	// DB Connection
	conn := pgorm.Conn()
	defer conn.Close()

	// 모델 제거
	for _, model := range ormModels {
		if err := conn.Model(model).DropTable(&orm.DropTableOptions{IfExists: true, Cascade: true}); err != nil {
			return err
		}
	}

	return nil
}
