// Code generated by protoc-gen-sdlmicro.
package server

import (
	sdlmicro "gitlab.suredatalab.kr/sdlmicro/middleware"
	"gitlab.suredatalab.kr/sdlmicro/middleware/async"
	"gitlab.suredatalab.kr/sdlmicro/middleware/log"
	"gitlab.suredatalab.kr/sdlmicro/middleware/pgorm"
	"google.golang.org/grpc"

	"gitlab.suredatalab.kr/beymons/facilities"
)

const PRODUCT_NAME = "products"

// FacilitiesServer - gRPC 서버
type FacilitiesServer struct {
	facilities.FacilitiesServer
	facilities.ProductsServer
}

// Init - 서비스 초기화
func (s *FacilitiesServer) Init() {
	createScheme()

	// DB Connection
	conn := pgorm.Conn()
	defer conn.Close()

	// 체크 제약조건 추가
	if _, err := conn.Exec(checkProductDocumentationQuery, PRODUCT_NAME); err != nil {
		log.Error("Failed to checkProductDocumentationQuery", "error", err)
	}
	if _, err := conn.Exec(checkFacilityDocumentationQuery, facilities.PACKAGE_NAME); err != nil {
		log.Error("Failed to checkFacilityDocumentationQuery", "error", err)
	}

	// 인덱스 추가
	for _, query := range []string{
		"CREATE UNIQUE INDEX facility_devices_device_id_key ON facility_devices (device_id) WHERE modbus IS NULL AND channel IS NULL",
		"CREATE UNIQUE INDEX facility_devices_device_id_modbus_key ON facility_devices (device_id, modbus) WHERE channel IS NULL",
		"CREATE UNIQUE INDEX facility_devices_device_id_modbus_channel_key ON facility_devices (device_id, modbus, channel) WHERE modbus IS NOT NULL AND channel IS NOT NULL",
		"CREATE OR REPLACE VIEW view_facility_devices AS SELECT site_id, facility_id, device_id FROM facility_devices GROUP BY site_id, facility_id, device_id",
	} {
		if _, err := conn.Exec(query); err != nil {
			log.Warnf("Failed to create view: %v", err)
		}
	}

	// 권한 생성
	if err := Register(); err != nil {
		log.Error(err.Error())
	}

	// 이벤트 기록을 위한 스트림 생성
	if _, err := async.CreateStream(facilities.PACKAGE_NAME, 0); err != nil {
		log.Error("Failed to create stream", "error", err)
	}
}

// Prune 함수는 서비스 권한과 생성된 테이블을 삭제한다.
func Prune() error {
	if err := deleteScheme(); err != nil {
		log.Error(err.Error())
	}

	// 권한 제거
	if err := Deregister(); err != nil {
		log.Error(err.Error())
	}

	return nil
}

// TestServer
func TestServer() string {
	sdlmicro.Name(facilities.PACKAGE_NAME)
	srv := FacilitiesServer{}
	srv.Init()
	addr, serve := sdlmicro.NewTestServer(func(g *grpc.Server) {
		facilities.RegisterFacilitiesServer(g, srv)
		facilities.RegisterProductsServer(g, srv)
	})
	go serve()
	return addr
}
