apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "name" . }}-ws-job"
  namespace: {{ include "namespace" . }}
  labels:
  annotations:
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ include "name" . }}-ws-job
        image: {{ printf "%s/busybox:latest" ( .Values.system.registry | trimSuffix "/") }}
        resources:
          limits:
            cpu : 1
            memory : "1Gi"
        command: [ "/bin/sh", "-c"]
        {{/*storageclass에서 생성되는 폴더 하위에 만들어짐
        /jf-ws/{{ .Values.workspace.name }}/deployments 이런식으로 하면
        생성되는폴더/workspace.name 구조로 폴더 생성*/}}
        args: ["mkdir -p \
        /jf-ws/projects \
        /jf-ws/deployments \
        /jf-dataset/0 \
        /jf-dataset/1;"]
        volumeMounts:
        - name: jf-ws
          mountPath: /jf-ws
        - name: jf-dataset
          mountPath: /jf-dataset
      volumes:
      - name: jf-ws
        persistentVolumeClaim:
          claimName: "{{ include "name" . }}-main-pvc"
      - name: jf-dataset
        persistentVolumeClaim:
          claimName: "{{ include "name" . }}-data-pvc"
