apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "name" . }}-bin-pvc"
  namespace: {{ include "namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "name" . }}-bin-pv"
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: "{{ include "name" . }}-bin-pvc"
    namespace: {{ include "namespace" . }}
  {{- include "volume.type" .Values.volume.jfBin | nindent 2 }}