// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// source: facilities.proto
// source: facilities_doc.proto
// source: products.proto

package server

import "gitlab.suredatalab.kr/sdlmicro/middleware/auth"

func Register() error {
	if err := auth.Register(&auth.RegisterRequest{
		ServiceName: "facilities",
		Resources: map[string]string{
			"create-facility":   "설비 생성 권한",
			"create-product":    "제품 생성 권한",
			"facility-admin":    "설비/제품 관리자",
			"manage-facilities": "설비 관리 권한",
			"manage-products":   "제품 관리 권한",
			"query-facilities":  "설비 검색 권한",
			"query-products":    "제품 검색 권한",
			"view-facilities":   "설비 조회 권한",
			"view-products":     "제품 조회 권한",
		},
		AdminRole: "facility-admin",
		Roles: map[string][]string{
			"/facilities.Facilities/CommandFacility": {
				"manage-facilities",
			},
			"/facilities.Facilities/Connect": {
				"manage-facilities",
			},
			"/facilities.Facilities/ControlFacility": {
				"view-facilities",
			},
			"/facilities.Facilities/CreateFacility": {
				"create-facility",
			},
			"/facilities.Facilities/DeleteControlFacility": {
				"manage-facilities",
			},
			"/facilities.Facilities/DeleteFacility": {
				"manage-facilities",
			},
			"/facilities.Facilities/Devices": {
				"view-facilities",
			},
			"/facilities.Facilities/Disconnect": {
				"manage-facilities",
			},
			"/facilities.Facilities/Facilities": {
				"view-facilities",
				"manage-facilities",
			},
			"/facilities.Facilities/FacilityHistories": {
				"view-facilities",
				"manage-facilities",
			},
			"/facilities.Facilities/ReplaceFacility": {
				"manage-facilities",
			},
			"/facilities.Facilities/SearchFacility": {
				"query-facilities",
				"manage-facilities",
			},
			"/facilities.Facilities/Sensors": {
				"view-facilities",
			},
			"/facilities.Facilities/SetControlFacility": {
				"manage-facilities",
			},
			"/facilities.Facilities/Stat": {
				"view-facilities",
			},
			"/facilities.Facilities/UpdateFacility": {
				"manage-facilities",
			},
			"/facilities.Products/ControlProduct": {
				"view-products",
				"view-facilities",
			},
			"/facilities.Products/CreateControlProduct": {
				"manage-products",
			},
			"/facilities.Products/CreateProduct": {
				"create-product",
			},
			"/facilities.Products/DeleteControlProduct": {
				"manage-products",
			},
			"/facilities.Products/DeleteProduct": {
				"manage-products",
			},
			"/facilities.Products/ProductHistories": {
				"view-products",
				"manage-products",
			},
			"/facilities.Products/Products": {
				"view-products",
				"manage-products",
			},
			"/facilities.Products/ReplaceProduct": {
				"manage-products",
			},
			"/facilities.Products/SearchProduct": {
				"query-products",
				"manage-products",
			},
			"/facilities.Products/UpdateControlProduct": {
				"manage-products",
			},
			"/facilities.Products/UpdateProduct": {
				"manage-products",
			},
		},
	}); err != nil {
		return err
	}

	return nil
}

func Deregister() error {
	if err := auth.Deregister(); err != nil {
		return err
	}

	return nil
}
