// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: facilities.proto

package facilities

import (
	context "context"
	devices "gitlab.suredatalab.kr/beymons/devices"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Facilities_SearchFacility_FullMethodName        = "/facilities.Facilities/SearchFacility"
	Facilities_CreateFacility_FullMethodName        = "/facilities.Facilities/CreateFacility"
	Facilities_Facilities_FullMethodName            = "/facilities.Facilities/Facilities"
	Facilities_FacilityHistories_FullMethodName     = "/facilities.Facilities/FacilityHistories"
	Facilities_ReplaceFacility_FullMethodName       = "/facilities.Facilities/ReplaceFacility"
	Facilities_UpdateFacility_FullMethodName        = "/facilities.Facilities/UpdateFacility"
	Facilities_CommandFacility_FullMethodName       = "/facilities.Facilities/CommandFacility"
	Facilities_DeleteFacility_FullMethodName        = "/facilities.Facilities/DeleteFacility"
	Facilities_Stat_FullMethodName                  = "/facilities.Facilities/Stat"
	Facilities_Devices_FullMethodName               = "/facilities.Facilities/Devices"
	Facilities_Connect_FullMethodName               = "/facilities.Facilities/Connect"
	Facilities_Disconnect_FullMethodName            = "/facilities.Facilities/Disconnect"
	Facilities_Sensors_FullMethodName               = "/facilities.Facilities/Sensors"
	Facilities_SetControlFacility_FullMethodName    = "/facilities.Facilities/SetControlFacility"
	Facilities_ControlFacility_FullMethodName       = "/facilities.Facilities/ControlFacility"
	Facilities_DeleteControlFacility_FullMethodName = "/facilities.Facilities/DeleteControlFacility"
)

// FacilitiesClient is the client API for Facilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FacilitiesClient interface {
	// 설비 검색
	SearchFacility(ctx context.Context, in *SearchFacilityRequest, opts ...grpc.CallOption) (*SearchFacilityResponse, error)
	// 설비 등록
	CreateFacility(ctx context.Context, in *Facility, opts ...grpc.CallOption) (*Facility, error)
	// 설비 정보 조회
	Facilities(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*FacilityResponse, error)
	// 설비 이력 조회
	FacilityHistories(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*FacilityHistoryResponse, error)
	// 설비 정보 수정
	ReplaceFacility(ctx context.Context, in *Facility, opts ...grpc.CallOption) (*Facility, error)
	// 사용자화 메타데이터 수정
	UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*Facility, error)
	// 설비 명령 전송
	CommandFacility(ctx context.Context, in *CommandFacilityRequest, opts ...grpc.CallOption) (*CommandFacilityResponse, error)
	// 설비 삭제
	DeleteFacility(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 설비의 현재 상태(온/습도) 조회
	Stat(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// 설비에 연결된 장치 조회
	Devices(ctx context.Context, in *devices.SearchRequest, opts ...grpc.CallOption) (*devices.SearchResponse, error)
	// 설비에 장치 연결
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*SensorsReponse, error)
	// 설비에 연결된 장치 해제
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 설비에 연결된 센서 조회
	Sensors(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*SensorsReponse, error)
	// 설비 제어 설정
	SetControlFacility(ctx context.Context, in *SetControlFacilityRequest, opts ...grpc.CallOption) (*FacilityControl, error)
	// 설비 제어 설정 조회
	//
	// controlId가 없는 경우 아직 설비 제어 설정이 안된 경우로
	// PUT /facilities/{facility_id}/controls API를 호출하여 설정해야 한다.
	ControlFacility(ctx context.Context, in *ControlFacilityRequest, opts ...grpc.CallOption) (*ControlFacilityResponse, error)
	// 설비 제어 설정 삭제
	DeleteControlFacility(ctx context.Context, in *ControlFacilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type facilitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewFacilitiesClient(cc grpc.ClientConnInterface) FacilitiesClient {
	return &facilitiesClient{cc}
}

func (c *facilitiesClient) SearchFacility(ctx context.Context, in *SearchFacilityRequest, opts ...grpc.CallOption) (*SearchFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFacilityResponse)
	err := c.cc.Invoke(ctx, Facilities_SearchFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) CreateFacility(ctx context.Context, in *Facility, opts ...grpc.CallOption) (*Facility, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Facility)
	err := c.cc.Invoke(ctx, Facilities_CreateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Facilities(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*FacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FacilityResponse)
	err := c.cc.Invoke(ctx, Facilities_Facilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) FacilityHistories(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*FacilityHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FacilityHistoryResponse)
	err := c.cc.Invoke(ctx, Facilities_FacilityHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) ReplaceFacility(ctx context.Context, in *Facility, opts ...grpc.CallOption) (*Facility, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Facility)
	err := c.cc.Invoke(ctx, Facilities_ReplaceFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*Facility, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Facility)
	err := c.cc.Invoke(ctx, Facilities_UpdateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) CommandFacility(ctx context.Context, in *CommandFacilityRequest, opts ...grpc.CallOption) (*CommandFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandFacilityResponse)
	err := c.cc.Invoke(ctx, Facilities_CommandFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) DeleteFacility(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Facilities_DeleteFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Stat(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, Facilities_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Devices(ctx context.Context, in *devices.SearchRequest, opts ...grpc.CallOption) (*devices.SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(devices.SearchResponse)
	err := c.cc.Invoke(ctx, Facilities_Devices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*SensorsReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorsReponse)
	err := c.cc.Invoke(ctx, Facilities_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Facilities_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) Sensors(ctx context.Context, in *FacilityRequest, opts ...grpc.CallOption) (*SensorsReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorsReponse)
	err := c.cc.Invoke(ctx, Facilities_Sensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) SetControlFacility(ctx context.Context, in *SetControlFacilityRequest, opts ...grpc.CallOption) (*FacilityControl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FacilityControl)
	err := c.cc.Invoke(ctx, Facilities_SetControlFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) ControlFacility(ctx context.Context, in *ControlFacilityRequest, opts ...grpc.CallOption) (*ControlFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlFacilityResponse)
	err := c.cc.Invoke(ctx, Facilities_ControlFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesClient) DeleteControlFacility(ctx context.Context, in *ControlFacilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Facilities_DeleteControlFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilitiesServer is the server API for Facilities service.
// All implementations must embed UnimplementedFacilitiesServer
// for forward compatibility.
type FacilitiesServer interface {
	// 설비 검색
	SearchFacility(context.Context, *SearchFacilityRequest) (*SearchFacilityResponse, error)
	// 설비 등록
	CreateFacility(context.Context, *Facility) (*Facility, error)
	// 설비 정보 조회
	Facilities(context.Context, *FacilityRequest) (*FacilityResponse, error)
	// 설비 이력 조회
	FacilityHistories(context.Context, *FacilityRequest) (*FacilityHistoryResponse, error)
	// 설비 정보 수정
	ReplaceFacility(context.Context, *Facility) (*Facility, error)
	// 사용자화 메타데이터 수정
	UpdateFacility(context.Context, *UpdateFacilityRequest) (*Facility, error)
	// 설비 명령 전송
	CommandFacility(context.Context, *CommandFacilityRequest) (*CommandFacilityResponse, error)
	// 설비 삭제
	DeleteFacility(context.Context, *FacilityRequest) (*emptypb.Empty, error)
	// 설비의 현재 상태(온/습도) 조회
	Stat(context.Context, *FacilityRequest) (*StatResponse, error)
	// 설비에 연결된 장치 조회
	Devices(context.Context, *devices.SearchRequest) (*devices.SearchResponse, error)
	// 설비에 장치 연결
	Connect(context.Context, *ConnectRequest) (*SensorsReponse, error)
	// 설비에 연결된 장치 해제
	Disconnect(context.Context, *DisconnectRequest) (*emptypb.Empty, error)
	// 설비에 연결된 센서 조회
	Sensors(context.Context, *FacilityRequest) (*SensorsReponse, error)
	// 설비 제어 설정
	SetControlFacility(context.Context, *SetControlFacilityRequest) (*FacilityControl, error)
	// 설비 제어 설정 조회
	//
	// controlId가 없는 경우 아직 설비 제어 설정이 안된 경우로
	// PUT /facilities/{facility_id}/controls API를 호출하여 설정해야 한다.
	ControlFacility(context.Context, *ControlFacilityRequest) (*ControlFacilityResponse, error)
	// 설비 제어 설정 삭제
	DeleteControlFacility(context.Context, *ControlFacilityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFacilitiesServer()
}

// UnimplementedFacilitiesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFacilitiesServer struct{}

func (UnimplementedFacilitiesServer) SearchFacility(context.Context, *SearchFacilityRequest) (*SearchFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFacility not implemented")
}
func (UnimplementedFacilitiesServer) CreateFacility(context.Context, *Facility) (*Facility, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacility not implemented")
}
func (UnimplementedFacilitiesServer) Facilities(context.Context, *FacilityRequest) (*FacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Facilities not implemented")
}
func (UnimplementedFacilitiesServer) FacilityHistories(context.Context, *FacilityRequest) (*FacilityHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FacilityHistories not implemented")
}
func (UnimplementedFacilitiesServer) ReplaceFacility(context.Context, *Facility) (*Facility, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceFacility not implemented")
}
func (UnimplementedFacilitiesServer) UpdateFacility(context.Context, *UpdateFacilityRequest) (*Facility, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFacility not implemented")
}
func (UnimplementedFacilitiesServer) CommandFacility(context.Context, *CommandFacilityRequest) (*CommandFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandFacility not implemented")
}
func (UnimplementedFacilitiesServer) DeleteFacility(context.Context, *FacilityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFacility not implemented")
}
func (UnimplementedFacilitiesServer) Stat(context.Context, *FacilityRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedFacilitiesServer) Devices(context.Context, *devices.SearchRequest) (*devices.SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Devices not implemented")
}
func (UnimplementedFacilitiesServer) Connect(context.Context, *ConnectRequest) (*SensorsReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedFacilitiesServer) Disconnect(context.Context, *DisconnectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedFacilitiesServer) Sensors(context.Context, *FacilityRequest) (*SensorsReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sensors not implemented")
}
func (UnimplementedFacilitiesServer) SetControlFacility(context.Context, *SetControlFacilityRequest) (*FacilityControl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetControlFacility not implemented")
}
func (UnimplementedFacilitiesServer) ControlFacility(context.Context, *ControlFacilityRequest) (*ControlFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlFacility not implemented")
}
func (UnimplementedFacilitiesServer) DeleteControlFacility(context.Context, *ControlFacilityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteControlFacility not implemented")
}
func (UnimplementedFacilitiesServer) mustEmbedUnimplementedFacilitiesServer() {}
func (UnimplementedFacilitiesServer) testEmbeddedByValue()                    {}

// UnsafeFacilitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacilitiesServer will
// result in compilation errors.
type UnsafeFacilitiesServer interface {
	mustEmbedUnimplementedFacilitiesServer()
}

func RegisterFacilitiesServer(s grpc.ServiceRegistrar, srv FacilitiesServer) {
	// If the following call pancis, it indicates UnimplementedFacilitiesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Facilities_ServiceDesc, srv)
}

func _Facilities_SearchFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).SearchFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_SearchFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).SearchFacility(ctx, req.(*SearchFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Facility)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_CreateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).CreateFacility(ctx, req.(*Facility))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Facilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Facilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Facilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Facilities(ctx, req.(*FacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_FacilityHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).FacilityHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_FacilityHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).FacilityHistories(ctx, req.(*FacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_ReplaceFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Facility)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).ReplaceFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_ReplaceFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).ReplaceFacility(ctx, req.(*Facility))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_UpdateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).UpdateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_UpdateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).UpdateFacility(ctx, req.(*UpdateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_CommandFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).CommandFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_CommandFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).CommandFacility(ctx, req.(*CommandFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_DeleteFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).DeleteFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_DeleteFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).DeleteFacility(ctx, req.(*FacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Stat(ctx, req.(*FacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Devices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(devices.SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Devices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Devices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Devices(ctx, req.(*devices.SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_Sensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).Sensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_Sensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).Sensors(ctx, req.(*FacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_SetControlFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetControlFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).SetControlFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_SetControlFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).SetControlFacility(ctx, req.(*SetControlFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_ControlFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).ControlFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_ControlFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).ControlFacility(ctx, req.(*ControlFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facilities_DeleteControlFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServer).DeleteControlFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facilities_DeleteControlFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServer).DeleteControlFacility(ctx, req.(*ControlFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Facilities_ServiceDesc is the grpc.ServiceDesc for Facilities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Facilities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facilities.Facilities",
	HandlerType: (*FacilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchFacility",
			Handler:    _Facilities_SearchFacility_Handler,
		},
		{
			MethodName: "CreateFacility",
			Handler:    _Facilities_CreateFacility_Handler,
		},
		{
			MethodName: "Facilities",
			Handler:    _Facilities_Facilities_Handler,
		},
		{
			MethodName: "FacilityHistories",
			Handler:    _Facilities_FacilityHistories_Handler,
		},
		{
			MethodName: "ReplaceFacility",
			Handler:    _Facilities_ReplaceFacility_Handler,
		},
		{
			MethodName: "UpdateFacility",
			Handler:    _Facilities_UpdateFacility_Handler,
		},
		{
			MethodName: "CommandFacility",
			Handler:    _Facilities_CommandFacility_Handler,
		},
		{
			MethodName: "DeleteFacility",
			Handler:    _Facilities_DeleteFacility_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Facilities_Stat_Handler,
		},
		{
			MethodName: "Devices",
			Handler:    _Facilities_Devices_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Facilities_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Facilities_Disconnect_Handler,
		},
		{
			MethodName: "Sensors",
			Handler:    _Facilities_Sensors_Handler,
		},
		{
			MethodName: "SetControlFacility",
			Handler:    _Facilities_SetControlFacility_Handler,
		},
		{
			MethodName: "ControlFacility",
			Handler:    _Facilities_ControlFacility_Handler,
		},
		{
			MethodName: "DeleteControlFacility",
			Handler:    _Facilities_DeleteControlFacility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facilities.proto",
}
