// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: products.proto

package facilities

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Products_SearchProduct_FullMethodName        = "/facilities.Products/SearchProduct"
	Products_CreateProduct_FullMethodName        = "/facilities.Products/CreateProduct"
	Products_Products_FullMethodName             = "/facilities.Products/Products"
	Products_ProductHistories_FullMethodName     = "/facilities.Products/ProductHistories"
	Products_ReplaceProduct_FullMethodName       = "/facilities.Products/ReplaceProduct"
	Products_UpdateProduct_FullMethodName        = "/facilities.Products/UpdateProduct"
	Products_DeleteProduct_FullMethodName        = "/facilities.Products/DeleteProduct"
	Products_CreateControlProduct_FullMethodName = "/facilities.Products/CreateControlProduct"
	Products_UpdateControlProduct_FullMethodName = "/facilities.Products/UpdateControlProduct"
	Products_ControlProduct_FullMethodName       = "/facilities.Products/ControlProduct"
	Products_DeleteControlProduct_FullMethodName = "/facilities.Products/DeleteControlProduct"
)

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsClient interface {
	// 제품 검색
	SearchProduct(ctx context.Context, in *SearchProductRequest, opts ...grpc.CallOption) (*SearchProductResponse, error)
	// 제품 등록
	//
	// 제조사 ID에 해당하는 사이트가 없는 경우 신규 시아트로 등록한다.
	CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	// 제품 정보 조회
	Products(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error)
	// 제품 력 조회
	ProductHistories(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductHistoryResponse, error)
	// 제품 정보 수정
	ReplaceProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	// 사용자화 메타데이터 수정
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error)
	// 제품 삭제
	DeleteProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 제품 제어 설정 추가
	CreateControlProduct(ctx context.Context, in *ProductControl, opts ...grpc.CallOption) (*ProductControl, error)
	// 제품 제어 설정 변경
	UpdateControlProduct(ctx context.Context, in *UpdateControlProductRequest, opts ...grpc.CallOption) (*ProductControl, error)
	// 제품 제어 설정 조회
	ControlProduct(ctx context.Context, in *ControlProductRequest, opts ...grpc.CallOption) (*ControlProductResponse, error)
	// 제품 제어 설정 삭제
	DeleteControlProduct(ctx context.Context, in *ControlProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) SearchProduct(ctx context.Context, in *SearchProductRequest, opts ...grpc.CallOption) (*SearchProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductResponse)
	err := c.cc.Invoke(ctx, Products_SearchProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Products_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) Products(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Products_Products_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ProductHistories(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductHistoryResponse)
	err := c.cc.Invoke(ctx, Products_ProductHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ReplaceProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Products_ReplaceProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, Products_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Products_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CreateControlProduct(ctx context.Context, in *ProductControl, opts ...grpc.CallOption) (*ProductControl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductControl)
	err := c.cc.Invoke(ctx, Products_CreateControlProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateControlProduct(ctx context.Context, in *UpdateControlProductRequest, opts ...grpc.CallOption) (*ProductControl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductControl)
	err := c.cc.Invoke(ctx, Products_UpdateControlProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ControlProduct(ctx context.Context, in *ControlProductRequest, opts ...grpc.CallOption) (*ControlProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlProductResponse)
	err := c.cc.Invoke(ctx, Products_ControlProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteControlProduct(ctx context.Context, in *ControlProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Products_DeleteControlProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
// All implementations must embed UnimplementedProductsServer
// for forward compatibility.
type ProductsServer interface {
	// 제품 검색
	SearchProduct(context.Context, *SearchProductRequest) (*SearchProductResponse, error)
	// 제품 등록
	//
	// 제조사 ID에 해당하는 사이트가 없는 경우 신규 시아트로 등록한다.
	CreateProduct(context.Context, *Product) (*Product, error)
	// 제품 정보 조회
	Products(context.Context, *ProductRequest) (*Product, error)
	// 제품 력 조회
	ProductHistories(context.Context, *ProductRequest) (*ProductHistoryResponse, error)
	// 제품 정보 수정
	ReplaceProduct(context.Context, *Product) (*Product, error)
	// 사용자화 메타데이터 수정
	UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error)
	// 제품 삭제
	DeleteProduct(context.Context, *ProductRequest) (*emptypb.Empty, error)
	// 제품 제어 설정 추가
	CreateControlProduct(context.Context, *ProductControl) (*ProductControl, error)
	// 제품 제어 설정 변경
	UpdateControlProduct(context.Context, *UpdateControlProductRequest) (*ProductControl, error)
	// 제품 제어 설정 조회
	ControlProduct(context.Context, *ControlProductRequest) (*ControlProductResponse, error)
	// 제품 제어 설정 삭제
	DeleteControlProduct(context.Context, *ControlProductRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProductsServer()
}

// UnimplementedProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductsServer struct{}

func (UnimplementedProductsServer) SearchProduct(context.Context, *SearchProductRequest) (*SearchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProduct not implemented")
}
func (UnimplementedProductsServer) CreateProduct(context.Context, *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductsServer) Products(context.Context, *ProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Products not implemented")
}
func (UnimplementedProductsServer) ProductHistories(context.Context, *ProductRequest) (*ProductHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductHistories not implemented")
}
func (UnimplementedProductsServer) ReplaceProduct(context.Context, *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceProduct not implemented")
}
func (UnimplementedProductsServer) UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductsServer) DeleteProduct(context.Context, *ProductRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductsServer) CreateControlProduct(context.Context, *ProductControl) (*ProductControl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateControlProduct not implemented")
}
func (UnimplementedProductsServer) UpdateControlProduct(context.Context, *UpdateControlProductRequest) (*ProductControl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateControlProduct not implemented")
}
func (UnimplementedProductsServer) ControlProduct(context.Context, *ControlProductRequest) (*ControlProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlProduct not implemented")
}
func (UnimplementedProductsServer) DeleteControlProduct(context.Context, *ControlProductRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteControlProduct not implemented")
}
func (UnimplementedProductsServer) mustEmbedUnimplementedProductsServer() {}
func (UnimplementedProductsServer) testEmbeddedByValue()                  {}

// UnsafeProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServer will
// result in compilation errors.
type UnsafeProductsServer interface {
	mustEmbedUnimplementedProductsServer()
}

func RegisterProductsServer(s grpc.ServiceRegistrar, srv ProductsServer) {
	// If the following call pancis, it indicates UnimplementedProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Products_ServiceDesc, srv)
}

func _Products_SearchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).SearchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_SearchProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).SearchProduct(ctx, req.(*SearchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_Products_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).Products(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_Products_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).Products(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ProductHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ProductHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ProductHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ProductHistories(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ReplaceProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ReplaceProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ReplaceProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ReplaceProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CreateControlProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductControl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateControlProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreateControlProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateControlProduct(ctx, req.(*ProductControl))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateControlProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateControlProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateControlProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_UpdateControlProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateControlProduct(ctx, req.(*UpdateControlProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ControlProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ControlProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ControlProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ControlProduct(ctx, req.(*ControlProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteControlProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteControlProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeleteControlProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteControlProduct(ctx, req.(*ControlProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Products_ServiceDesc is the grpc.ServiceDesc for Products service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Products_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facilities.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProduct",
			Handler:    _Products_SearchProduct_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _Products_CreateProduct_Handler,
		},
		{
			MethodName: "Products",
			Handler:    _Products_Products_Handler,
		},
		{
			MethodName: "ProductHistories",
			Handler:    _Products_ProductHistories_Handler,
		},
		{
			MethodName: "ReplaceProduct",
			Handler:    _Products_ReplaceProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _Products_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _Products_DeleteProduct_Handler,
		},
		{
			MethodName: "CreateControlProduct",
			Handler:    _Products_CreateControlProduct_Handler,
		},
		{
			MethodName: "UpdateControlProduct",
			Handler:    _Products_UpdateControlProduct_Handler,
		},
		{
			MethodName: "ControlProduct",
			Handler:    _Products_ControlProduct_Handler,
		},
		{
			MethodName: "DeleteControlProduct",
			Handler:    _Products_DeleteControlProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}
