// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: products.proto

package facilities

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "gitlab.suredatalab.kr/sdlmicro/middleware/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 정렬 옵션
type SearchProductRequest_Order int32

const (
	// 제조사 ID (오름차순)
	SearchProductRequest_manufacture_id_asc SearchProductRequest_Order = 0
	// 제조사 ID (내림차순)
	SearchProductRequest_manufacture_id_desc SearchProductRequest_Order = 1
	// 제조사 이름 (오름차순)
	SearchProductRequest_manufacture_name_asc SearchProductRequest_Order = 2
	// 제조사 이름 (내림차순)
	SearchProductRequest_manufacture_name_desc SearchProductRequest_Order = 3
	// 모델 번호 (오름차순)
	SearchProductRequest_model_number_asc SearchProductRequest_Order = 4
	// 모델 번호 (내림차순)
	SearchProductRequest_model_number_desc SearchProductRequest_Order = 5
	// 제품명 (오름차순)
	SearchProductRequest_product_name_asc SearchProductRequest_Order = 6
	// 제품명 (내림차순)
	SearchProductRequest_product_name_desc SearchProductRequest_Order = 7
)

// Enum value maps for SearchProductRequest_Order.
var (
	SearchProductRequest_Order_name = map[int32]string{
		0: "manufacture_id_asc",
		1: "manufacture_id_desc",
		2: "manufacture_name_asc",
		3: "manufacture_name_desc",
		4: "model_number_asc",
		5: "model_number_desc",
		6: "product_name_asc",
		7: "product_name_desc",
	}
	SearchProductRequest_Order_value = map[string]int32{
		"manufacture_id_asc":    0,
		"manufacture_id_desc":   1,
		"manufacture_name_asc":  2,
		"manufacture_name_desc": 3,
		"model_number_asc":      4,
		"model_number_desc":     5,
		"product_name_asc":      6,
		"product_name_desc":     7,
	}
)

func (x SearchProductRequest_Order) Enum() *SearchProductRequest_Order {
	p := new(SearchProductRequest_Order)
	*p = x
	return p
}

func (x SearchProductRequest_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchProductRequest_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_products_proto_enumTypes[0].Descriptor()
}

func (SearchProductRequest_Order) Type() protoreflect.EnumType {
	return &file_products_proto_enumTypes[0]
}

func (x SearchProductRequest_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchProductRequest_Order.Descriptor instead.
func (SearchProductRequest_Order) EnumDescriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1, 0}
}

type ProductHistory_Kind int32

const (
	// 제품 등록
	ProductHistory_CREATED ProductHistory_Kind = 0
	// 제품 정보 수정
	ProductHistory_UPDATED ProductHistory_Kind = 1
	// 제품 삭제
	ProductHistory_DELETED ProductHistory_Kind = 2
)

// Enum value maps for ProductHistory_Kind.
var (
	ProductHistory_Kind_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
	}
	ProductHistory_Kind_value = map[string]int32{
		"CREATED": 0,
		"UPDATED": 1,
		"DELETED": 2,
	}
)

func (x ProductHistory_Kind) Enum() *ProductHistory_Kind {
	p := new(ProductHistory_Kind)
	*p = x
	return p
}

func (x ProductHistory_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductHistory_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_products_proto_enumTypes[1].Descriptor()
}

func (ProductHistory_Kind) Type() protoreflect.EnumType {
	return &file_products_proto_enumTypes[1]
}

func (x ProductHistory_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductHistory_Kind.Descriptor instead.
func (ProductHistory_Kind) EnumDescriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{12, 0}
}

type ProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 모델 번호
	ModelNumber   string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

func (x *ProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ProductRequest) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

type SearchProductRequest struct {
	state protoimpl.MessageState       `protogen:"open.v1"`
	Order []SearchProductRequest_Order `protobuf:"varint,1,rep,packed,name=order,proto3,enum=facilities.SearchProductRequest_Order" json:"order,omitempty"`
	// 응답으로 보내줄 레코드 수.
	// 지정하지 않거나 0인 경우 전체 레코드를 조회하지만,
	// 응답이 15초 이상 소요되는 경우 타임아웃 오류가 발생된다.
	Limit uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// 페이지에서 표시되는 첫 레코드의 인덱스 (Default: 0)
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// 전체 검색
	//
	// 검색 대상:
	// - 제품명
	// - 제조사명
	// - 제조사 ID (전방일치)
	// - 모델 번호 (전방일치)
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// 제조사 ID로 필터링
	ManufactureId string `protobuf:"bytes,5,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 제조사 이름으로 검색
	ManufactureName string `protobuf:"bytes,6,opt,name=manufacture_name,json=manufactureName,proto3" json:"manufacture_name,omitempty"`
	// 모델 번호
	Model string `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	// 제품명으로 검색
	Name          string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductRequest) Reset() {
	*x = SearchProductRequest{}
	mi := &file_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductRequest) ProtoMessage() {}

func (x *SearchProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductRequest.ProtoReflect.Descriptor instead.
func (*SearchProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductRequest) GetOrder() []SearchProductRequest_Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SearchProductRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProductRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *SearchProductRequest) GetManufactureName() string {
	if x != nil {
		return x.ManufactureName
	}
	return ""
}

func (x *SearchProductRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SearchProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchProductResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entities []*Product             `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// 데이터의 총건수
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 관련 링크 (HATEOAS)
	Link          map[string]string `protobuf:"bytes,3,rep,name=link,proto3" json:"link,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductResponse) Reset() {
	*x = SearchProductResponse{}
	mi := &file_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductResponse) ProtoMessage() {}

func (x *SearchProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductResponse.ProtoReflect.Descriptor instead.
func (*SearchProductResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

func (x *SearchProductResponse) GetEntities() []*Product {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchProductResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchProductResponse) GetLink() map[string]string {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpdateProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 모델 번호
	ModelNumber   string            `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty"`
	Payload       map[string]string `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *UpdateProductRequest) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *UpdateProductRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProductHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 관리 이력
	Histories     []*ProductHistory `protobuf:"bytes,2,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductHistoryResponse) Reset() {
	*x = ProductHistoryResponse{}
	mi := &file_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductHistoryResponse) ProtoMessage() {}

func (x *ProductHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductHistoryResponse.ProtoReflect.Descriptor instead.
func (*ProductHistoryResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{4}
}

func (x *ProductHistoryResponse) GetHistories() []*ProductHistory {
	if x != nil {
		return x.Histories
	}
	return nil
}

type CommandProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandProductRequest_Delete
	Command       isCommandProductRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandProductRequest) Reset() {
	*x = CommandProductRequest{}
	mi := &file_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandProductRequest) ProtoMessage() {}

func (x *CommandProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandProductRequest.ProtoReflect.Descriptor instead.
func (*CommandProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{5}
}

func (x *CommandProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *CommandProductRequest) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *CommandProductRequest) GetCommand() isCommandProductRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandProductRequest) GetDelete() bool {
	if x != nil {
		if x, ok := x.Command.(*CommandProductRequest_Delete); ok {
			return x.Delete
		}
	}
	return false
}

type isCommandProductRequest_Command interface {
	isCommandProductRequest_Command()
}

type CommandProductRequest_Delete struct {
	// 삭제 명령
	Delete bool `protobuf:"varint,3,opt,name=delete,proto3,oneof"`
}

func (*CommandProductRequest_Delete) isCommandProductRequest_Command() {}

type CommandProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 명령이 적용된 리소스 수
	Count         uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandProductResponse) Reset() {
	*x = CommandProductResponse{}
	mi := &file_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandProductResponse) ProtoMessage() {}

func (x *CommandProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandProductResponse.ProtoReflect.Descriptor instead.
func (*CommandProductResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{6}
}

func (x *CommandProductResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateControlProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty"`
	// 제어 설정 ID
	ControlId string `protobuf:"bytes,3,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	// 센서 타입
	SensorType string `protobuf:"bytes,4,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	// 명령어
	Command string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	// 제어 명령
	//
	// go template 문법을 사용하며 제어 명령에서 해당 값을 입력한다.
	Payload       string `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateControlProductRequest) Reset() {
	*x = UpdateControlProductRequest{}
	mi := &file_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateControlProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateControlProductRequest) ProtoMessage() {}

func (x *UpdateControlProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateControlProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateControlProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateControlProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *UpdateControlProductRequest) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *UpdateControlProductRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *UpdateControlProductRequest) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *UpdateControlProductRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UpdateControlProductRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ControlProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty"`
	// 제어 설정 ID
	ControlId     string `protobuf:"bytes,3,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlProductRequest) Reset() {
	*x = ControlProductRequest{}
	mi := &file_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlProductRequest) ProtoMessage() {}

func (x *ControlProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlProductRequest.ProtoReflect.Descriptor instead.
func (*ControlProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{8}
}

func (x *ControlProductRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ControlProductRequest) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *ControlProductRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

type ControlProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ProductControl      `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlProductResponse) Reset() {
	*x = ControlProductResponse{}
	mi := &file_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlProductResponse) ProtoMessage() {}

func (x *ControlProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlProductResponse.ProtoReflect.Descriptor instead.
func (*ControlProductResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{9}
}

func (x *ControlProductResponse) GetEntities() []*ProductControl {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Product
//
// 설비에 대한 제품 정보를 관리
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty" pg:",type:varchar(50),notnull,pk"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty" pg:",type:varchar(100),notnull,pk"`
	// 제조사 정보
	Manufacture *structpb.Struct `protobuf:"bytes,3,opt,name=manufacture,proto3" json:"manufacture,omitempty" pg:"-"`
	// 제품명
	ProductName string `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty" pg:",type:varchar(200)"`
	// 제품 출시 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// 사용자화 메타데이터
	Attributes map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" pg:"-"`
	// 리소스에 대한 변경 권한 여부
	Writable      bool `protobuf:"varint,7,opt,name=writable,proto3" json:"writable,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{10}
}

func (x *Product) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *Product) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *Product) GetManufacture() *structpb.Struct {
	if x != nil {
		return x.Manufacture
	}
	return nil
}

func (x *Product) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

// ProductAttribute
//
// 제품에 대한 추가 정보를 관리한다.
type ProductAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,1,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty" pg:",type:varchar(50),pk,notnull"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,2,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty" pg:",type:varchar(100),pk,notnull"`
	// 속성명
	Attribute string `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty" pg:",type:varchar(100),pk,notnull"`
	// 값
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" pg:",type:varchar(200),notnull"`
	// 마지막 업데이트 일시
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	mi := &file_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{11}
}

func (x *ProductAttribute) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ProductAttribute) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *ProductAttribute) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *ProductAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProductAttribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProductHistory
//
// Product 모델의 이력을 관리한다.
type ProductHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 이력 발생 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,2,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty" pg:",type:varchar(50),notnull"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,3,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty" pg:",type:varchar(100),notnull"`
	// 관리 이력 코드
	Action ProductHistory_Kind `protobuf:"varint,4,opt,name=action,proto3,enum=facilities.ProductHistory_Kind" json:"action,omitempty" pg:",type:varchar(7),notnull,use_zero"`
	// 이력을 발생시킨 사용자 ID
	CreatedUserId string `protobuf:"bytes,5,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty" pg:",type:varchar(36),notnull"`
	// 이력 발생 당시의 사용자 이름
	CreatedName string `protobuf:"bytes,6,opt,name=created_name,json=createdName,proto3" json:"created_name,omitempty" pg:",type:varchar(200),notnull,default:'Anonymous'"`
	// 이력을 발생시킨 사용자 정보
	CreatedBy *structpb.Struct `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty" pg:"-"`
	// 상세 이력
	Details       *structpb.Struct `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty" pg:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductHistory) Reset() {
	*x = ProductHistory{}
	mi := &file_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductHistory) ProtoMessage() {}

func (x *ProductHistory) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductHistory.ProtoReflect.Descriptor instead.
func (*ProductHistory) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{12}
}

func (x *ProductHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductHistory) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ProductHistory) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *ProductHistory) GetAction() ProductHistory_Kind {
	if x != nil {
		return x.Action
	}
	return ProductHistory_CREATED
}

func (x *ProductHistory) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *ProductHistory) GetCreatedName() string {
	if x != nil {
		return x.CreatedName
	}
	return ""
}

func (x *ProductHistory) GetCreatedBy() *structpb.Struct {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *ProductHistory) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// ProductUpdateHistory
//
// Product 모델의 변경 이력을 관리한다.
type ProductUpdateHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 이력 발생 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,2,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty" pg:",type:varchar(50),notnull"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,3,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty" pg:",type:varchar(100),notnull"`
	// 기존 값
	Origin string `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty" pg:",type:jsonb"`
	// 변경된 값
	Change        string `protobuf:"bytes,5,opt,name=change,proto3" json:"change,omitempty" pg:",type:jsonb"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateHistory) Reset() {
	*x = ProductUpdateHistory{}
	mi := &file_products_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateHistory) ProtoMessage() {}

func (x *ProductUpdateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateHistory.ProtoReflect.Descriptor instead.
func (*ProductUpdateHistory) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{13}
}

func (x *ProductUpdateHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductUpdateHistory) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ProductUpdateHistory) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *ProductUpdateHistory) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ProductUpdateHistory) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

// ProductControl
//
// 제품에 제어 설정 관리
type ProductControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 제어 설정 ID
	ControlId string `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty" pg:",type:uuid,pk,notnull,default:gen_random_uuid()"`
	// 제조사 ID
	ManufactureId string `protobuf:"bytes,2,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty" pg:",type:varchar(50),notnull"`
	// 모델 번호
	ModelNumber string `protobuf:"bytes,3,opt,name=model_number,json=modelNumber,proto3" json:"model_number,omitempty" pg:",type:varchar(100),notnull"`
	// 제어 이름
	ControlName string `protobuf:"bytes,4,opt,name=control_name,json=controlName,proto3" json:"control_name,omitempty" pg:",type:varchar(100),notnull"`
	// 연결된 Modbus 주소
	Modbus uint32 `protobuf:"varint,5,opt,name=modbus,proto3" json:"modbus,omitempty" pg:",type:integer,notnull"`
	// 센서 타입
	SensorType string `protobuf:"bytes,6,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty" pg:",type:varchar(100),notnull"`
	// 센서 타입 이름
	SensorTypeName string `protobuf:"bytes,7,opt,name=sensor_type_name,json=sensorTypeName,proto3" json:"sensor_type_name,omitempty" pg:"-"`
	// 명령어
	Command string `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty" pg:",type:varchar(200),notnull"`
	// 제어 명령
	//
	// go template 문법을 사용하며 제어 명령에서 해당 값을 입력한다.
	Payload string `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty" pg:",type:varchar(1000),notnull"`
	// 관련 채널 번호
	Channels []string `protobuf:"bytes,10,rep,name=channels,proto3" json:"channels,omitempty" pg:"-"`
	// 마지막 업데이트 일시
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductControl) Reset() {
	*x = ProductControl{}
	mi := &file_products_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductControl) ProtoMessage() {}

func (x *ProductControl) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductControl.ProtoReflect.Descriptor instead.
func (*ProductControl) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{14}
}

func (x *ProductControl) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ProductControl) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

func (x *ProductControl) GetModelNumber() string {
	if x != nil {
		return x.ModelNumber
	}
	return ""
}

func (x *ProductControl) GetControlName() string {
	if x != nil {
		return x.ControlName
	}
	return ""
}

func (x *ProductControl) GetModbus() uint32 {
	if x != nil {
		return x.Modbus
	}
	return 0
}

func (x *ProductControl) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *ProductControl) GetSensorTypeName() string {
	if x != nil {
		return x.SensorTypeName
	}
	return ""
}

func (x *ProductControl) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProductControl) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ProductControl) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ProductControl) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_products_proto protoreflect.FileDescriptor

const file_products_proto_rawDesc = "" +
	"\n" +
	"\x0eproducts.proto\x12\n" +
	"facilities\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a%sdlmicro/middleware/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\x0eProductRequest\x12/\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tB\b\x92A\x02x2\xe0A\x02R\rmanufactureId\x12+\n" +
	"\fmodel_number\x18\x02 \x01(\tB\b\x92A\x02xd\xe0A\x02R\vmodelNumber\"\x98\x04\n" +
	"\x14SearchProductRequest\x12A\n" +
	"\x05order\x18\x01 \x03(\x0e2&.facilities.SearchProductRequest.OrderB\x03\xe0A\x01R\x05order\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x04B\x03\xe0A\x01R\x05limit\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x04B\x03\xe0A\x01R\x06offset\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tB\x03\xe0A\x01R\x06search\x12/\n" +
	"\x0emanufacture_id\x18\x05 \x01(\tB\b\x92A\x02x2\xe0A\x01R\rmanufactureId\x12.\n" +
	"\x10manufacture_name\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fmanufactureName\x12\x1e\n" +
	"\x05model\x18\a \x01(\tB\b\x92A\x02xd\xe0A\x01R\x05model\x12\x1d\n" +
	"\x04name\x18\t \x01(\tB\t\x92A\x03x\xc8\x01\xe0A\x01R\x04name\"\xc7\x01\n" +
	"\x05Order\x12\x16\n" +
	"\x12manufacture_id_asc\x10\x00\x12\x17\n" +
	"\x13manufacture_id_desc\x10\x01\x12\x18\n" +
	"\x14manufacture_name_asc\x10\x02\x12\x19\n" +
	"\x15manufacture_name_desc\x10\x03\x12\x14\n" +
	"\x10model_number_asc\x10\x04\x12\x15\n" +
	"\x11model_number_desc\x10\x05\x12\x14\n" +
	"\x10product_name_asc\x10\x06\x12\x15\n" +
	"\x11product_name_desc\x10\a\"\xd8\x01\n" +
	"\x15SearchProductResponse\x12/\n" +
	"\bentities\x18\x01 \x03(\v2\x13.facilities.ProductR\bentities\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12?\n" +
	"\x04link\x18\x03 \x03(\v2+.facilities.SearchProductResponse.LinkEntryR\x04link\x1a7\n" +
	"\tLinkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\x14UpdateProductRequest\x12/\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tB\b\x92A\x02x2\xe0A\x02R\rmanufactureId\x12+\n" +
	"\fmodel_number\x18\x02 \x01(\tB\b\x92A\x02xd\xe0A\x02R\vmodelNumber\x12i\n" +
	"\apayload\x18\x03 \x03(\v2-.facilities.UpdateProductRequest.PayloadEntryB \x92A\x1aJ\x18{\"description\": \"value\"}\xe0A\x02R\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x16ProductHistoryResponse\x128\n" +
	"\thistories\x18\x02 \x03(\v2\x1a.facilities.ProductHistoryR\thistories\"\xa1\x01\n" +
	"\x15CommandProductRequest\x12/\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tB\b\x92A\x02x2\xe0A\x02R\rmanufactureId\x12+\n" +
	"\fmodel_number\x18\x02 \x01(\tB\b\x92A\x02xd\xe0A\x02R\vmodelNumber\x12\x18\n" +
	"\x06delete\x18\x03 \x01(\bH\x00R\x06deleteB\x10\n" +
	"\acommand\x12\x05\xbaH\x02\b\x01\".\n" +
	"\x16CommandProductResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"\xa9\x03\n" +
	"\x1bUpdateControlProductRequest\x12/\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tB\b\x92A\x02x2\xe0A\x02R\rmanufactureId\x12+\n" +
	"\fmodel_number\x18\x02 \x01(\tB\b\x92A\x02xd\xe0A\x02R\vmodelNumber\x12*\n" +
	"\n" +
	"control_id\x18\x03 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\tcontrolId\x12Y\n" +
	"\vsensor_type\x18\x04 \x01(\tB8\x92A2J\x11\"agsmotor_green2\"xd\x8a\x01\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe0A\x02R\n" +
	"sensorType\x12_\n" +
	"\acommand\x18\x05 \x01(\tBE\x92A?J\x1d\"set_agsmotor_operation_req2\"x\xc8\x01\x8a\x01\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe0A\x02R\acommand\x12D\n" +
	"\apayload\x18\x06 \x01(\tB*\x92A\x1aJ\x15\"{\\\"2\\\": {{.ratio}}}\"x\xe8\a\xe0A\x02\xbaH\ar\x05\x10\x02\x18\xe8\aR\apayload\"\x94\x01\n" +
	"\x15ControlProductRequest\x12/\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tB\b\x92A\x02x2\xe0A\x02R\rmanufactureId\x12+\n" +
	"\fmodel_number\x18\x02 \x01(\tB\b\x92A\x02xd\xe0A\x02R\vmodelNumber\x12\x1d\n" +
	"\n" +
	"control_id\x18\x03 \x01(\tR\tcontrolId\"P\n" +
	"\x16ControlProductResponse\x126\n" +
	"\bentities\x18\x01 \x03(\v2\x1a.facilities.ProductControlR\bentities\"\xa0\x06\n" +
	"\aProduct\x12m\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tBF\x92A\x02x2\xe0A\x02\xe2\xde\x1f:\n" +
	"\x1c,type:varchar(50),notnull,pk\x1a\x1aproducts_manufacture_id_fkR\rmanufactureId\x12`\n" +
	"\fmodel_number\x18\x02 \x01(\tB=\x92A\x05xd\x80\x01\x02\xe0A\x02\xbaH\fr\n" +
	"\x10\x02\x18dZ\x01\tZ\x01\n" +
	"\xe2\xde\x1f\x1f\n" +
	"\x1d,type:varchar(100),notnull,pkR\vmodelNumber\x12E\n" +
	"\vmanufacture\x18\x03 \x01(\v2\x17.google.protobuf.StructB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\vmanufacture\x12R\n" +
	"\fproduct_name\x18\x04 \x01(\tB/\x92A\x03x\xc8\x01\xe0A\x01\xbaH\vr\t\x18\xc8\x01Z\x01\tZ\x01\n" +
	"\xe2\xde\x1f\x14\n" +
	"\x12,type:varchar(200)R\vproductName\x12k\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x01\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12\xa1\x01\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2#.facilities.Product.AttributesEntryB\\\x92A\x1cJ\x1a{\"<ATTRIBUTE>\": \"<VALUE>\"}\xe0A\x01\xbaH0\x9a\x01-\"\"r \x10\x03\x18d2\x1a^[a-z][a-z0-9_]*[a-z0-9]+$*\ar\x05\x10\x01\x18\xc8\x01\xe2\xde\x1f\x03\n" +
	"\x01-R\n" +
	"attributes\x12&\n" +
	"\bwritable\x18\a \x01(\bB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\bwritable\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:1\xda\xde\x1f-\n" +
	"+\n" +
	"\x1aproducts_manufacture_id_fk\x12\x04Site\x1a\asite_id\"\xca\x05\n" +
	"\x10ProductAttribute\x12|\n" +
	"\x0emanufacture_id\x18\x01 \x01(\tBU\xe2\xde\x1fQ\n" +
	"\x1c,type:varchar(50),pk,notnull\x1a1product_attributes_manufacture_id_model_number_fkR\rmanufactureId\x12y\n" +
	"\fmodel_number\x18\x02 \x01(\tBV\xe2\xde\x1fR\n" +
	"\x1d,type:varchar(100),pk,notnull\x1a1product_attributes_manufacture_id_model_number_fkR\vmodelNumber\x12A\n" +
	"\tattribute\x18\x03 \x01(\tB#\xe2\xde\x1f\x1f\n" +
	"\x1d,type:varchar(100),pk,notnullR\tattribute\x126\n" +
	"\x05value\x18\x04 \x01(\tB \xe2\xde\x1f\x1c\n" +
	"\x1a,type:varchar(200),notnullR\x05value\x12k\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x03\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tupdatedAt:\xd4\x01\xda\xde\x1f\xcf\x01\n" +
	"\\\n" +
	"1product_attributes_manufacture_id_model_number_fk\x12\aProduct\x1a\x0emanufacture_id\x1a\fmodel_number \x01\x1ao\n" +
	"<product_attributes_manufacture_id_model_number_attribute_key\x12\x10\n" +
	"\x0emanufacture_id\x12\x0e\n" +
	"\fmodel_number\x12\v\n" +
	"\tattribute\x18\x01\"\xbc\a\n" +
	"\x0eProductHistory\x12k\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x05\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12I\n" +
	"\x0emanufacture_id\x18\x02 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(50),notnullR\rmanufactureId\x12F\n" +
	"\fmodel_number\x18\x03 \x01(\tB#\xe0A\x05\xe2\xde\x1f\x1c\n" +
	"\x1a,type:varchar(100),notnullR\vmodelNumber\x12c\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1f.facilities.ProductHistory.KindB*\xe0A\x05\xe2\xde\x1f#\n" +
	"!,type:varchar(7),notnull,use_zeroR\x06action\x12J\n" +
	"\x0fcreated_user_id\x18\x05 \x01(\tB\"\xe0A\x05\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(36),notnullR\rcreatedUserId\x12]\n" +
	"\fcreated_name\x18\x06 \x01(\tB:\xe0A\x04\xe0A\x05\xe2\xde\x1f0\n" +
	".,type:varchar(200),notnull,default:'Anonymous'R\vcreatedName\x12\xfb\x01\n" +
	"\n" +
	"created_by\x18\a \x01(\v2\x17.google.protobuf.StructB\xc2\x01\x92A\xb4\x01@\x01J\xaf\x01{\"email\": \"example@suredatalab.com\", \"first_name\": \"길동\", \"last_name\": \"홍\", \"username\": \"example\", \"name\": \"홍길동\", \"user_id\": \"UUID_000010\"}\xe0A\x05\xe2\xde\x1f\x03\n" +
	"\x01-R\tcreatedBy\x12=\n" +
	"\adetails\x18\b \x01(\v2\x17.google.protobuf.StructB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\adetails\"-\n" +
	"\x04Kind\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02:.\xda\xde\x1f*\x12(\n" +
	"\n" +
	"created_at\x12\x061 week\x1a\x12\x1a\x0emanufacture_id \n" +
	"\"\x93\x03\n" +
	"\x14ProductUpdateHistory\x12h\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB-\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tcreatedAt\x12F\n" +
	"\x0emanufacture_id\x18\x02 \x01(\tB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(50),notnullR\rmanufactureId\x12C\n" +
	"\fmodel_number\x18\x03 \x01(\tB \xe2\xde\x1f\x1c\n" +
	"\x1a,type:varchar(100),notnullR\vmodelNumber\x12)\n" +
	"\x06origin\x18\x04 \x01(\tB\x11\xe2\xde\x1f\r\n" +
	"\v,type:jsonbR\x06origin\x12)\n" +
	"\x06change\x18\x05 \x01(\tB\x11\xe2\xde\x1f\r\n" +
	"\v,type:jsonbR\x06change:.\xda\xde\x1f*\x12(\n" +
	"\n" +
	"created_at\x12\x061 week\x1a\x12\x1a\x0emanufacture_id \n" +
	"\"\xf1\v\n" +
	"\x0eProductControl\x12Z\n" +
	"\n" +
	"control_id\x18\x01 \x01(\tB;\xe0A\x03\xe0A\x05\xe2\xde\x1f1\n" +
	"/,type:uuid,pk,notnull,default:gen_random_uuid()R\tcontrolId\x12\x8d\x01\n" +
	"\x0emanufacture_id\x18\x02 \x01(\tBf\x92A\x02x2\xe0A\x02\xe0A\x05\xbaH\x06r\x04\x10\x01\x182\xe2\xde\x1fN\n" +
	"\x19,type:varchar(50),notnull\x1a1product_controls_manufacture_id_model_number_fkeyR\rmanufactureId\x12\x8a\x01\n" +
	"\fmodel_number\x18\x03 \x01(\tBg\x92A\x02xd\xe0A\x02\xe0A\x05\xbaH\x06r\x04\x10\x01\x18d\xe2\xde\x1fO\n" +
	"\x1a,type:varchar(100),notnull\x1a1product_controls_manufacture_id_model_number_fkeyR\vmodelNumber\x12s\n" +
	"\fcontrol_name\x18\x04 \x01(\tBP\x92A\x18J\x14\"1중 좌측 측창\"xd\xe0A\x02\xe0A\x05\xbaH\fr\n" +
	"\x10\x01\x18dZ\x01\tZ\x01\n" +
	"\xe2\xde\x1f\x1c\n" +
	"\x1a,type:varchar(100),notnullR\vcontrolName\x126\n" +
	"\x06modbus\x18\x05 \x01(\rB\x1e\xe0A\x02\xe2\xde\x1f\x17\n" +
	"\x15,type:integer,notnullR\x06modbus\x12\xbd\x01\n" +
	"\vsensor_type\x18\x06 \x01(\tB\x9b\x01\x92A1J\x10\"agsmotor_green\"xd\x8a\x01\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe0A\x02\xbaH\x1er\x1c2\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe2\xde\x1f?\n" +
	"\x1a,type:varchar(100),notnull\x1a!product_controls_sensor_type_fkeyR\n" +
	"sensorType\x124\n" +
	"\x10sensor_type_name\x18\a \x01(\tB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\x0esensorTypeName\x12\xa0\x01\n" +
	"\acommand\x18\b \x01(\tB\x85\x01\x92A>J\x1c\"set_agsmotor_operation_req\"x\xc8\x01\x8a\x01\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe0A\x02\xbaH\x1er\x1c2\x1a^[a-z][a-z0-9_]*[a-z0-9]+$\xe2\xde\x1f\x1c\n" +
	"\x1a,type:varchar(200),notnullR\acommand\x12d\n" +
	"\apayload\x18\t \x01(\tBJ\x92A\x1aJ\x15\"{\\\"1\\\": {{.ratio}}}\"x\xe8\a\xe0A\x02\xbaH\x06r\x04\x10\x02\x18d\xe2\xde\x1f\x1d\n" +
	"\x1b,type:varchar(1000),notnullR\apayload\x12&\n" +
	"\bchannels\x18\n" +
	" \x03(\tB\n" +
	"\xe0A\x03\xe2\xde\x1f\x03\n" +
	"\x01-R\bchannels\x12k\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB0\xe0A\x03\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\tupdatedAt:\xa4\x02\xda\xde\x1f\x9f\x02\n" +
	"\\\n" +
	"1product_controls_manufacture_id_model_number_fkey\x12\aProduct\x1a\x0emanufacture_id\x1a\fmodel_number \x01\n" +
	"8\n" +
	"!product_controls_sensor_type_fkey\x12\n" +
	"SensorType\x1a\atype_id\x1a\x84\x01\n" +
	"Dproduct_controls_manufacture_id_model_number_control_name_modbus_key\x12\x10\n" +
	"\x0emanufacture_id\x12\x0e\n" +
	"\fmodel_number\x12\x0e\n" +
	"\fcontrol_name\x12\b\n" +
	"\x06modbus\x18\x012\xd9\x12\n" +
	"\bProducts\x12\x8e\x01\n" +
	"\rSearchProduct\x12 .facilities.SearchProductRequest\x1a!.facilities.SearchProductResponse\"8\xd2\xde\x1f#\n" +
	"\x0equery-products\n" +
	"\x0fmanage-products \x02\x82\xd3\xe4\x93\x02\v\x12\t/products\x12\xb5\x01\n" +
	"\rCreateProduct\x12\x13.facilities.Product\x1a\x13.facilities.Product\"z\x92A<J:\n" +
	"\x03409\x123\n" +
	")Returned when the resource already exist.\x12\x062\x04null\xd2\xde\x1f\x12\n" +
	"\x0ecreate-product \x01\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/products/{manufacture_id}\x12\x94\x01\n" +
	"\bProducts\x12\x1a.facilities.ProductRequest\x1a\x13.facilities.Product\"W\xd2\xde\x1f\"\n" +
	"\rview-products\n" +
	"\x0fmanage-products \x05\x82\xd3\xe4\x93\x02+\x12)/products/{manufacture_id}/{model_number}\x12\xb3\x01\n" +
	"\x10ProductHistories\x12\x1a.facilities.ProductRequest\x1a\".facilities.ProductHistoryResponse\"_\xd2\xde\x1f \n" +
	"\rview-products\n" +
	"\x0fmanage-products\x82\xd3\xe4\x93\x025\x123/products/{manufacture_id}/{model_number}/histories\x12\xbf\x01\n" +
	"\x0eReplaceProduct\x12\x13.facilities.Product\x1a\x13.facilities.Product\"\x82\x01\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products \x03\x82\xd3\xe4\x93\x02e:\x01*Z5:\x01*\"0/products/{manufacture_id}/{model_number}/update\x1a)/products/{manufacture_id}/{model_number}\x12\xa4\x01\n" +
	"\rUpdateProduct\x12 .facilities.UpdateProductRequest\x1a\x13.facilities.Product\"\\\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products \x04\x82\xd3\xe4\x93\x02?:\apayload24/products/{manufacture_id}/{model_number}/attributes\x12\xc4\x01\n" +
	"\rDeleteProduct\x12\x1a.facilities.ProductRequest\x1a\x16.google.protobuf.Empty\"\x7f\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products c\x82\xd3\xe4\x93\x02bZ5:\x01*\"0/products/{manufacture_id}/{model_number}/delete*)/products/{manufacture_id}/{model_number}\x12\xb6\x01\n" +
	"\x14CreateControlProduct\x12\x1a.facilities.ProductControl\x1a\x1a.facilities.ProductControl\"f\x92A\x0f\n" +
	"\r제어 설정\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products \x1e\x82\xd3\xe4\x93\x027:\x01*\"2/products/{manufacture_id}/{model_number}/controls\x12\xa0\x02\n" +
	"\x14UpdateControlProduct\x12'.facilities.UpdateControlProductRequest\x1a\x1a.facilities.ProductControl\"\xc2\x01\x92A\x0f\n" +
	"\r제어 설정\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products \x1f\x82\xd3\xe4\x93\x02\x92\x01:\x01*ZL:\x01*\"G/products/{manufacture_id}/{model_number}/controls/{control_id}/setting\x1a?/products/{manufacture_id}/{model_number}/controls/{control_id}\x12\xcb\x01\n" +
	"\x0eControlProduct\x12!.facilities.ControlProductRequest\x1a\".facilities.ControlProductResponse\"r\x92A\x0f\n" +
	"\r제어 설정\xd2\xde\x1f\"\n" +
	"\rview-products\n" +
	"\x0fview-facilities  \x82\xd3\xe4\x93\x024\x122/products/{manufacture_id}/{model_number}/controls\x12\x92\x02\n" +
	"\x14DeleteControlProduct\x12!.facilities.ControlProductRequest\x1a\x16.google.protobuf.Empty\"\xbe\x01\x92A\x0f\n" +
	"\r제어 설정\xd2\xde\x1f\x13\n" +
	"\x0fmanage-products a\x82\xd3\xe4\x93\x02\x8e\x01ZK:\x01*\"F/products/{manufacture_id}/{model_number}/controls/{control_id}/delete*?/products/{manufacture_id}/{model_number}/controls/{control_id}\x1a\xc7\x01\x92A\x0f\x12\r제품 관리\xca\xde\x1f\xb0\x01\n" +
	"&\n" +
	"\x0ecreate-product\x12\x14제품 생성 권한\n" +
	"'\n" +
	"\x0fmanage-products\x12\x14제품 관리 권한\n" +
	"&\n" +
	"\x0equery-products\x12\x14제품 검색 권한\n" +
	"%\n" +
	"\rview-products\x12\x14제품 조회 권한\x12\x0efacility-adminB*Z(gitlab.suredatalab.kr/beymons/facilitiesb\x06proto3"

var (
	file_products_proto_rawDescOnce sync.Once
	file_products_proto_rawDescData []byte
)

func file_products_proto_rawDescGZIP() []byte {
	file_products_proto_rawDescOnce.Do(func() {
		file_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)))
	})
	return file_products_proto_rawDescData
}

var file_products_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_products_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_products_proto_goTypes = []any{
	(SearchProductRequest_Order)(0),     // 0: facilities.SearchProductRequest.Order
	(ProductHistory_Kind)(0),            // 1: facilities.ProductHistory.Kind
	(*ProductRequest)(nil),              // 2: facilities.ProductRequest
	(*SearchProductRequest)(nil),        // 3: facilities.SearchProductRequest
	(*SearchProductResponse)(nil),       // 4: facilities.SearchProductResponse
	(*UpdateProductRequest)(nil),        // 5: facilities.UpdateProductRequest
	(*ProductHistoryResponse)(nil),      // 6: facilities.ProductHistoryResponse
	(*CommandProductRequest)(nil),       // 7: facilities.CommandProductRequest
	(*CommandProductResponse)(nil),      // 8: facilities.CommandProductResponse
	(*UpdateControlProductRequest)(nil), // 9: facilities.UpdateControlProductRequest
	(*ControlProductRequest)(nil),       // 10: facilities.ControlProductRequest
	(*ControlProductResponse)(nil),      // 11: facilities.ControlProductResponse
	(*Product)(nil),                     // 12: facilities.Product
	(*ProductAttribute)(nil),            // 13: facilities.ProductAttribute
	(*ProductHistory)(nil),              // 14: facilities.ProductHistory
	(*ProductUpdateHistory)(nil),        // 15: facilities.ProductUpdateHistory
	(*ProductControl)(nil),              // 16: facilities.ProductControl
	nil,                                 // 17: facilities.SearchProductResponse.LinkEntry
	nil,                                 // 18: facilities.UpdateProductRequest.PayloadEntry
	nil,                                 // 19: facilities.Product.AttributesEntry
	(*structpb.Struct)(nil),             // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 22: google.protobuf.Empty
}
var file_products_proto_depIdxs = []int32{
	0,  // 0: facilities.SearchProductRequest.order:type_name -> facilities.SearchProductRequest.Order
	12, // 1: facilities.SearchProductResponse.entities:type_name -> facilities.Product
	17, // 2: facilities.SearchProductResponse.link:type_name -> facilities.SearchProductResponse.LinkEntry
	18, // 3: facilities.UpdateProductRequest.payload:type_name -> facilities.UpdateProductRequest.PayloadEntry
	14, // 4: facilities.ProductHistoryResponse.histories:type_name -> facilities.ProductHistory
	16, // 5: facilities.ControlProductResponse.entities:type_name -> facilities.ProductControl
	20, // 6: facilities.Product.manufacture:type_name -> google.protobuf.Struct
	21, // 7: facilities.Product.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: facilities.Product.attributes:type_name -> facilities.Product.AttributesEntry
	21, // 9: facilities.ProductAttribute.updated_at:type_name -> google.protobuf.Timestamp
	21, // 10: facilities.ProductHistory.created_at:type_name -> google.protobuf.Timestamp
	1,  // 11: facilities.ProductHistory.action:type_name -> facilities.ProductHistory.Kind
	20, // 12: facilities.ProductHistory.created_by:type_name -> google.protobuf.Struct
	20, // 13: facilities.ProductHistory.details:type_name -> google.protobuf.Struct
	21, // 14: facilities.ProductUpdateHistory.created_at:type_name -> google.protobuf.Timestamp
	21, // 15: facilities.ProductControl.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 16: facilities.Products.SearchProduct:input_type -> facilities.SearchProductRequest
	12, // 17: facilities.Products.CreateProduct:input_type -> facilities.Product
	2,  // 18: facilities.Products.Products:input_type -> facilities.ProductRequest
	2,  // 19: facilities.Products.ProductHistories:input_type -> facilities.ProductRequest
	12, // 20: facilities.Products.ReplaceProduct:input_type -> facilities.Product
	5,  // 21: facilities.Products.UpdateProduct:input_type -> facilities.UpdateProductRequest
	2,  // 22: facilities.Products.DeleteProduct:input_type -> facilities.ProductRequest
	16, // 23: facilities.Products.CreateControlProduct:input_type -> facilities.ProductControl
	9,  // 24: facilities.Products.UpdateControlProduct:input_type -> facilities.UpdateControlProductRequest
	10, // 25: facilities.Products.ControlProduct:input_type -> facilities.ControlProductRequest
	10, // 26: facilities.Products.DeleteControlProduct:input_type -> facilities.ControlProductRequest
	4,  // 27: facilities.Products.SearchProduct:output_type -> facilities.SearchProductResponse
	12, // 28: facilities.Products.CreateProduct:output_type -> facilities.Product
	12, // 29: facilities.Products.Products:output_type -> facilities.Product
	6,  // 30: facilities.Products.ProductHistories:output_type -> facilities.ProductHistoryResponse
	12, // 31: facilities.Products.ReplaceProduct:output_type -> facilities.Product
	12, // 32: facilities.Products.UpdateProduct:output_type -> facilities.Product
	22, // 33: facilities.Products.DeleteProduct:output_type -> google.protobuf.Empty
	16, // 34: facilities.Products.CreateControlProduct:output_type -> facilities.ProductControl
	16, // 35: facilities.Products.UpdateControlProduct:output_type -> facilities.ProductControl
	11, // 36: facilities.Products.ControlProduct:output_type -> facilities.ControlProductResponse
	22, // 37: facilities.Products.DeleteControlProduct:output_type -> google.protobuf.Empty
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_products_proto_init() }
func file_products_proto_init() {
	if File_products_proto != nil {
		return
	}
	file_products_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandProductRequest_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_proto_goTypes,
		DependencyIndexes: file_products_proto_depIdxs,
		EnumInfos:         file_products_proto_enumTypes,
		MessageInfos:      file_products_proto_msgTypes,
	}.Build()
	File_products_proto = out.File
	file_products_proto_goTypes = nil
	file_products_proto_depIdxs = nil
}
