apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  backoffLimit: 0  # 실패 시 재시도하지 않음
  template:
    spec:
      serviceAccountName: {{ .Values.namespace }}-clusteradmin-resource
      containers:
      - name: {{ .Values.name }}
        image: docker.io/bitnamilegacy/kubectl:1.33.4-debian-12-r0
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c", "--"]
        args: ["kubectl {{ .Values.status }} {{ .Values.node }}"]
        volumeMounts:
        - mountPath: /jf-bin/.kube
          name: jf-bin
          subPath: .kube
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-d8ccg
          readOnly: true
      volumes:
      - name: jf-bin
        persistentVolumeClaim:
          claimName: jf-bin-pvc
      - name: kube-api-access-d8ccg
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
      restartPolicy: Never
