FROM python:3.11.5

COPY requirements.txt /requirements.txt
WORKDIR /
RUN pip install -r requirements.txt

# RUN pip install fastapi==0.103.1 uvicorn==0.23.2 pydantic==2.4.1 \
#     fastapi-restful==0.5.0 fastapi-restful-extension==0.4.2 typing-inspect==0.9.0 Werkzeug==2.3.7 \
#     kubernetes==28.1.0 paramiko==3.3.1   \
#     starlette-context==0.3.6

RUN pip install flask==1.1.2 flask_cors==3.0.9 flask_restful==0.3.8 flask_restplus==0.13.0