spec:
  inputs:
    appName: 
      description: Job 이름의 접두사로 사용할 앱 이름으로 고유하게 지정해 주세요
      default: "CI 예제"
    dirName:
      description: 현재 디렉토리로 devops 폴더 안의 폴더 이름을 default 값으로 지정해 주세요.
      default: "walking_skeleton_dummy"
---

stages:
  - preflight
  - build
  - test
  - push
  - deploy

include:
  - local: devops/ci-commons/general.gitlab-ci.yml # 일반 템플릿 로드

".$[[ inputs.appName ]].when_devops_changed": # rules:changes가 extends된 변수를 인식하지 못하는 버그가 있어서 추가로 작성 필요
  rules:
    - changes:
      - devops/$[[ inputs.dirName ]]/**/* 

".$[[ inputs.appName ]].skip_devops_changed": # rules:changes가 extends된 변수를 인식하지 못하는 버그가 있어서 추가로 작성 필요
  rules:
    - changes:
        - devops/$[[ inputs.dirName ]]/**/* 
      when: never

".$[[ inputs.appName ]].when_any_changed": # rules:changes가 extends된 변수를 인식하지 못하는 버그가 있어서 추가로 작성 필요
  rules:
    - changes:
      - "devops/$[[ inputs.dirName ]]/**/*" 

".$[[ inputs.appName ]].variables": 
  variables:
    DIR_NAME: "walking_skeleton_dummy" # 디렉토리 이름, 수정 필요
    
    DEVOPS_DIR: "${CI_PROJECT_DIR}/devops/${DIR_NAME}" # 데브옵스 경로, 필요 시 수정

"$[[ inputs.appName ]], CI 로드 확인": # 해당 CI 파일 로드 확인용
  stage: preflight
  script:
    - echo "$[[ inputs.appName ]] CI 확인 완료" 

"$[[ inputs.appName ]], 점검":
  extends: ".$[[ inputs.appName ]].variables"
  stage: preflight
  script:
    - echo "더미 점검"

"$[[ inputs.appName ]], 빌드":
  extends: ".$[[ inputs.appName ]].variables"
  stage: build
  script:
    - echo "더미 빌드"

"$[[ inputs.appName ]], 테스트":
  extends: ".$[[ inputs.appName ]].variables"
  stage: test
  script:
    - echo "더미 테스트"

"$[[ inputs.appName ]], 변경 확인":
  extends: 
    - ".$[[ inputs.appName ]].variables"
    - ".$[[ inputs.appName ]].when_devops_changed"
  stage: test
  script:
    - echo "더미 devops 변경 사항 확인됨."

"$[[ inputs.appName ]], 푸시":
  extends: 
    - ".$[[ inputs.appName ]].variables"
    - .general_deploy_needed
  stage: push
  script:
    - echo "더미 푸시"

"$[[ inputs.appName ]], 배포":
  extends: 
    - ".$[[ inputs.appName ]].variables"
    - .general_deploy_needed
  stage: deploy
  script:
    - echo "더미 배포"