apiVersion: v1
kind: Service
metadata:
  name: simple-fast-api-svc
spec:
  type: NodePort # Nodeport 사용
  selector:
    app: simple-fast-api
  ports:
  - protocol: TCP
    port: 80 # 외부에 노출할 포트
    targetPort: 8000 # 위에 containerport로 제시된 포트

