apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfb-registry-deploy
spec:
  selector:
    matchLabels:
      app: jfb-registry
  template:
    metadata:
      labels:
        app: jfb-registry
    spec:
      containers:
        - image: registry:2
          name: jfb-registry
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:5000
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/registry.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/registry.key
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
            - name: certs
              mountPath: /certs
      nodeName: jf-node-09
      volumes:
        - name: certs
          hostPath:
            path: /home/sdb/registry/certs
        - name: data
          hostPath:
            path: /home/sdb/registry/data

