apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  labels:
    role: app-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
  volumeName: pv-{{ .Values.name }}
  storageClassName: ""
