import { BarChartParam, DrawParam } from './BarChartTypes';
declare class BarChart {
    private canvas;
    private ctx;
    private tooltip;
    private data;
    private minXAxis;
    private minYAxis;
    private maxXAxis;
    private maxYAxis;
    private minMax;
    private unitsPerTickX;
    private unitsPerTickY;
    private padding;
    private tickSize;
    private axisColor;
    private font;
    private fontHeight;
    private rangeX;
    private rangeY;
    private numXTicks;
    private numYTicks;
    private x;
    private y;
    private width;
    private height;
    private scaleX;
    private scaleY;
    private xAxisSelector;
    private dataSelector;
    private barWidth;
    private barColor;
    private isAxisDraw;
    private xStart;
    constructor(param: BarChartParam);
    private minAndMax;
    private getLongestValueWidth;
    private calcRelation;
    private drawXAxis;
    private drawXTick;
    private drawXValue;
    private drawYAxis;
    private drawYTick;
    private drawYValue;
    private drawChart;
    private tooltipMaker;
    private drawTooltip;
    draw(draw?: DrawParam): void;
}
export default BarChart;
