// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: collects.proto

package collects

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "gitlab.suredatalab.kr/sdlmicro/middleware/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsRequest_Interval int32

const (
	StatisticsRequest_hours  StatisticsRequest_Interval = 0
	StatisticsRequest_days   StatisticsRequest_Interval = 1
	StatisticsRequest_weeks  StatisticsRequest_Interval = 2
	StatisticsRequest_months StatisticsRequest_Interval = 3
	StatisticsRequest_years  StatisticsRequest_Interval = 4
)

// Enum value maps for StatisticsRequest_Interval.
var (
	StatisticsRequest_Interval_name = map[int32]string{
		0: "hours",
		1: "days",
		2: "weeks",
		3: "months",
		4: "years",
	}
	StatisticsRequest_Interval_value = map[string]int32{
		"hours":  0,
		"days":   1,
		"weeks":  2,
		"months": 3,
		"years":  4,
	}
)

func (x StatisticsRequest_Interval) Enum() *StatisticsRequest_Interval {
	p := new(StatisticsRequest_Interval)
	*p = x
	return p
}

func (x StatisticsRequest_Interval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticsRequest_Interval) Descriptor() protoreflect.EnumDescriptor {
	return file_collects_proto_enumTypes[0].Descriptor()
}

func (StatisticsRequest_Interval) Type() protoreflect.EnumType {
	return &file_collects_proto_enumTypes[0]
}

func (x StatisticsRequest_Interval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatisticsRequest_Interval.Descriptor instead.
func (StatisticsRequest_Interval) EnumDescriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{0, 0}
}

type StatisticsRequest struct {
	state    protoimpl.MessageState     `protogen:"open.v1"`
	Interval StatisticsRequest_Interval `protobuf:"varint,1,opt,name=interval,proto3,enum=collects.StatisticsRequest_Interval" json:"interval,omitempty"`
	// interval을 설정했을 때 기준이 되는 타임존 [Default: Asia/Seoul]
	Timezone string `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// 고객 ID
	SiteId        string `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_collects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsRequest) GetInterval() StatisticsRequest_Interval {
	if x != nil {
		return x.Interval
	}
	return StatisticsRequest_hours
}

func (x *StatisticsRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *StatisticsRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type StatisticsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Entities      []*StatisticsResponse_Statistics `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_collects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticsResponse) GetEntities() []*StatisticsResponse_Statistics {
	if x != nil {
		return x.Entities
	}
	return nil
}

// ReceiveData 모델은 NATS 브로커를 통해 데이터를 푸시하기 위한 구조이다.
type ReceiveData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 고객 ID
	SiteId string `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// Gateway ID
	GatewayId string `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// 원본 크기 (bytes)
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// 데이터 수신 일시
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// 수신 데이터
	Data          *structpb.Struct `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveData) Reset() {
	*x = ReceiveData{}
	mi := &file_collects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveData) ProtoMessage() {}

func (x *ReceiveData) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveData.ProtoReflect.Descriptor instead.
func (*ReceiveData) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveData) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ReceiveData) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ReceiveData) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReceiveData) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *ReceiveData) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// ReceiveHistory 모델은 수신 이력을 관리한다.
type ReceiveHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 데이터 수신 일시
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty" pg:",type:timestamptz,pk,notnull"`
	// 데이터를 전송한 사이트
	SiteId string `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty" pg:",type:varchar(50),pk,notnull"`
	// 수신된 Gateway ID
	GatewayId string `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// 수신된 데이터 크기 (bytes)
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// 데이터 원본
	Origin []byte `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	// 발생된 에러 내용
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// 처리 완료 일시
	ProcessedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty" pg:",type:timestamptz"`
	// 데이터 내 노드 수
	Nodes uint32 `protobuf:"varint,8,opt,name=nodes,proto3" json:"nodes,omitempty"`
	// 데이터 내 센서 수
	Sensors uint32 `protobuf:"varint,9,opt,name=sensors,proto3" json:"sensors,omitempty"`
	// 기록된 데이터 수
	Recorded      uint32 `protobuf:"varint,10,opt,name=recorded,proto3" json:"recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveHistory) Reset() {
	*x = ReceiveHistory{}
	mi := &file_collects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveHistory) ProtoMessage() {}

func (x *ReceiveHistory) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveHistory.ProtoReflect.Descriptor instead.
func (*ReceiveHistory) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiveHistory) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *ReceiveHistory) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ReceiveHistory) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ReceiveHistory) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReceiveHistory) GetOrigin() []byte {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ReceiveHistory) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReceiveHistory) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *ReceiveHistory) GetNodes() uint32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ReceiveHistory) GetSensors() uint32 {
	if x != nil {
		return x.Sensors
	}
	return 0
}

func (x *ReceiveHistory) GetRecorded() uint32 {
	if x != nil {
		return x.Recorded
	}
	return 0
}

// ReceiveStatistics 모델은 수신 통계를 관리한다.
type ReceiveStatistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 통계 기준 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" pg:",type:timestamptz,pk,notnull,default:now()"`
	// 데이터를 전송한 사이트
	SiteId string `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty" pg:",type:varchar(50),pk,notnull"`
	// 수신 건수 (probe)
	Received uint64 `protobuf:"varint,3,opt,name=received,proto3" json:"received,omitempty" pg:",notnull,use_zero"`
	// 기록된 데이터 수 (probe)
	Recorded uint64 `protobuf:"varint,4,opt,name=recorded,proto3" json:"recorded,omitempty" pg:",notnull,use_zero"`
	// 데이터 총량
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty" pg:",notnull,use_zero"`
	// 에러 발생 건수
	Error uint64 `protobuf:"varint,6,opt,name=error,proto3" json:"error,omitempty" pg:",notnull,use_zero"`
	// 작업 시간 합계 (sec)
	WorkTime float64 `protobuf:"fixed64,7,opt,name=work_time,json=workTime,proto3" json:"work_time,omitempty" pg:",notnull,use_zero"`
	// 게이트웨이 수
	Gateway uint32 `protobuf:"varint,8,opt,name=gateway,proto3" json:"gateway,omitempty" pg:",notnull,use_zero"`
	// 노드 수
	Nodes uint64 `protobuf:"varint,9,opt,name=nodes,proto3" json:"nodes,omitempty" pg:",notnull,use_zero"`
	// 센서 수
	Sensors       uint64 `protobuf:"varint,10,opt,name=sensors,proto3" json:"sensors,omitempty" pg:",notnull,use_zero"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveStatistics) Reset() {
	*x = ReceiveStatistics{}
	mi := &file_collects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveStatistics) ProtoMessage() {}

func (x *ReceiveStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveStatistics.ProtoReflect.Descriptor instead.
func (*ReceiveStatistics) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveStatistics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReceiveStatistics) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ReceiveStatistics) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *ReceiveStatistics) GetRecorded() uint64 {
	if x != nil {
		return x.Recorded
	}
	return 0
}

func (x *ReceiveStatistics) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReceiveStatistics) GetError() uint64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ReceiveStatistics) GetWorkTime() float64 {
	if x != nil {
		return x.WorkTime
	}
	return 0
}

func (x *ReceiveStatistics) GetGateway() uint32 {
	if x != nil {
		return x.Gateway
	}
	return 0
}

func (x *ReceiveStatistics) GetNodes() uint64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ReceiveStatistics) GetSensors() uint64 {
	if x != nil {
		return x.Sensors
	}
	return 0
}

// ReceiveRssiHistory 모델은 수신된 데이터에 대한 RSSI 이력을 관리한다.
type ReceiveRssiHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 데이터 수신 일시
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty" pg:",type:timestamptz,pk,notnull,default:now()"`
	// 송신한 장치 ID
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// Index
	Index int32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty" pg:",notnull"`
	// 수신된 장치 ID
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// 수신 강도
	Rssi          int32 `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty" pg:",notnull"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRssiHistory) Reset() {
	*x = ReceiveRssiHistory{}
	mi := &file_collects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRssiHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRssiHistory) ProtoMessage() {}

func (x *ReceiveRssiHistory) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRssiHistory.ProtoReflect.Descriptor instead.
func (*ReceiveRssiHistory) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveRssiHistory) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *ReceiveRssiHistory) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReceiveRssiHistory) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReceiveRssiHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReceiveRssiHistory) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

// LastReceivedHistory 모델은 장치 및 채널별로 마지막으로 수신된 기록을 관리한다.
type LastReceivedHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 수신된 장치 ID
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" pg:",type:varchar(14),pk,notnull"`
	// 수신 채널
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty" pg:",pk,notnull"`
	// 데이터 수신 일시
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty" pg:",type:timestamptz,notnull,default:now()"`
	// 마지막으로 수신한 GW
	GatewayId     string `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty" pg:",type:varchar(14),notnull"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReceivedHistory) Reset() {
	*x = LastReceivedHistory{}
	mi := &file_collects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReceivedHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReceivedHistory) ProtoMessage() {}

func (x *LastReceivedHistory) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReceivedHistory.ProtoReflect.Descriptor instead.
func (*LastReceivedHistory) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{6}
}

func (x *LastReceivedHistory) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LastReceivedHistory) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *LastReceivedHistory) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *LastReceivedHistory) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type StatisticsResponse_Statistics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 통계 기준 일시
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 수신 건수 (probe)
	Received uint64 `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	// 기록된 데이터 수 (probe)
	Recorded uint64 `protobuf:"varint,3,opt,name=recorded,proto3" json:"recorded,omitempty"`
	// 데이터 총량
	Size uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// 에러 발생 건수
	Error uint64 `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	// 작업 시간 합계 (sec)
	WorkTime uint64 `protobuf:"varint,6,opt,name=work_time,json=workTime,proto3" json:"work_time,omitempty"`
	// 게이트웨이 수
	Gateway uint32 `protobuf:"varint,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// 노드 수
	Nodes uint64 `protobuf:"varint,8,opt,name=nodes,proto3" json:"nodes,omitempty"`
	// 센서 수
	Sensors       uint64 `protobuf:"varint,9,opt,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse_Statistics) Reset() {
	*x = StatisticsResponse_Statistics{}
	mi := &file_collects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse_Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse_Statistics) ProtoMessage() {}

func (x *StatisticsResponse_Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_collects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse_Statistics.ProtoReflect.Descriptor instead.
func (*StatisticsResponse_Statistics) Descriptor() ([]byte, []int) {
	return file_collects_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StatisticsResponse_Statistics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StatisticsResponse_Statistics) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetRecorded() uint64 {
	if x != nil {
		return x.Recorded
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetError() uint64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetWorkTime() uint64 {
	if x != nil {
		return x.WorkTime
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetGateway() uint32 {
	if x != nil {
		return x.Gateway
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetNodes() uint64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *StatisticsResponse_Statistics) GetSensors() uint64 {
	if x != nil {
		return x.Sensors
	}
	return 0
}

var File_collects_proto protoreflect.FileDescriptor

const file_collects_proto_rawDesc = "" +
	"\n" +
	"\x0ecollects.proto\x12\bcollects\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a%sdlmicro/middleware/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\x11StatisticsRequest\x12E\n" +
	"\binterval\x18\x01 \x01(\x0e2$.collects.StatisticsRequest.IntervalB\x03\xe0A\x01R\binterval\x12\x1f\n" +
	"\btimezone\x18\x02 \x01(\tB\x03\xe0A\x01R\btimezone\x12\x1c\n" +
	"\asite_id\x18\x03 \x01(\tB\x03\xe0A\x01R\x06siteId\"A\n" +
	"\bInterval\x12\t\n" +
	"\x05hours\x10\x00\x12\b\n" +
	"\x04days\x10\x01\x12\t\n" +
	"\x05weeks\x10\x02\x12\n" +
	"\n" +
	"\x06months\x10\x03\x12\t\n" +
	"\x05years\x10\x04\"\xec\x02\n" +
	"\x12StatisticsResponse\x12C\n" +
	"\bentities\x18\x01 \x03(\v2'.collects.StatisticsResponse.StatisticsR\bentities\x1a\x90\x02\n" +
	"\n" +
	"Statistics\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x04R\breceived\x12\x1a\n" +
	"\brecorded\x18\x03 \x01(\x04R\brecorded\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x14\n" +
	"\x05error\x18\x05 \x01(\x04R\x05error\x12\x1b\n" +
	"\twork_time\x18\x06 \x01(\x04R\bworkTime\x12\x18\n" +
	"\agateway\x18\a \x01(\rR\agateway\x12\x14\n" +
	"\x05nodes\x18\b \x01(\x04R\x05nodes\x12\x18\n" +
	"\asensors\x18\t \x01(\x04R\asensors\"\xd6\x01\n" +
	"\vReceiveData\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12;\n" +
	"\vreceived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12>\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x11\x92A\x0eJ\f{\"data\": []}R\x04data\"\xec\x03\n" +
	"\x0eReceiveHistory\x12_\n" +
	"\vreceived_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:timestamptz,pk,notnullR\n" +
	"receivedAt\x12;\n" +
	"\asite_id\x18\x02 \x01(\tB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(50),pk,notnullR\x06siteId\x12A\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(14),pk,notnullR\tgatewayId\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\fR\x06origin\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12V\n" +
	"\fprocessed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x17\xe2\xde\x1f\x13\n" +
	"\x11,type:timestamptzR\vprocessedAt\x12\x14\n" +
	"\x05nodes\x18\b \x01(\rR\x05nodes\x12\x18\n" +
	"\asensors\x18\t \x01(\rR\asensors\x12\x1a\n" +
	"\brecorded\x18\n" +
	" \x01(\rR\brecorded:\x13\xda\xde\x1f\x0f\x12\r\n" +
	"\vreceived_at\"\xef\x04\n" +
	"\x11ReceiveStatistics\x12k\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe2\xde\x1f,\n" +
	"*,type:timestamptz,pk,notnull,default:now()R\tcreatedAt\x12;\n" +
	"\asite_id\x18\x02 \x01(\tB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(50),pk,notnullR\x06siteId\x123\n" +
	"\breceived\x18\x03 \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\breceived\x123\n" +
	"\brecorded\x18\x04 \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\brecorded\x12+\n" +
	"\x04size\x18\x05 \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\x04size\x12-\n" +
	"\x05error\x18\x06 \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\x05error\x124\n" +
	"\twork_time\x18\a \x01(\x01B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\bworkTime\x121\n" +
	"\agateway\x18\b \x01(\rB\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\agateway\x12-\n" +
	"\x05nodes\x18\t \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\x05nodes\x121\n" +
	"\asensors\x18\n" +
	" \x01(\x04B\x17\xe2\xde\x1f\x13\n" +
	"\x11,notnull,use_zeroR\asensors:\x1f\xda\xde\x1f\x1b\x12\x19\n" +
	"\n" +
	"created_at\x1a\v\x1a\asite_id \n" +
	"\"\xe0\x02\n" +
	"\x12ReceiveRssiHistory\x12m\n" +
	"\vreceived_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB0\xe2\xde\x1f,\n" +
	"*,type:timestamptz,pk,notnull,default:now()R\n" +
	"receivedAt\x12;\n" +
	"\anode_id\x18\x02 \x01(\tB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(14),pk,notnullR\x06nodeId\x12$\n" +
	"\x05index\x18\x03 \x01(\x05B\x0e\xe2\xde\x1f\n" +
	"\n" +
	"\b,notnullR\x05index\x12?\n" +
	"\tdevice_id\x18\x04 \x01(\tB\"\xe2\xde\x1f\x1e\n" +
	"\x1c,type:varchar(14),pk,notnullR\bdeviceId\x12\"\n" +
	"\x04rssi\x18\x05 \x01(\x05B\x0e\xe2\xde\x1f\n" +
	"\n" +
	"\b,notnullR\x04rssi:\x13\xda\xde\x1f\x0f\x12\r\n" +
	"\vreceived_at\"\x98\x03\n" +
	"\x13LastReceivedHistory\x12e\n" +
	"\tdevice_id\x18\x01 \x01(\tBH\xe2\xde\x1fD\n" +
	"\x1c,type:varchar(14),pk,notnull\x1a$last_received_histories_device_id_fkR\bdeviceId\x12+\n" +
	"\achannel\x18\x02 \x01(\rB\x11\xe2\xde\x1f\r\n" +
	"\v,pk,notnullR\achannel\x12j\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB-\xe2\xde\x1f)\n" +
	"',type:timestamptz,notnull,default:now()R\n" +
	"receivedAt\x12>\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tB\x1f\xe2\xde\x1f\x1b\n" +
	"\x19,type:varchar(14),notnullR\tgatewayId:A\xda\xde\x1f=\n" +
	";\n" +
	"$last_received_histories_device_id_fk\x12\x06Device\x1a\tdevice_id \x012\xde\x02\n" +
	"\bCollects\x12K\n" +
	"\x04Send\x12\x15.collects.ReceiveData\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/collects\x12x\n" +
	"\n" +
	"Statistics\x12\x1b.collects.StatisticsRequest\x1a\x1c.collects.StatisticsResponse\"/\xd2\xde\x1f\x0f\n" +
	"\rquery-collect\x82\xd3\xe4\x93\x02\x16\x12\x14/statistics/collects\x1a\x8a\x01\x92A\x1c\x12\x1a데이터 수집 서비스\xca\xde\x1fg\n" +
	"/\n" +
	"\rcollect-admin\x12\x1e수집 서비스 관리 권한\n" +
	"%\n" +
	"\rquery-collect\x12\x14통계 조회 권한\x12\rcollect-adminB(Z&gitlab.suredatalab.kr/beymons/collectsb\x06proto3"

var (
	file_collects_proto_rawDescOnce sync.Once
	file_collects_proto_rawDescData []byte
)

func file_collects_proto_rawDescGZIP() []byte {
	file_collects_proto_rawDescOnce.Do(func() {
		file_collects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collects_proto_rawDesc), len(file_collects_proto_rawDesc)))
	})
	return file_collects_proto_rawDescData
}

var file_collects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_collects_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_collects_proto_goTypes = []any{
	(StatisticsRequest_Interval)(0),       // 0: collects.StatisticsRequest.Interval
	(*StatisticsRequest)(nil),             // 1: collects.StatisticsRequest
	(*StatisticsResponse)(nil),            // 2: collects.StatisticsResponse
	(*ReceiveData)(nil),                   // 3: collects.ReceiveData
	(*ReceiveHistory)(nil),                // 4: collects.ReceiveHistory
	(*ReceiveStatistics)(nil),             // 5: collects.ReceiveStatistics
	(*ReceiveRssiHistory)(nil),            // 6: collects.ReceiveRssiHistory
	(*LastReceivedHistory)(nil),           // 7: collects.LastReceivedHistory
	(*StatisticsResponse_Statistics)(nil), // 8: collects.StatisticsResponse.Statistics
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*structpb.Struct)(nil),               // 10: google.protobuf.Struct
	(*emptypb.Empty)(nil),                 // 11: google.protobuf.Empty
}
var file_collects_proto_depIdxs = []int32{
	0,  // 0: collects.StatisticsRequest.interval:type_name -> collects.StatisticsRequest.Interval
	8,  // 1: collects.StatisticsResponse.entities:type_name -> collects.StatisticsResponse.Statistics
	9,  // 2: collects.ReceiveData.received_at:type_name -> google.protobuf.Timestamp
	10, // 3: collects.ReceiveData.data:type_name -> google.protobuf.Struct
	9,  // 4: collects.ReceiveHistory.received_at:type_name -> google.protobuf.Timestamp
	9,  // 5: collects.ReceiveHistory.processed_at:type_name -> google.protobuf.Timestamp
	9,  // 6: collects.ReceiveStatistics.created_at:type_name -> google.protobuf.Timestamp
	9,  // 7: collects.ReceiveRssiHistory.received_at:type_name -> google.protobuf.Timestamp
	9,  // 8: collects.LastReceivedHistory.received_at:type_name -> google.protobuf.Timestamp
	9,  // 9: collects.StatisticsResponse.Statistics.created_at:type_name -> google.protobuf.Timestamp
	3,  // 10: collects.Collects.Send:input_type -> collects.ReceiveData
	1,  // 11: collects.Collects.Statistics:input_type -> collects.StatisticsRequest
	11, // 12: collects.Collects.Send:output_type -> google.protobuf.Empty
	2,  // 13: collects.Collects.Statistics:output_type -> collects.StatisticsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_collects_proto_init() }
func file_collects_proto_init() {
	if File_collects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collects_proto_rawDesc), len(file_collects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collects_proto_goTypes,
		DependencyIndexes: file_collects_proto_depIdxs,
		EnumInfos:         file_collects_proto_enumTypes,
		MessageInfos:      file_collects_proto_msgTypes,
	}.Build()
	File_collects_proto = out.File
	file_collects_proto_goTypes = nil
	file_collects_proto_depIdxs = nil
}
