// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// source: collects_doc.proto
// source: collects.proto

package server

import "gitlab.suredatalab.kr/sdlmicro/middleware/auth"

func Register() error {
	if err := auth.Register(&auth.RegisterRequest{
		ServiceName: "collects",
		Resources: map[string]string{
			"collect-admin": "수집 서비스 관리 권한",
			"query-collect": "통계 조회 권한",
		},
		AdminRole: "collect-admin",
		Roles: map[string][]string{
			"/collects.Collects/Statistics": {
				"query-collect",
			},
		},
	}); err != nil {
		return err
	}

	return nil
}

func Deregister() error {
	if err := auth.Deregister(); err != nil {
		return err
	}

	return nil
}
