apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-{{ .Values.global.jfb.namespace }}-bin-pv
  labels:
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteMany
  claimRef:
    name: jf-bin-pvc
    namespace: {{ .Values.global.jfb.namespace }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  {{- include "lib.volume.type" .Values.global.jfb.volume.jfBin | nindent 2 }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-bin-pvc
  namespace: {{ .Values.global.jfb.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: ""
---