{{- range $index, $node := .Values.cluster }}
apiVersion: v1
kind: Pod
metadata:
  annotations:
    acryl.ai/appType: user
    {{- if $.Values.rdma.enabled }}
    k8s.v1.cni.cncf.io/networks: default/{{ $node.node_name }}
    {{- end }}
  labels:
    {{- range $key, $val := $.Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    role: "jfb-user-function"
    index: {{ $index | quote }}
    device_type: {{ $node.device.type | default "" | quote }}
    device_model: {{ $node.device.model | default "" | quote }}
    device_count: {{ $node.device.count | default "" | quote }}
    device_ids: {{ $node.device.ids | default "" | quote }}
    node_name: {{ $node.node_name | default "" | quote }}
  name: {{ $.Values.pod_name }}-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  hostname: {{ $.Values.spec.hostname }}
  {{- if $node.node_name }}
  nodeName: {{ $node.node_name }}
  {{- end }}
  {{- if $.Values.spec.cpu_instance_name }}
  nodeSelector:
    jfb/cpu-instance.name: {{ $.Values.spec.cpu_instance_name }}
  {{- end }}
  {{- if $.Values.pullSecrets }}
  imagePullSecrets:
  - name: {{ $.Values.pullSecrets }}
  {{- end }}
  containers:
  - command:
    - /bin/bash
    - -c
    - |
        {{- include "command" (dict "Values" $.Values "node" $node "index" $index) | indent 4 }}
    env:
    {{- range $key, $val := $.Values.spec.containers.env }}
    - name: {{ $key }}
      value: {{ $val | quote }}
    {{- end }}
    - name: JF_NUM_GPUS
      value: "{{ $node.device.count }}"
    - name: JF_POD_INDEX
      value: {{ $index | quote }}
    - name: JF_NUM_PODS
      value: {{ len $.Values.cluster | quote }}
    - name: DEBIAN_FRONTEND
      value: noninteractive
    {{- if and (eq $node.device.type "GPU") $node.device.uuids }}
    - name: "NVIDIA_VISIBLE_DEVICES"
      value: {{ $node.device.uuids }}
    {{- end }}
    {{- if $.Values.rdma.enabled }}
    - name: "JF_RDMA_ENABLED"
      value: {{ $.Values.rdma.enabled | quote }}
    {{- if $.Values.rdma.mp.enabled }}
    - name: "JF_MP_ENABLED"
      value: "true"
    {{- if and $.Values.rdma.mp.seed_num $.Values.rdma.mp.seed_list }}
    {{- range $.Values.rdma.mp.seed_list }}
    {{- if eq .nodeName $node.node_name }}
    {{- if .seed }}
    - name: "JFB_MP_SEED_LIST"
      value: {{ .seed | quote }}
    - name: "JFB_MP_SEED_NUM"
      value: {{ $.Values.rdma.mp.seed_num | quote }} 
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if $.Values.rdma.p2p }}
    {{- range $.Values.rdma.p2p }}
    {{- if eq .nodeName $node.node_name }}
    - name: "JF_RDMA_IS_P2P"
      value: "true"
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }} # rdma    
    {{- include "readinessProbe" (dict "Values" $.Values "node" $node "index" $index) }}
    image: {{ $.Values.spec.containers.image }}
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - echo START
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - echo END
    name: "jonathan-tool"
    resources:
      limits:
        cpu : {{ $.Values.spec.containers.resource.limits.cpu }}
        memory : {{ $.Values.spec.containers.resource.limits.memory }}
        {{- if $.Values.rdma.enabled }}
        rdma/jf_roce: 1
        {{- end }}
      requests:
        cpu : 0.01
        memory : "10M"
        {{- if $.Values.rdma.enabled }}
        rdma/jf_roce: 1
        {{- end }}
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        {{- if $.Values.rdma.enabled }}
        - NET_ADMIN
        {{- end }}
      privileged: false # TODO 기존과 같게 할건지 확인 필요
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - name: jf-main
      mountPath: {{ $.Values.spec.containers.env.JF_HOME}} 
      {{- if $.Values.labels.project_name}}
      subPath: {{ $.Values.labels.pod_type }}s/{{ $.Values.labels.project_name}}/src
      {{- else }}
      subPath: {{ $.Values.labels.pod_type }}s/{{ $.Values.labels.preprocessing_name }}
      {{- end }}
    - name: jf-data
      mountPath: {{ $.Values.spec.containers.env.JF_HOME}}/dataset
      subPath: {{ $.Values.dataset.access }}/{{ $.Values.dataset.name }}
    {{- if ge (int $.Values.total_device_count) 2 }}
      # 분산학습 프레임워크 적용 
    - name: jf-bin
      mountPath: /distributed
      subPath: distributed
      readOnly: true
    {{- end }}
    - name: jf-bin
      mountPath: /support # 오프라인 pod에서 설치할 수 있도록 바이너리 파일 모음 폴더
      subPath: support
      readOnly: true
    - name: jf-bin
      mountPath: /jonathan_tool_packages
      subPath: jonathan_tool_packages
      readOnly: true
    - name: jf-bin
      mountPath: /addlib # 배포 api 코드 임포트 라이브러리 
      subPath: deployment_log
      readOnly: true
    {{- if $.Values.offlineMode }}
    {{- if $.Values.privateRepo }}
    - name: apt-gpg-key
      mountPath: /root/.apt
    {{- end }}
    {{- if $.Values.privatePip }}
    - name: pip-conf
      mountPath: /root/.config/pip
    {{- end }}
    {{- end }}
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostIPC: true
  restartPolicy: {{ $.Values.spec.restartPolicy }}
  terminationGracePeriodSeconds: 0
  volumes:
  {{- if $.Values.offlineMode }}
  {{- if $.Values.privateRepo }}
  - name: apt-gpg-key
    configMap:
      name: jonathan-private-repo-cm
  {{- end }}
  {{- if $.Values.privatePip }}
  - name: pip-conf
    configMap:
      name: jonathan-pip-cm
  {{- end }}
  {{- end }}
  - name: jf-main
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-main-pvc
  - name: jf-data
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-data-pvc
  - name: jf-bin
    persistentVolumeClaim:
      claimName: {{ $.Values.namespace }}-bin-pvc
---
{{- end }}