{
 "title": "inference latency",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Preprocessing Compute Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_preproc\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Compute Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_trt\", quantile=\"0.999\"}",
     "legendFormat": "inference latency"
    },
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_preproc\", quantile=\"0.999\"}",
     "legendFormat": "preprocess latency"
    },
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_postproc\", quantile=\"0.999\"}",
     "legendFormat": "Postprocess latency"
    }
   ]
  },
  {
   "title": "Inference Compute Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_trt\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Input latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_compute_input_summary_us{model=\"yx_trt\", quantile=\"0.999\"}",
     "legendFormat": "Inference input"
    },
    {
     "expr": "nv_inference_compute_input_summary_us{model=\"yx_preproc\", quantile=\"0.999\"}",
     "legendFormat": "Preprocess input"
    },
    {
     "expr": "nv_inference_compute_input_summary_us{model=\"yx_postproc\", quantile=\"0.999\"}",
     "legendFormat": "Postprocess input"
    }
   ]
  },
  {
   "title": "Postprocessing Compute Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_summary_us{model=\"yx_postproc\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Output latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "nv_inference_compute_output_summary_us{model=\"yx_trt\", quantile=\"0.999\"}",
     "legendFormat": "Inference output"
    },
    {
     "expr": "nv_inference_compute_output_summary_us{model=\"yx_preproc\", quantile=\"0.999\"}",
     "legendFormat": "preprocessing output"
    },
    {
     "expr": "nv_inference_compute_output_summary_us{model=\"yx_postproc\", quantile=\"0.999\"}",
     "legendFormat": "post processing output"
    }
   ]
  },
  {
   "title": "Queue Delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_queue_summary_us{model=\"yx_trt\", quantile=\"0.999\"}",
     "legendFormat": "Inference queue delay"
    },
    {
     "expr": "nv_inference_queue_summary_us{model=\"yx_preproc\", quantile=\"0.999\"}",
     "legendFormat": "Preprocess queue delay"
    },
    {
     "expr": "nv_inference_queue_summary_us{model=\"yx_postproc\", quantile=\"0.999\"}",
     "legendFormat": "Postprocess queue delay"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nv_inference_request_summary_us{model=\"yolox_e2e\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "nv_cpu_utilization * 100", "legendFormat": "CPU Utilization" }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "nv_gpu_power_usage", "legendFormat": "GPU Power (w)" },
    { "expr": "nv_gpu_utilization * 100", "legendFormat": "GPU Util. (%)" }
   ]
  }
 ]
}