apiVersion: v1
kind: Service
metadata:
  name: storage-exporter-service
  labels:
    app: storage-exporter
spec:
  type: ClusterIP 
  ports:      
  - name: metrics
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: storage-exporter
